/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (pings DB) */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out (clears session) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user */
        get: operations["me"];
        put?: never;
        post?: never;
        /** Soft-delete the current user (tombstones display_name, scrubs email, clears all sessions) */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /** Rename the current user */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the current user's password (requires old password) */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload an 8x8 avatar PNG (base64-encoded, <= 1024 bytes) */
        put: operations["setAvatar"];
        post?: never;
        /** Remove the current user's avatar (falls back to initials on display) */
        delete: operations["deleteAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve a user's pixelated avatar PNG (group-member access)
         * @description Returns the stored avatar PNG for the user. The source is an 8x8 bitmap
         *     uploaded by the client; the server upscales it with nearest-neighbour
         *     sampling before storage so it renders crisp at any CSS size. Callers
         *     must share at least one group with the target user. Browsers should
         *     cache on `?v={avatar_updated_at}` to avoid stale renders when the owner
         *     updates.
         */
        get: operations["getUserAvatar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List groups the current user belongs to */
        get: operations["listGroups"];
        put?: never;
        /** Create a group */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a group (creator only; cascades) */
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        /** Update a group (rename or change default currency) */
        patch: operations["updateGroup"];
        trace?: never;
    };
    "/v1/groups/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a member to a group (invitee must be registered) */
        post: operations["addGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member (creator removes anyone; members may leave themselves)
         * @description The group creator can remove any non-creator member. Any member may
         *     remove themselves (leave). The creator cannot leave or be removed -
         *     ownership transfer or full group deletion is required first.
         *     The target's net balance for the group must be exactly zero (settle up
         *     first), so removing them never silently writes off debt. If the group
         *     ends up with fewer than 2 members, any pinned `default_split` is
         *     cleared automatically.
         */
        delete: operations["removeGroupMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group expenses (newest first) */
        get: operations["listExpenses"];
        put?: never;
        /** Create an expense */
        post: operations["createExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single expense (members only) */
        get: operations["getExpense"];
        put?: never;
        post?: never;
        /** Soft-delete an expense (any group member) */
        delete: operations["deleteExpense"];
        options?: never;
        head?: never;
        /**
         * Update description, amount, category, or payer (payer or group creator only)
         * @description Editable fields: `description`, `amount_cents`, `category_id`, `payer_id`.
         *     Splits are rescaled proportionally when `amount_cents` changes, preserving
         *     each member's relative share. A row is appended to `expense_revisions`
         *     for every change.
         */
        patch: operations["updateExpense"];
        trace?: never;
    };
    "/v1/expenses/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full edit history of an expense (oldest first) */
        get: operations["listExpenseRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available expense categories (seeded) */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get net balances + simplified pairwise debts for a group */
        get: operations["getBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List settlements in a group */
        get: operations["listSettlements"];
        put?: never;
        /** Record a settlement (one member pays another) */
        post: operations["createSettlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settlements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single settlement by id (member-only) */
        get: operations["getSettlement"];
        put?: never;
        post?: never;
        /** Soft-delete a settlement (any group member) */
        delete: operations["deleteSettlement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the merged activity feed for a group (newest first, paginated) */
        get: operations["listActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/recurring-expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recurring expense templates for a group */
        get: operations["listRecurringExpenses"];
        put?: never;
        /** Create a recurring expense template */
        post: operations["createRecurringExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring-expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a recurring template */
        delete: operations["deleteRecurringExpense"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** Format: date-time */
            created_at: string;
            /** @description True when the user has uploaded a pixel avatar. Fetch it at `/v1/users/{id}/avatar`. */
            has_avatar: boolean;
            /**
             * Format: date-time
             * @description Cache-buster for the avatar URL. Changes on every upload/delete.
             */
            avatar_updated_at?: string;
            /**
             * Format: date-time
             * @description Set when the account has been soft-deleted; `display_name` is then a tombstone.
             */
            deleted_at?: string;
            /**
             * @description First day of the week in calendar UIs. 0 = Sunday, 1 = Monday.
             * @enum {integer}
             */
            week_start: 0 | 1;
            /** @description IANA timezone (e.g. "Europe/Madrid"). Null means the client should use the device-detected zone. */
            timezone?: string | null;
        };
        UpdateMeRequest: {
            display_name?: string;
            /**
             * @description First day of the week. 0 = Sunday, 1 = Monday.
             * @enum {integer}
             */
            week_start?: 0 | 1;
            /** @description IANA timezone (e.g. "Europe/Madrid"). Send an empty string to revert to device detection. */
            timezone?: string;
        };
        ChangePasswordRequest: {
            old_password: string;
            new_password: string;
        };
        SetAvatarRequest: {
            /** @description Base64-encoded PNG. Decoded size must be <= 1024 bytes and the image exactly 8x8 pixels. */
            png_base64: string;
        };
        /**
         * @example {
         *       "email": "alice@example.com",
         *       "password": "correct-horse-battery-staple",
         *       "display_name": "Alice"
         *     }
         */
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Group: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description ISO-4217 code used when expenses omit currency */
            default_currency: string;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            members: components["schemas"]["GroupMember"][];
            /**
             * @description Optional 2-member percentage split that prefills the create-expense form.
             *     Automatically cleared by the server when the group grows past 2 members.
             */
            default_split?: components["schemas"]["DefaultSplitEntry"][];
        };
        DefaultSplitEntry: {
            /** Format: uuid */
            user_id: string;
            /** @description 0..10000; the two entries must sum to exactly 10000. */
            basis_points: number;
        };
        GroupMember: {
            /** Format: uuid */
            user_id: string;
            display_name: string;
            /** Format: date-time */
            joined_at: string;
            has_avatar: boolean;
            /** Format: date-time */
            avatar_updated_at?: string;
            /**
             * Format: date-time
             * @description Set when the user has soft-deleted their account; `display_name` is a tombstone.
             */
            deleted_at?: string;
        };
        /**
         * @example {
         *       "name": "Trip to Lisbon",
         *       "default_currency": "EUR"
         *     }
         */
        CreateGroupRequest: {
            name: string;
            /** @default EUR */
            default_currency: string;
        };
        UpdateGroupRequest: {
            name?: string;
            default_currency?: string;
            /**
             * @description Set the default 2-member split. Pass an empty array (or null) to clear it.
             *     Only valid when the group has exactly 2 members.
             */
            default_split?: components["schemas"]["DefaultSplitEntry"][] | null;
            /**
             * Format: uuid
             * @description Transfer group ownership to another member. Only the current owner
             *     may set this; the target must already be a member of the group.
             */
            created_by?: string;
        };
        AddMemberRequest: {
            /** Format: email */
            email: string;
        };
        /** @enum {string} */
        SplitMode: "equal" | "exact" | "percent" | "shares";
        SplitInput: {
            /** Format: uuid */
            user_id: string;
            /** Format: int64 */
            value?: number;
        };
        Split: {
            /** Format: uuid */
            user_id: string;
            /** Format: int64 */
            share_cents: number;
        };
        /**
         * @example {
         *       "description": "Hotel",
         *       "amount_cents": 20000,
         *       "payer_id": "7a1d5b9e-0c0a-4a12-9a55-0c55cf2b6fb1",
         *       "mode": "equal",
         *       "splits": [
         *         {
         *           "user_id": "7a1d5b9e-0c0a-4a12-9a55-0c55cf2b6fb1"
         *         },
         *         {
         *           "user_id": "9c0e3a31-6b2f-41d7-bf80-7a3f1b6d3d24"
         *         }
         *       ]
         *     }
         */
        CreateExpenseRequest: {
            description: string;
            /** Format: int64 */
            amount_cents: number;
            /** @description Defaults to group.default_currency if omitted */
            currency?: string;
            /** Format: uuid */
            payer_id: string;
            /** Format: date-time */
            incurred_at?: string;
            /**
             * Format: uuid
             * @description Defaults to the `other` category when omitted.
             */
            category_id?: string;
            mode: components["schemas"]["SplitMode"];
            splits: components["schemas"]["SplitInput"][];
        };
        UpdateExpenseRequest: {
            description?: string;
            /** Format: int64 */
            amount_cents?: number;
            /** Format: uuid */
            category_id?: string;
            /**
             * Format: uuid
             * @description New payer; must be a current group member.
             */
            payer_id?: string;
            /**
             * @description Must be supplied together with `splits`. When both are present, the server
             *     re-resolves per-user shares. When neither is present, existing splits are
             *     rescaled proportionally if `amount_cents` changes.
             */
            mode?: components["schemas"]["SplitMode"];
            /** @description Must be supplied together with `mode`. */
            splits?: components["schemas"]["SplitInput"][];
            /**
             * Format: date-time
             * @description When the expense was incurred (independent of when it was recorded).
             *     Defaults to the creation time if omitted on create, then immutable
             *     unless explicitly set here.
             */
            incurred_at?: string;
        };
        Expense: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            description: string;
            /** Format: int64 */
            amount_cents: number;
            currency: string;
            /** Format: uuid */
            payer_id: string;
            /**
             * Format: uuid
             * @description User who recorded the expense. Distinct from `payer_id` (who fronted
             *     the money) - any group member may create an expense on behalf of any
             *     other member, and the history attributes the action to this user.
             */
            created_by: string;
            /** Format: date-time */
            incurred_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            category_id: string;
            splits: components["schemas"]["Split"][];
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** @description Stable machine identifier (e.g. `groceries`). The frontend maps this to an icon. */
            slug: string;
            /** @description Human-readable name. */
            label: string;
            /** @description Section header for the picker (e.g. `Entertainment`, `No category`). */
            group_label: string;
        };
        ExpenseRevision: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            expense_id: string;
            /** Format: uuid */
            edited_by: string;
            /** Format: date-time */
            edited_at: string;
            /**
             * @description Which field was changed.
             * @enum {string}
             */
            field: "description" | "amount_cents" | "category_id" | "payer_id";
            /** @description Previous value, stringified. */
            old_value: string;
            /** @description New value, stringified. */
            new_value: string;
        };
        Balance: {
            /** Format: uuid */
            user_id: string;
            display_name: string;
            /**
             * Format: int64
             * @description positive = owed to user; negative = user owes
             */
            net_cents: number;
        };
        SimplifiedDebt: {
            /** Format: uuid */
            from_user_id: string;
            /** Format: uuid */
            to_user_id: string;
            /** Format: int64 */
            amount_cents: number;
        };
        BalancesResponse: {
            net: components["schemas"]["Balance"][];
            simplified: components["schemas"]["SimplifiedDebt"][];
        };
        CreateSettlementRequest: {
            /** Format: uuid */
            to_user_id: string;
            /** Format: int64 */
            amount_cents: number;
            note?: string;
            /** Format: date-time */
            settled_at?: string;
        };
        Settlement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            /** Format: uuid */
            from_user_id: string;
            /** Format: uuid */
            to_user_id: string;
            /** Format: int64 */
            amount_cents: number;
            note?: string;
            /** Format: date-time */
            settled_at: string;
            /** Format: date-time */
            created_at: string;
        };
        ActivityItem: {
            /** @enum {string} */
            kind: "expense" | "settlement";
            /** Format: date-time */
            occurred_at: string;
            /** @description When kind=expense and the expense matches a recurring template by content, the template's cadence. Omitted otherwise. */
            cadence?: components["schemas"]["Cadence"];
            /** @description Present iff kind=expense. */
            expense?: components["schemas"]["Expense"];
            /** @description Present iff kind=settlement. */
            settlement?: components["schemas"]["Settlement"];
        };
        ActivityPage: {
            items: components["schemas"]["ActivityItem"][];
            /** @description Pass to the next request as `cursor`. Absent when there are no more items. */
            next_cursor?: string;
        };
        /** @enum {string} */
        Cadence: "daily" | "weekly" | "biweekly" | "monthly" | "yearly";
        CreateRecurringExpenseRequest: {
            description: string;
            /** Format: int64 */
            amount_cents: number;
            /** @description Defaults to group.default_currency if omitted */
            currency?: string;
            /** Format: uuid */
            payer_id: string;
            /**
             * Format: uuid
             * @description Defaults to the `other` category when omitted.
             */
            category_id?: string;
            mode: components["schemas"]["SplitMode"];
            splits: components["schemas"]["SplitInput"][];
            cadence: components["schemas"]["Cadence"];
            /** Format: date-time */
            next_run_at: string;
        };
        RecurringExpense: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            description: string;
            /** Format: int64 */
            amount_cents: number;
            currency: string;
            /** Format: uuid */
            payer_id: string;
            /** Format: uuid */
            category_id: string;
            mode: components["schemas"]["SplitMode"];
            splits: components["schemas"]["SplitInput"][];
            cadence: components["schemas"]["Cadence"];
            /** Format: date-time */
            next_run_at: string;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description Invalid input (malformed JSON, failed validation, or unknown field). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid session cookie. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not permitted for this resource. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist (or is hidden by soft-delete). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request conflicts with existing state (e.g. duplicate email). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limited. Retry after the `Retry-After` header. */
        TooManyRequests: {
            headers: {
                /** @description Seconds until the client may retry. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Server is not ready (e.g. DB unreachable). */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        GroupId: string;
        ExpenseId: string;
        RecurringId: string;
        SettlementId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created; session cookie set */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in; session cookie set */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted; session cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    setAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAvatarRequest"];
            };
        };
        responses: {
            /** @description Avatar saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avatar cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUserAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    addGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listExpenses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpenseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpenseRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listExpenseRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseRevision"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listSettlements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"][];
                };
            };
        };
    };
    createSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSettlementRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SettlementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SettlementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listActivity: {
        parameters: {
            query?: {
                /** @description Max items to return. Defaults to 50. */
                limit?: number;
                /** @description Opaque cursor returned by a previous response; omit for the first page. */
                cursor?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listRecurringExpenses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpense"][];
                };
            };
        };
    };
    createRecurringExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringExpenseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpense"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteRecurringExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RecurringId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
