/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness (pings DB) */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns whether first-run setup has been completed. */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/setup/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete first-run setup by creating the admin account.
         * @description Validates the setup token (logged to API stdout on every boot while
         *     the install ceremony is pending) and creates the very first user
         *     with role=admin. Idempotent: subsequent calls after success return
         *     410 Gone regardless of token.
         */
        post: operations["completeSetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description When SMTP is configured the new account starts unverified: the response
         *     body's `verification_required` is `true`, no session cookie is set, and
         *     a 6-digit verification code is emailed to the address. The user must
         *     POST it to `/v1/auth/verify` before they can log in. When SMTP is not
         *     configured the account is auto-verified immediately and the response
         *     sets a session cookie just like login.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify a pending registration with the 6-digit code */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resend the registration verification code
         * @description Always returns 204 regardless of whether the email matches a pending
         *     registration, to avoid account enumeration. Rate-limited per IP.
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin a password reset (sends a 6-digit code by email)
         * @description Always responds 204 to avoid account enumeration: the same response
         *     shape is returned whether the email is registered or not. When the
         *     email matches an active user a code is enqueued; otherwise nothing
         *     happens. Rate-limited per IP.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a password reset using the 6-digit code */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out (clears session) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user */
        get: operations["me"];
        put?: never;
        post?: never;
        /** Soft-delete the current user (tombstones display_name, scrubs email, clears all sessions) */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /** Rename the current user */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change the current user's password (requires old password) */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/email/change-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin a change-email flow (sends a code to the new address)
         * @description Step-up: the caller's current password must be supplied. The new email
         *     is held in a verification token and only persisted to `users.email`
         *     when the user POSTs the matching 6-digit code to
         *     `/v1/me/email/change-confirm`. The current address keeps working until
         *     confirm succeeds.
         */
        post: operations["changeEmailRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/email/change-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm a pending email change with the 6-digit code
         * @description On success the user's email is updated, all sessions for the user are
         *     revoked, and a fresh session cookie is issued so the current browser
         *     stays logged in.
         */
        post: operations["changeEmailConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user's notification preferences */
        get: operations["getMyNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update the current user's notification preferences */
        patch: operations["updateMyNotifications"];
        trace?: never;
    };
    "/v1/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload an 8x8 avatar PNG (base64-encoded, <= 1024 bytes) */
        put: operations["setAvatar"];
        post?: never;
        /** Remove the current user's avatar (falls back to initials on display) */
        delete: operations["deleteAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{id}/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve a user's pixelated avatar PNG (group-member access)
         * @description Returns the stored avatar PNG for the user. The source is an 8x8 bitmap
         *     uploaded by the client; the server upscales it with nearest-neighbour
         *     sampling before storage so it renders crisp at any CSS size. Callers
         *     must share at least one group with the target user. Browsers should
         *     cache on `?v={avatar_updated_at}` to avoid stale renders when the owner
         *     updates.
         */
        get: operations["getUserAvatar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List groups the current user belongs to */
        get: operations["listGroups"];
        put?: never;
        /** Create a group */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a group (creator only; cascades) */
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        /** Update a group (rename or change default currency) */
        patch: operations["updateGroup"];
        trace?: never;
    };
    "/v1/groups/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a member to a group (invitee must be registered) */
        post: operations["addGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a member (creator removes anyone; members may leave themselves)
         * @description The group creator can remove any non-creator member. Any member may
         *     remove themselves (leave). The creator cannot leave or be removed -
         *     ownership transfer or full group deletion is required first.
         *     The target's net balance for the group must be exactly zero (settle up
         *     first), so removing them never silently writes off debt. If the group
         *     ends up with fewer than 2 members, any pinned `default_split` is
         *     cleared automatically.
         */
        delete: operations["removeGroupMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group expenses (newest first) */
        get: operations["listExpenses"];
        put?: never;
        /** Create an expense */
        post: operations["createExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single expense (members only) */
        get: operations["getExpense"];
        put?: never;
        post?: never;
        /** Soft-delete an expense (any group member) */
        delete: operations["deleteExpense"];
        options?: never;
        head?: never;
        /**
         * Update description, amount, category, or payer (payer or group creator only)
         * @description Editable fields: `description`, `amount_cents`, `category_id`, `payer_id`.
         *     Splits are rescaled proportionally when `amount_cents` changes, preserving
         *     each member's relative share. A row is appended to `expense_revisions`
         *     for every change.
         */
        patch: operations["updateExpense"];
        trace?: never;
    };
    "/v1/expenses/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Full edit history of an expense (oldest first) */
        get: operations["listExpenseRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available expense categories (seeded) */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get net balances + simplified pairwise debts for a group */
        get: operations["getBalances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List settlements in a group */
        get: operations["listSettlements"];
        put?: never;
        /** Record a settlement (one member pays another) */
        post: operations["createSettlement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settlements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single settlement by id (member-only) */
        get: operations["getSettlement"];
        put?: never;
        post?: never;
        /** Soft-delete a settlement (any group member) */
        delete: operations["deleteSettlement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the merged activity feed for a group (newest first, paginated) */
        get: operations["listActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/groups/{id}/recurring-expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recurring expense templates for a group */
        get: operations["listRecurringExpenses"];
        put?: never;
        /** Create a recurring expense template */
        post: operations["createRecurringExpense"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recurring-expenses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a recurring template */
        delete: operations["deleteRecurringExpense"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users (admin) */
        get: operations["adminListUsers"];
        put?: never;
        /** Create a user on behalf (admin) */
        post: operations["adminCreateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single user (admin) */
        get: operations["adminGetUser"];
        put?: never;
        post?: never;
        /** Soft-delete a user (admin, step-up) */
        delete: operations["adminDeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send the user a password-reset email (admin, step-up)
         * @description Scrambles the target user's password hash, revokes every active
         *     session for them, and emails them a 6-digit code so they can set a
         *     new password through the standard /reset flow. The admin never types
         *     a temporary password.
         */
        post: operations["adminResetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Promote or demote a user (admin, step-up) */
        patch: operations["adminSetUserRole"];
        trace?: never;
    };
    "/v1/admin/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all groups across the instance (admin) */
        get: operations["adminListGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete any group (admin, step-up) */
        delete: operations["adminDeleteGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/smtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get SMTP configuration (admin) */
        get: operations["adminGetSmtpConfig"];
        /** Update SMTP configuration (admin) */
        put: operations["adminUpdateSmtpConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/smtp/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reveal the stored SMTP password (admin)
         * @description Decrypts and returns the SMTP password as cleartext. Admin-only and
         *     audit-logged as `admin_view_smtp_password`. The cleartext is never
         *     returned by `GET /v1/admin/smtp` - admins must use this dedicated
         *     endpoint, which makes the action explicit and reviewable.
         */
        get: operations["adminRevealSmtpPassword"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/smtp/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test the current SMTP configuration (admin) */
        post: operations["adminTestSmtpConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/smtp/send-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a real test email to the admin's own address (admin)
         * @description Sends a plain-text test email through the configured SMTP server to
         *     the calling admin's verified email address. Synchronous: the SMTP
         *     result is reflected directly in the response (no outbox round-trip),
         *     so failures surface immediately in the admin UI.
         */
        post: operations["adminSendSmtpTestEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List admin audit entries (admin) */
        get: operations["adminListAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** Format: date-time */
            created_at: string;
            /** @description True when the user has uploaded a pixel avatar. Fetch it at `/v1/users/{id}/avatar`. */
            has_avatar: boolean;
            /**
             * Format: date-time
             * @description Cache-buster for the avatar URL. Changes on every upload/delete.
             */
            avatar_updated_at?: string;
            /**
             * Format: date-time
             * @description Set when the account has been soft-deleted; `display_name` is then a tombstone.
             */
            deleted_at?: string;
            /**
             * @description First day of the week in calendar UIs. 0 = Sunday, 1 = Monday.
             * @enum {integer}
             */
            week_start: 0 | 1;
            /** @description IANA timezone (e.g. "Europe/Madrid"). Null means the client should use the device-detected zone. */
            timezone?: string | null;
            /** @description True when the user has the admin role. Read-only; promotion only happens via the bootstrap path or an admin endpoint. */
            readonly is_admin?: boolean;
            /**
             * Format: date-time
             * @description When the email address was confirmed. Null until the user verifies, or set automatically at registration when SMTP is unconfigured.
             */
            email_verified_at?: string | null;
        };
        UpdateMeRequest: {
            display_name?: string;
            /**
             * @description First day of the week. 0 = Sunday, 1 = Monday.
             * @enum {integer}
             */
            week_start?: 0 | 1;
            /** @description IANA timezone (e.g. "Europe/Madrid"). Send an empty string to revert to device detection. */
            timezone?: string;
        };
        ChangePasswordRequest: {
            old_password: string;
            new_password: string;
        };
        SetAvatarRequest: {
            /** @description Base64-encoded PNG. Decoded size must be <= 1024 bytes and the image exactly 8x8 pixels. */
            png_base64: string;
        };
        /**
         * @example {
         *       "email": "alice@example.com",
         *       "password": "correct-horse-battery-staple",
         *       "display_name": "Alice"
         *     }
         */
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        RegisterResponse: {
            user: components["schemas"]["User"];
            /** @description True when the user must POST a 6-digit code to `/v1/auth/verify` before logging in. False when SMTP is unconfigured and the account was auto-verified. */
            verification_required: boolean;
        };
        /**
         * @example {
         *       "email": "alice@example.com",
         *       "code": "482193"
         *     }
         */
        VerifyEmailRequest: {
            /** Format: email */
            email: string;
            /** @description 6-digit numeric code received by email. */
            code: string;
        };
        /**
         * @example {
         *       "email": "alice@example.com"
         *     }
         */
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        /**
         * @example {
         *       "email": "alice@example.com",
         *       "code": "482193",
         *       "new_password": "correct-horse-battery-staple"
         *     }
         */
        PasswordResetConfirm: {
            /** Format: email */
            email: string;
            /** @description 6-digit numeric code received by email. */
            code: string;
            new_password: string;
        };
        /**
         * @example {
         *       "email": "alice@example.com"
         *     }
         */
        ResendVerificationRequest: {
            /** Format: email */
            email: string;
        };
        /**
         * @example {
         *       "new_email": "alice.new@example.com",
         *       "password": "correct-horse-battery-staple"
         *     }
         */
        ChangeEmailRequest: {
            /** Format: email */
            new_email: string;
            /** @description The caller's current password (step-up). */
            password: string;
        };
        /**
         * @example {
         *       "code": "917544"
         *     }
         */
        ConfirmEmailChangeRequest: {
            /** @description 6-digit code received at the new address. */
            code: string;
        };
        /**
         * @description Per-user, per-event email opt-in flags. All default to false (off).
         *     The server only emails when the corresponding flag is true AND SMTP is
         *     configured.
         */
        NotificationPrefs: {
            /** @description Email me when a recurring expense is materialized in one of my groups. */
            notify_recurring_run?: boolean;
            /** @description Email me when a settlement is recorded in one of my groups. */
            notify_settlement?: boolean;
            /** @description Email me when I am added to a new group. */
            notify_group_added?: boolean;
        };
        SetupStatus: {
            /** @description True after the install ceremony has been completed; false while it is still pending. */
            locked: boolean;
        };
        SetupCompleteRequest: {
            token: string;
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Group: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description ISO-4217 code used when expenses omit currency */
            default_currency: string;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            members: components["schemas"]["GroupMember"][];
            /**
             * @description Optional 2-member percentage split that prefills the create-expense form.
             *     Automatically cleared by the server when the group grows past 2 members.
             */
            default_split?: components["schemas"]["DefaultSplitEntry"][];
        };
        DefaultSplitEntry: {
            /** Format: uuid */
            user_id: string;
            /** @description 0..10000; the two entries must sum to exactly 10000. */
            basis_points: number;
        };
        GroupMember: {
            /** Format: uuid */
            user_id: string;
            display_name: string;
            /** Format: date-time */
            joined_at: string;
            has_avatar: boolean;
            /** Format: date-time */
            avatar_updated_at?: string;
            /**
             * Format: date-time
             * @description Set when the user has soft-deleted their account; `display_name` is a tombstone.
             */
            deleted_at?: string;
        };
        /**
         * @example {
         *       "name": "Trip to Lisbon",
         *       "default_currency": "EUR"
         *     }
         */
        CreateGroupRequest: {
            name: string;
            /** @default EUR */
            default_currency: string;
        };
        UpdateGroupRequest: {
            name?: string;
            default_currency?: string;
            /**
             * @description Set the default 2-member split. Pass an empty array (or null) to clear it.
             *     Only valid when the group has exactly 2 members.
             */
            default_split?: components["schemas"]["DefaultSplitEntry"][] | null;
            /**
             * Format: uuid
             * @description Transfer group ownership to another member. Only the current owner
             *     may set this; the target must already be a member of the group.
             */
            created_by?: string;
        };
        AddMemberRequest: {
            /** Format: email */
            email: string;
        };
        /** @enum {string} */
        SplitMode: "equal" | "exact" | "percent" | "shares";
        SplitInput: {
            /** Format: uuid */
            user_id: string;
            /** Format: int64 */
            value?: number;
        };
        Split: {
            /** Format: uuid */
            user_id: string;
            /** Format: int64 */
            share_cents: number;
        };
        /**
         * @example {
         *       "description": "Hotel",
         *       "amount_cents": 20000,
         *       "payer_id": "7a1d5b9e-0c0a-4a12-9a55-0c55cf2b6fb1",
         *       "mode": "equal",
         *       "splits": [
         *         {
         *           "user_id": "7a1d5b9e-0c0a-4a12-9a55-0c55cf2b6fb1"
         *         },
         *         {
         *           "user_id": "9c0e3a31-6b2f-41d7-bf80-7a3f1b6d3d24"
         *         }
         *       ]
         *     }
         */
        CreateExpenseRequest: {
            description: string;
            /** Format: int64 */
            amount_cents: number;
            /** @description Defaults to group.default_currency if omitted */
            currency?: string;
            /** Format: uuid */
            payer_id: string;
            /** Format: date-time */
            incurred_at?: string;
            /**
             * Format: uuid
             * @description Defaults to the `other` category when omitted.
             */
            category_id?: string;
            mode: components["schemas"]["SplitMode"];
            splits: components["schemas"]["SplitInput"][];
        };
        UpdateExpenseRequest: {
            description?: string;
            /** Format: int64 */
            amount_cents?: number;
            /** Format: uuid */
            category_id?: string;
            /**
             * Format: uuid
             * @description New payer; must be a current group member.
             */
            payer_id?: string;
            /**
             * @description Must be supplied together with `splits`. When both are present, the server
             *     re-resolves per-user shares. When neither is present, existing splits are
             *     rescaled proportionally if `amount_cents` changes.
             */
            mode?: components["schemas"]["SplitMode"];
            /** @description Must be supplied together with `mode`. */
            splits?: components["schemas"]["SplitInput"][];
            /**
             * Format: date-time
             * @description When the expense was incurred (independent of when it was recorded).
             *     Defaults to the creation time if omitted on create, then immutable
             *     unless explicitly set here.
             */
            incurred_at?: string;
        };
        Expense: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            description: string;
            /** Format: int64 */
            amount_cents: number;
            currency: string;
            /** Format: uuid */
            payer_id: string;
            /**
             * Format: uuid
             * @description User who recorded the expense. Distinct from `payer_id` (who fronted
             *     the money) - any group member may create an expense on behalf of any
             *     other member, and the history attributes the action to this user.
             */
            created_by: string;
            /** Format: date-time */
            incurred_at: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            category_id: string;
            splits: components["schemas"]["Split"][];
        };
        Category: {
            /** Format: uuid */
            id: string;
            /** @description Stable machine identifier (e.g. `groceries`). The frontend maps this to an icon. */
            slug: string;
            /** @description Human-readable name. */
            label: string;
            /** @description Section header for the picker (e.g. `Entertainment`, `No category`). */
            group_label: string;
        };
        ExpenseRevision: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            expense_id: string;
            /** Format: uuid */
            edited_by: string;
            /** Format: date-time */
            edited_at: string;
            /**
             * @description Which field was changed.
             * @enum {string}
             */
            field: "description" | "amount_cents" | "category_id" | "payer_id";
            /** @description Previous value, stringified. */
            old_value: string;
            /** @description New value, stringified. */
            new_value: string;
        };
        Balance: {
            /** Format: uuid */
            user_id: string;
            display_name: string;
            /**
             * Format: int64
             * @description positive = owed to user; negative = user owes
             */
            net_cents: number;
        };
        SimplifiedDebt: {
            /** Format: uuid */
            from_user_id: string;
            /** Format: uuid */
            to_user_id: string;
            /** Format: int64 */
            amount_cents: number;
        };
        BalancesResponse: {
            net: components["schemas"]["Balance"][];
            simplified: components["schemas"]["SimplifiedDebt"][];
        };
        CreateSettlementRequest: {
            /** Format: uuid */
            to_user_id: string;
            /** Format: int64 */
            amount_cents: number;
            note?: string;
            /** Format: date-time */
            settled_at?: string;
        };
        Settlement: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            /** Format: uuid */
            from_user_id: string;
            /** Format: uuid */
            to_user_id: string;
            /** Format: int64 */
            amount_cents: number;
            note?: string;
            /** Format: date-time */
            settled_at: string;
            /** Format: date-time */
            created_at: string;
        };
        ActivityItem: {
            /** @enum {string} */
            kind: "expense" | "settlement";
            /** Format: date-time */
            occurred_at: string;
            /** @description When kind=expense and the expense matches a recurring template by content, the template's cadence. Omitted otherwise. */
            cadence?: components["schemas"]["Cadence"];
            /** @description Present iff kind=expense. */
            expense?: components["schemas"]["Expense"];
            /** @description Present iff kind=settlement. */
            settlement?: components["schemas"]["Settlement"];
        };
        ActivityPage: {
            items: components["schemas"]["ActivityItem"][];
            /** @description Pass to the next request as `cursor`. Absent when there are no more items. */
            next_cursor?: string;
        };
        /** @enum {string} */
        Cadence: "daily" | "weekly" | "biweekly" | "monthly" | "yearly";
        CreateRecurringExpenseRequest: {
            description: string;
            /** Format: int64 */
            amount_cents: number;
            /** @description Defaults to group.default_currency if omitted */
            currency?: string;
            /** Format: uuid */
            payer_id: string;
            /**
             * Format: uuid
             * @description Defaults to the `other` category when omitted.
             */
            category_id?: string;
            mode: components["schemas"]["SplitMode"];
            splits: components["schemas"]["SplitInput"][];
            cadence: components["schemas"]["Cadence"];
            /** Format: date-time */
            next_run_at: string;
        };
        RecurringExpense: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            group_id: string;
            description: string;
            /** Format: int64 */
            amount_cents: number;
            currency: string;
            /** Format: uuid */
            payer_id: string;
            /** Format: uuid */
            category_id: string;
            mode: components["schemas"]["SplitMode"];
            splits: components["schemas"]["SplitInput"][];
            cadence: components["schemas"]["Cadence"];
            /** Format: date-time */
            next_run_at: string;
            /** Format: date-time */
            created_at: string;
        };
        StepUpRequest: {
            /** @description The admin's own password, re-entered for the destructive action. */
            password: string;
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            /**
             * Format: email
             * @description Decrypted email. Null for soft-deleted users (their encrypted email is scrambled at delete time).
             */
            email: string | null;
            display_name: string;
            /** @enum {string} */
            role: "user" | "admin";
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Set when the account is soft-deleted.
             */
            deleted_at?: string;
            has_avatar: boolean;
            /** @enum {integer} */
            week_start: 0 | 1;
        };
        AdminUserListResponse: {
            items: components["schemas"]["AdminUser"][];
            total: number;
            limit: number;
            offset: number;
        };
        /**
         * @example {
         *       "email": "alice@example.org",
         *       "display_name": "Alice",
         *       "role": "user"
         *     }
         */
        AdminUserCreateRequest: {
            /** Format: email */
            email: string;
            display_name: string;
            /**
             * @default user
             * @enum {string}
             */
            role: "user" | "admin";
        };
        AdminSetUserRoleRequest: {
            /** @enum {string} */
            role: "user" | "admin";
            /** @description The admin's own password (step-up). */
            password: string;
        };
        AdminGroup: {
            /** Format: uuid */
            id: string;
            name: string;
            default_currency: string;
            /** Format: uuid */
            created_by: string;
            /** Format: date-time */
            created_at: string;
            member_count: number;
            expense_count: number;
        };
        AdminGroupListResponse: {
            items: components["schemas"]["AdminGroup"][];
            total: number;
            limit: number;
            offset: number;
        };
        /** @enum {string} */
        SmtpTlsMode: "none" | "starttls" | "tls";
        SmtpConfig: {
            host: string;
            port: number;
            username?: string | null;
            /** Format: email */
            from_address: string;
            tls_mode: components["schemas"]["SmtpTlsMode"];
            /** @description True when an encrypted password is stored. The cleartext is never returned. */
            password_set: boolean;
            /** Format: date-time */
            updated_at?: string;
            /** Format: uuid */
            updated_by?: string | null;
        };
        SmtpConfigUpdateRequest: {
            host: string;
            port: number;
            username?: string | null;
            /** Format: email */
            from_address: string;
            tls_mode: components["schemas"]["SmtpTlsMode"];
            /** @description SMTP password. Pass null to leave the existing one untouched; pass empty string to clear it; pass a non-empty value to set a new one. */
            smtp_password?: string | null;
            /**
             * @description Required when tls_mode='none' and a username/password is provided.
             * @default false
             */
            allow_plaintext_credentials: boolean;
        };
        SmtpPasswordResponse: {
            /** @description Cleartext SMTP password. Empty string when no password is stored. */
            password: string;
        };
        SmtpTestResponse: {
            success: boolean;
            /** @description Short, non-sensitive error code on failure (e.g. "dial_timeout", "auth_failed", "tls_handshake_failed"). */
            error?: string;
        };
        AdminAuditEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actor_user_id: string;
            /** Format: uuid */
            target_user_id?: string | null;
            /** Format: uuid */
            target_group_id?: string | null;
            action: string;
            ip?: string | null;
            user_agent?: string | null;
            success: boolean;
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            created_at: string;
        };
        AdminAuditListResponse: {
            items: components["schemas"]["AdminAuditEntry"][];
            total: number;
            limit: number;
            offset: number;
        };
    };
    responses: {
        /** @description Invalid input (malformed JSON, failed validation, or unknown field). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid session cookie. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not permitted for this resource. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource does not exist (or is hidden by soft-delete). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request conflicts with existing state (e.g. duplicate email). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limited. Retry after the `Retry-After` header. */
        TooManyRequests: {
            headers: {
                /** @description Seconds until the client may retry. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Server is not ready (e.g. DB unreachable). */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Instance is in first-run setup mode; visit /setup. */
        SetupRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        GroupId: string;
        ExpenseId: string;
        RecurringId: string;
        SettlementId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    completeSetup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupCompleteRequest"];
            };
        };
        responses: {
            /** @description Admin created; session cookie set. */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid setup token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            409: components["responses"]["Conflict"];
            /** @description Setup already completed; the install ceremony is closed. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created. Session cookie is set only when `verification_required` is false. */
            201: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["SetupRequired"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Verified; session cookie set. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Verification code expired or already used. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description Accepted. A new code may have been sent. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Accepted. A code may have been emailed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Password rotated; session cookie set. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Verification code expired or already used. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in; session cookie set */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Account exists but the email address has not been verified yet. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account deleted; session cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    changeEmailRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeEmailRequest"];
            };
        };
        responses: {
            /** @description Code sent (if SMTP is configured); awaiting confirmation. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            /** @description Step-up rate-limited. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    changeEmailConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailChangeRequest"];
            };
        };
        responses: {
            /** @description Email updated; new session cookie set. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            /** @description Verification code expired or already used. */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    getMyNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPrefs"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMyNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NotificationPrefs"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPrefs"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    setAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAvatarRequest"];
            };
        };
        responses: {
            /** @description Avatar saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Avatar cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getUserAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    addGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMember"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Member removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listExpenses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpenseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpenseRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Expense"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listExpenseRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ExpenseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseRevision"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getBalances: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancesResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listSettlements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"][];
                };
            };
        };
    };
    createSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSettlementRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SettlementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settlement"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSettlement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SettlementId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listActivity: {
        parameters: {
            query?: {
                /** @description Max items to return. Defaults to 50. */
                limit?: number;
                /** @description Opaque cursor returned by a previous response; omit for the first page. */
                cursor?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listRecurringExpenses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpense"][];
                };
            };
        };
    };
    createRecurringExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRecurringExpenseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringExpense"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    deleteRecurringExpense: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RecurringId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                include_deleted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminCreateUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    adminGetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminDeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepUpRequest"];
            };
        };
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description Step-up rate-limited; retry after the cooldown. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    adminResetUserPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepUpRequest"];
            };
        };
        responses: {
            /** @description Password reset email queued; target's sessions revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Step-up rate-limited. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    adminSetUserRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminSetUserRoleRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description Step-up rate-limited. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    adminListGroups: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGroupListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminDeleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepUpRequest"];
            };
        };
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Step-up rate-limited. */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    adminGetSmtpConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmtpConfig"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminUpdateSmtpConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmtpConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmtpConfig"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminRevealSmtpPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmtpPasswordResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description SMTP is not configured, or no password is stored. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    adminTestSmtpConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result of the connection test. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmtpTestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminSendSmtpTestEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Result of the send attempt. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmtpTestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminListAuditLog: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                action?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
