// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for Cadence.
const (
	Daily   Cadence = "daily"
	Monthly Cadence = "monthly"
	Weekly  Cadence = "weekly"
)

// Valid indicates whether the value is a known member of the Cadence enum.
func (e Cadence) Valid() bool {
	switch e {
	case Daily:
		return true
	case Monthly:
		return true
	case Weekly:
		return true
	default:
		return false
	}
}

// Defines values for ExpenseRevisionField.
const (
	AmountCents ExpenseRevisionField = "amount_cents"
	CategoryId  ExpenseRevisionField = "category_id"
	Description ExpenseRevisionField = "description"
	PayerId     ExpenseRevisionField = "payer_id"
)

// Valid indicates whether the value is a known member of the ExpenseRevisionField enum.
func (e ExpenseRevisionField) Valid() bool {
	switch e {
	case AmountCents:
		return true
	case CategoryId:
		return true
	case Description:
		return true
	case PayerId:
		return true
	default:
		return false
	}
}

// Defines values for SplitMode.
const (
	Equal   SplitMode = "equal"
	Exact   SplitMode = "exact"
	Percent SplitMode = "percent"
	Shares  SplitMode = "shares"
)

// Valid indicates whether the value is a known member of the SplitMode enum.
func (e SplitMode) Valid() bool {
	switch e {
	case Equal:
		return true
	case Exact:
		return true
	case Percent:
		return true
	case Shares:
		return true
	default:
		return false
	}
}

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	Email openapi_types.Email `json:"email"`
}

// Balance defines model for Balance.
type Balance struct {
	DisplayName string `json:"display_name"`

	// NetCents positive = owed to user; negative = user owes
	NetCents int64              `json:"net_cents"`
	UserId   openapi_types.UUID `json:"user_id"`
}

// BalancesResponse defines model for BalancesResponse.
type BalancesResponse struct {
	Net        []Balance        `json:"net"`
	Simplified []SimplifiedDebt `json:"simplified"`
}

// Cadence defines model for Cadence.
type Cadence string

// Category defines model for Category.
type Category struct {
	// Emoji Single emoji used as visual summary.
	Emoji string             `json:"emoji"`
	Id    openapi_types.UUID `json:"id"`

	// Label Human-readable name.
	Label string `json:"label"`

	// Slug Stable machine identifier (e.g. `groceries`).
	Slug string `json:"slug"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// CreateExpenseRequest defines model for CreateExpenseRequest.
type CreateExpenseRequest struct {
	AmountCents int64 `json:"amount_cents"`

	// CategoryId Defaults to the `other` category when omitted.
	CategoryId *openapi_types.UUID `json:"category_id,omitempty"`

	// Currency Defaults to group.default_currency if omitted
	Currency    *string            `json:"currency,omitempty"`
	Description string             `json:"description"`
	IncurredAt  *time.Time         `json:"incurred_at,omitempty"`
	Mode        SplitMode          `json:"mode"`
	PayerId     openapi_types.UUID `json:"payer_id"`
	Splits      []SplitInput       `json:"splits"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	DefaultCurrency *string `json:"default_currency,omitempty"`
	Name            string  `json:"name"`
}

// CreateRecurringExpenseRequest defines model for CreateRecurringExpenseRequest.
type CreateRecurringExpenseRequest struct {
	AmountCents int64   `json:"amount_cents"`
	Cadence     Cadence `json:"cadence"`

	// CategoryId Defaults to the `other` category when omitted.
	CategoryId *openapi_types.UUID `json:"category_id,omitempty"`

	// Currency Defaults to group.default_currency if omitted
	Currency    *string            `json:"currency,omitempty"`
	Description string             `json:"description"`
	Mode        SplitMode          `json:"mode"`
	NextRunAt   time.Time          `json:"next_run_at"`
	PayerId     openapi_types.UUID `json:"payer_id"`
	Splits      []SplitInput       `json:"splits"`
}

// CreateSettlementRequest defines model for CreateSettlementRequest.
type CreateSettlementRequest struct {
	AmountCents int64              `json:"amount_cents"`
	Note        *string            `json:"note,omitempty"`
	SettledAt   *time.Time         `json:"settled_at,omitempty"`
	ToUserId    openapi_types.UUID `json:"to_user_id"`
}

// DefaultSplitEntry defines model for DefaultSplitEntry.
type DefaultSplitEntry struct {
	// BasisPoints 0..10000; the two entries must sum to exactly 10000.
	BasisPoints int                `json:"basis_points"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Expense defines model for Expense.
type Expense struct {
	AmountCents int64              `json:"amount_cents"`
	CategoryId  openapi_types.UUID `json:"category_id"`
	CreatedAt   time.Time          `json:"created_at"`
	Currency    string             `json:"currency"`
	Description string             `json:"description"`
	GroupId     openapi_types.UUID `json:"group_id"`
	Id          openapi_types.UUID `json:"id"`
	IncurredAt  time.Time          `json:"incurred_at"`
	PayerId     openapi_types.UUID `json:"payer_id"`
	Splits      []Split            `json:"splits"`
}

// ExpenseRevision defines model for ExpenseRevision.
type ExpenseRevision struct {
	EditedAt  time.Time          `json:"edited_at"`
	EditedBy  openapi_types.UUID `json:"edited_by"`
	ExpenseId openapi_types.UUID `json:"expense_id"`

	// Field Which field was changed.
	Field ExpenseRevisionField `json:"field"`
	Id    openapi_types.UUID   `json:"id"`

	// NewValue New value, stringified.
	NewValue string `json:"new_value"`

	// OldValue Previous value, stringified.
	OldValue string `json:"old_value"`
}

// ExpenseRevisionField Which field was changed.
type ExpenseRevisionField string

// Group defines model for Group.
type Group struct {
	CreatedAt time.Time          `json:"created_at"`
	CreatedBy openapi_types.UUID `json:"created_by"`

	// DefaultCurrency ISO-4217 code used when expenses omit currency
	DefaultCurrency string `json:"default_currency"`

	// DefaultSplit Optional 2-member percentage split that prefills the create-expense form.
	// Automatically cleared by the server when the group grows past 2 members.
	DefaultSplit *[]DefaultSplitEntry `json:"default_split,omitempty"`
	Id           openapi_types.UUID   `json:"id"`
	Members      []GroupMember        `json:"members"`
	Name         string               `json:"name"`
}

// GroupMember defines model for GroupMember.
type GroupMember struct {
	AvatarUpdatedAt *time.Time `json:"avatar_updated_at,omitempty"`

	// DeletedAt Set when the user has soft-deleted their account; `display_name` is a tombstone.
	DeletedAt   *time.Time         `json:"deleted_at,omitempty"`
	DisplayName string             `json:"display_name"`
	HasAvatar   bool               `json:"has_avatar"`
	JoinedAt    time.Time          `json:"joined_at"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RecurringExpense defines model for RecurringExpense.
type RecurringExpense struct {
	AmountCents int64              `json:"amount_cents"`
	Cadence     Cadence            `json:"cadence"`
	CategoryId  openapi_types.UUID `json:"category_id"`
	CreatedAt   time.Time          `json:"created_at"`
	Currency    string             `json:"currency"`
	Description string             `json:"description"`
	GroupId     openapi_types.UUID `json:"group_id"`
	Id          openapi_types.UUID `json:"id"`
	Mode        SplitMode          `json:"mode"`
	NextRunAt   time.Time          `json:"next_run_at"`
	PayerId     openapi_types.UUID `json:"payer_id"`
	Splits      []SplitInput       `json:"splits"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// SetAvatarRequest defines model for SetAvatarRequest.
type SetAvatarRequest struct {
	// PngBase64 Base64-encoded PNG. Decoded size must be <= 1024 bytes and the image exactly 8x8 pixels.
	PngBase64 string `json:"png_base64"`
}

// Settlement defines model for Settlement.
type Settlement struct {
	AmountCents int64              `json:"amount_cents"`
	CreatedAt   time.Time          `json:"created_at"`
	FromUserId  openapi_types.UUID `json:"from_user_id"`
	GroupId     openapi_types.UUID `json:"group_id"`
	Id          openapi_types.UUID `json:"id"`
	Note        *string            `json:"note,omitempty"`
	SettledAt   time.Time          `json:"settled_at"`
	ToUserId    openapi_types.UUID `json:"to_user_id"`
}

// SimplifiedDebt defines model for SimplifiedDebt.
type SimplifiedDebt struct {
	AmountCents int64              `json:"amount_cents"`
	FromUserId  openapi_types.UUID `json:"from_user_id"`
	ToUserId    openapi_types.UUID `json:"to_user_id"`
}

// Split defines model for Split.
type Split struct {
	ShareCents int64              `json:"share_cents"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// SplitInput defines model for SplitInput.
type SplitInput struct {
	UserId openapi_types.UUID `json:"user_id"`
	Value  *int64             `json:"value,omitempty"`
}

// SplitMode defines model for SplitMode.
type SplitMode string

// UpdateExpenseRequest defines model for UpdateExpenseRequest.
type UpdateExpenseRequest struct {
	AmountCents *int64              `json:"amount_cents,omitempty"`
	CategoryId  *openapi_types.UUID `json:"category_id,omitempty"`
	Description *string             `json:"description,omitempty"`

	// Mode Must be supplied together with `splits`. When both are present, the server
	// re-resolves per-user shares. When neither is present, existing splits are
	// rescaled proportionally if `amount_cents` changes.
	Mode *SplitMode `json:"mode,omitempty"`

	// PayerId New payer; must be a current group member.
	PayerId *openapi_types.UUID `json:"payer_id,omitempty"`

	// Splits Must be supplied together with `mode`.
	Splits *[]SplitInput `json:"splits,omitempty"`
}

// UpdateGroupRequest defines model for UpdateGroupRequest.
type UpdateGroupRequest struct {
	DefaultCurrency *string `json:"default_currency,omitempty"`

	// DefaultSplit Set the default 2-member split. Pass an empty array (or null) to clear it.
	// Only valid when the group has exactly 2 members.
	DefaultSplit *[]DefaultSplitEntry `json:"default_split,omitempty"`
	Name         *string              `json:"name,omitempty"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	DisplayName string `json:"display_name"`
}

// User defines model for User.
type User struct {
	// AvatarUpdatedAt Cache-buster for the avatar URL. Changes on every upload/delete.
	AvatarUpdatedAt *time.Time `json:"avatar_updated_at,omitempty"`
	CreatedAt       time.Time  `json:"created_at"`

	// DeletedAt Set when the account has been soft-deleted; `display_name` is then a tombstone.
	DeletedAt   *time.Time          `json:"deleted_at,omitempty"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`

	// HasAvatar True when the user has uploaded a pixel avatar. Fetch it at `/v1/users/{id}/avatar`.
	HasAvatar bool               `json:"has_avatar"`
	Id        openapi_types.UUID `json:"id"`
}

// ExpenseId defines model for ExpenseId.
type ExpenseId = openapi_types.UUID

// GroupId defines model for GroupId.
type GroupId = openapi_types.UUID

// RecurringId defines model for RecurringId.
type RecurringId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// UpdateExpenseJSONRequestBody defines body for UpdateExpense for application/json ContentType.
type UpdateExpenseJSONRequestBody = UpdateExpenseRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = UpdateGroupRequest

// CreateExpenseJSONRequestBody defines body for CreateExpense for application/json ContentType.
type CreateExpenseJSONRequestBody = CreateExpenseRequest

// AddGroupMemberJSONRequestBody defines body for AddGroupMember for application/json ContentType.
type AddGroupMemberJSONRequestBody = AddMemberRequest

// CreateRecurringExpenseJSONRequestBody defines body for CreateRecurringExpense for application/json ContentType.
type CreateRecurringExpenseJSONRequestBody = CreateRecurringExpenseRequest

// CreateSettlementJSONRequestBody defines body for CreateSettlement for application/json ContentType.
type CreateSettlementJSONRequestBody = CreateSettlementRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// SetAvatarJSONRequestBody defines body for SetAvatar for application/json ContentType.
type SetAvatarJSONRequestBody = SetAvatarRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7D1rc9u4dn/lDNuZa/dSD9vJPpzZaR07m01vXuNHbzvrjAURRyI2JMAFQDm6GX/tD+hP7C/p4EGKFCmJ",
	"ciwnd29nZzaWSAAH5/3AgT4HkUgzwZFrFRx/DjIiSYoapf304lOGXOEraj4wHhwHGdFxEAacpBgcB4wG",
	"YSDx95xJpMGxljmGgYpiTIkZMREyJTo4DvLcvqnnmRmltGR8GtzdhcFLKfJsd9OfY5RL82lXS9yZwSoT",
	"XKFF2HNCz/H3HJU2nyLBNXL7J8myhEVEM8EHvynBzXeLZf5Z4iQ4Dv5psCDGwD1VgxdSCumWoqgiyTIz",
	"SXAcvOIzkjAKjGe5hr2UJAZapPDvF+/ehjAhLEEK9h27bghCQs4/cnHLYcIwofv94C4MTgWfJCx6BIg9",
	"aiDyKyq4ZToG/MSUZnwKShONsIf9aR9o7pZHwJSwxIH6s5BjRiny3cN6kusYubYgUBjnGrjQkKFMmTbf",
	"TIQEHTMFEpXIZYQWwLdC/yxyTh8Dl25ZoAKVhc2iEfaEBKYgtmiC8RyUmOgexQQ1OiReoJyxCK84mRGW",
	"kHGCu4fWrIkWMAOpRELnns5nzyHnEkkUG0gchJdCvCF87tlFPQIyDZ8lLGUaaR/OUcs5kIlGQ2KEkf2i",
	"d2K+GEGMhKLsB2Hg/rLgVd4wH5c3HwlOFeRcs8TOGCUMuYaUzEGakWa2xRZSxlmap8HxQalwGNc4RQv7",
	"XRhccZLrWEj2N3wETnvDlDLSaRjLqxyFSjHBIRLiIzOcf1fAb7FxQukbTMcoK7qQUMrMhCR5L0WGUjOj",
	"MSckURgGWeWrz4EV+Jr2dd+0afiF6v7Vv/WhfE2Mf8NIG4Z6ThLCI8vn9aUoU1lC5jfOGnxeXiAMOOqb",
	"qDCOdbxkQjHNZgg/gbhFClpArlA+A45T4h+YL8xTFYSL3TCuv3sSNGkbBub1G0a7Gbfq1ouBYX1HVfjX",
	"4EWdexvWRBBHSz2mMVWbOKjA8l25EpGSzM1nxdIsYRPm+LXTbBflkDMc6+akSxgwgNbWadvvKaHo+QC5",
	"kbBfA0pYMg/C4Bbxo/0jFVzHybwyfsENp0TjVMh5E0+Yit9Yi+gzPk2MCRO/McMMFIiCGVM5SUDlaUqc",
	"7DcW6sQDYZCQMSbNVX/JU8J7RssanQqGFVpXUUk+bYFZ21EpiWLGERg1ZnDCUHqNPZpKEaFkqEb7/Y2c",
	"aQG3CxXghh5ZrQSKCZ/ie6LUrZD0fuqD4+1N5mew6pR8eo18quPg+PDpd6FRr8Xng2ELVkRCO4/ftPva",
	"XGEdtNb9SyQavdvddfv4iaSZs+IkFTkvNdbhcDgcLqvzX4S2REgFNWvj7zkxHzMy97on+J4c0KfjH7E3",
	"jIak94QcHPZ+JE+f9obR06fR5HD83WR8YIiaJcys8uvnhd7qNvYurA75MRriETk66H03Ppz0nhzQ73vj",
	"yQ/D3vfkaHIw/o4e0cMnwd2Hu2U61/f6ualf19nRMIi8LHt9W0fSGU5InmhllLp1AYSOjfEvBsFtjByE",
	"8wX7VeW+SlRNIII8mq9fa2rioT5139wUY4BNirXMthb8eFTjxqOWZWtL1XnZsMZaXg4Dxi0I9IboGoYp",
	"0djTzFqYxiDHWBuUu+GdN+bFuyrrdVB5Bdd1tSLm9VcmQrKgMf7KjTrYYE6qeAvrrFYB2G+2hGq1SNtA",
	"9x4CvcwKwXHw4up8Eb9eSpYZxnnN1FjwoCEkzfHld+VUWzFU4SlVBv0w3E4p2ilWo6oM2rdUgw+sHUpP",
	"YR17FQ7F/+uTTvpka9XA8ZO+kTnfSgH9cfTJgg/rqFgtPBeodYIpcv1VxIYLjW180US7hXM7w6LFzb0D",
	"pMrYJfS34dKLkCX2C66dw78FFsdEMXWTCdYaOA77/QPjmT2zqkDfCkCujT8Naa60iQuM6OInEulkDvbV",
	"vpNTj3nn1pWUGO4olKztog1NLmXQiIUiL+VN8UelyLTt2RIMkZOC4v3WtZ1xaK6+kYM3uoKbda8Vte2Y",
	"t6qvN2nVxnOrxrtC1/W1+/h2O1etG+N8u1SJj3C9Yi2RXtOx1Z3XiFnTuwuWWMN+5zhjylNtKSFA2bYs",
	"4oeM552wiw6CrsSwCf+mLvprzKLYVQPgliiIbABuXZAyQ7IWwxU8VZD84f58aWLkGUlybAL7Fm/BPgrB",
	"vW8zPa2pDRN4r5jlvcQZE7nqNlUb+1VQX6VaWCF6gfAqJNW9tfGUjRFa1Ol9tI0f05GX2qOEWrHp4l3v",
	"yeHB92BUs8tkWZfVo0JZfxIq8ralV+nWt+LXXPxd5uwuHPZSm1eGDKXhQDJFsGNAx0RDJnHCkkS5HLtF",
	"Qc8DCAYH/Wt+kmuREs0ikiRziBIkEimM53aIclUKuzHz2aoZ8/9bBRlRGg7Bra/610YWOqm1pi9xZ7Hj",
	"HcfDqhd52MycdpQaD1dnZWt5zSXp2/K1K/LhbcLgE80NFqox4ZKaLaBdKQUesqZxnxFN5E2e0a1FwpXA",
	"ijHLFRq9oLrN2cdEVStn1DxhEkgUGfX3DEbVPPsImAICWqRjpQXHWgC3HqhN9YeYqBu36crjsRAJEhvt",
	"/yYY3xIRD19kWABRA7iNuq/FlPEdl4WMHVqkb7vUjCoj2oBezkg8kNP5hRmGfww39Y+WMti1c1t3yLql",
	"E2qs0i4AU6Z093puNYFZ03DBScLs8l6YA2I+/5t/vx+JtCqLx0EkpMRI92IhFfbGRGuU857SxMzeTHYu",
	"adNtcpThGv1SqwA92aBvtis3bVJHS7q2jTgXqE+swr2fWs349GZMFH73pGkXn9vve8iN10fh/duXfThD",
	"90Gxv6FLWIwRrvPh8Cj6CQ6Gh09gPNeogHBrNIGlxksrshk/fPoBMvYJE9WvI/bg6XDLNHIF8BVo8Zmw",
	"h1HX91CmEynSLVJWu1GgRUruq6fglpVbDTvhmgxdDdSNumrp3MD2tF+f4dyapl+Css4oakVEEUzV969i",
	"IrHL9neVVqwCsBJuZy+302TbUKXMDWy1/xV7WrmLN955KVIpRbHdakOj5l0YWyBFteZNrmyws2UxLGW8",
	"+u3BbovnHRIMD1E2IknybmIPHHT0Bj80zrJ5e6XyLEuYPbQ1RR2boJ/pGEbOURr14a8mGhwLHQORCJlE",
	"hVyHlSzBNZfYk6hEMkMFGcqejRsdHf14jszOzdRihsVhV7uUmd5MpSKSIAVDJCEdVRNbpxtVKTXy+Tmb",
	"f1hyW5upMvv0WWmjiU/PaJ/XcEF4p2LjwuPdDp2GcKN+10zJNrW1hrw5KdmqzL5JRtqyYg+Z1rpAbRnK",
	"v7bIbtn3+/CeKONGAaaZnoPduz3ey/Mk2QctXPoKmO5f83c8mbuz3svpq5io0vvaTf7KwOOOEbvj86uS",
	"SVseGVhB4jf3PBDwJcHBcjF3k0t+pTonr+oscUqiGHvj3ARb/og5ghsHV+ev++AOyCkQHHCGcg55lghC",
	"By5N1T3xdB93tnMGzWfJLOuNEXktk9aWO9Nm5G4SaFtkjeq5tvr+LmWOLSlCh32kQFxU42nVh59RRzEw",
	"DUTDaDA7GJghavCZ0buBe2dUKTZUEnr39qyLbS3l5mp517XJORsSRLlken5hZL8o5oqPDE9yIxhNoteO",
	"gcNbkqIh54hqdePPiI8Mq2YJYRx+ubx8DxSzRMxNWGZDxGs+urn5RSjdq42xmB6dvnv3l1cvbi5enF6d",
	"v/jJKJeRV1zc5gbMqoujUJUJFhgjGfsLzt2xdvykUXKSnIlItZWFBM0jDSoSGdrolcgoZhojnUuzTC6T",
	"4DiItc7U8WAwZTrOx/1IpIPf8oQR3iMJkZHgAyp0jFaFD8aJGA9Swvjg+eurF+/PX7297KfUVV8noji6",
	"T1zvjd/GmbiM0fnu91kzaPZe2AJJWaghqeDTmgtgrIH5z7uYPePDGA/l5P2rUgctoAKSZXbAqeAz5GYR",
	"dXzNAf4FTpIEUsFx7kpr1rkB7zWCdWBgjwuYJIJotd9fDHp15t69unp1porvFw04hseYNYUiI7/nuNR/",
	"AHtrGC40swG0cplwr1zsg0IN47mTVJLreJCIKeMjD8pl3FjScPkFSfGCafzpNfk0ega3kmkE5NSdmACJ",
	"ydwsYUtTBo+nF+c/+xmLTqixoAzNq0YE681ZCvZGbebtGKx5GxX4u2Spx/T5z6dwdHT0I1xdnloK/QdK",
	"AzPjU0+g57liHJWqQJmwGULOKUq7+1EfnkskHw39va8J//vf/2OeHRboGA1iJImO/zayYjIa2H4e88mS",
	"eyKJ0jK3YlNZyEkUwtt3lzBzgCF14pywqEireyF48+qywf3CcKdrtRJyOvCD1MC8a9wFppO6/BgGDsLA",
	"L2YP3hz2h7Y6nCEnGQuOg6P+sH9kE246tkqh2Jv5e+qaHwzmLRO+osFx8It/vtT5dzgcthQu/1JTq8Hx",
	"rx/CwJ/7D46D12yGhhxGXZGpMqrcrR58MMM8XldCcu4edwUkDJ4Oj1Z5e+UUg5b2sHV7MEA4ntrLGJ8q",
	"OHu+v2o/NeGy/pFQLfuyNSLflolKPxd0/mBdTrX6013dkBoDc9eOzQdZ23qFLQ1Wr8V0ihQYf7asZZRt",
	"aqn0mV2g7p06u1dbttGXehcGT4YHm6ldayUzgw5/3DxouT9vLY+LKVhqFhxh1mvyg3DZnpUMYZ43SNOS",
	"sfa4NK9bqGpwiFzDng2aVIHp/fWQSV/4WA1bURrZEb8uV146sezBzlnWHTalD82ww828V+mwtkM6sGvZ",
	"4LwL/i4IBAQ43trIYCVL+ayZDwdbdfprpvTp4rUv1EadAvyyqa1ZnWzQ3dmRe2iWuiwypaE0L4VrCgv0",
	"wJ5CpEir0llBXonQwqm1cZVTBibGbKL1zH5flO/D2jUHK9KJi1cGi2sQ7j50UUJuNRrcWwl3sdOLXng7",
	"4snmEWVzep0aF4vg3GabPDX2bPoQhPSxgg0khQTBk3mVLgUNgg93YTtPv0S9E8w/nGUuwHtIjn9sMrqM",
	"AwHlW04LMvoYbz3dMqKjlgD/BWWuGdRFJMcwqjwfhUvJ6RBGlbqA+Vjkp03kcFHmu2FVuttF/a0J79Bl",
	"0OWM8ek1RxLFPnj9kw20XL+1Tb734QSkuLUBY5Yhp641e1Qc2pT+yK4aXXMTlbk0mlvGhSN17q2VX76Y",
	"gR/eQ2gtDz2yZ7tGfhx4Xh7uYd+/eblzG4TKrkNwLByW7V326hWnT++hVtuM3aBk47WuxNIxdfU1FXAn",
	"Z2T5XP0ufZJH19B5kgBSpiFmSgs5BzGpWVyRUFQaJkwqvZ4XLO+sJ/1L98pjEM0dXH9c99FhwJ309mVN",
	"m5UfYyL4VIEWFQR6dFlL1xrFVZp0dxTItbQBP3Is56m0Mph7PBVdo6ZbHYijaBvRajzf0dUvSLmdtiuu",
	"I/sjuvln3sP3dmevanieQURURCiq/RVSU/iHbb7RQ+B6V37R9gI33L3A/aP4RCWvSeQkReP0OD+7PPJQ",
	"HK3Y7yb3g7G/sGil5XuJurjU6CGl/+GYonHl0tf1aGpke4kaOGoosAx/hsWFSpARJm+ZMsQba2UrWk2l",
	"XRKolXylI9PBZ/2K9NvGU/3GPNQVjtKi/LvH8XaTk7neS7pvKLxrhd96d9Ij+1hrAuFH97K+kHkKv6yM",
	"TzoEJE7KK72I7Xx0Qmm1y+9bY6TG9YVfw1EvejNbbial9I/sO5xQCsQn90CLhRPB+IxpXPScFLW5eplg",
	"nfcgiz6+XidDtNz2961bpEabYkfT1LQZJaLK3ITGNEuIxlV2vxyx0Xw0oPw27ciqW6geWRc0afrwluUB",
	"jMQajlnBJC3iqcqOrfVyeVF579uWyEoP2r1lsYIVYLxF9Kpo2yR8FYC+TbFr3l/1yAJXJdnfvxN3jpGQ",
	"xp4umAT2BMfCvmZkroBwexvd/kqe8rKa4ua82xvsdEznxJ8QL8+El+dI3I0cD5FYrNa1G2nivfKsuYLq",
	"iekQVCTzsXK3zofgTwuRJClAVC1HhlYUvtuQsfvjZKeVfT4EHl/6NpUq/tpQsDZH6FGxqzTfG/zGzvQ9",
	"eopvSextvm0z1UrJHlQbH9YJuGs17ybkrm/lAUX6HFMxa+7rT6rokdmbkCRRMCbRRxM7MM40I4ltl/FS",
	"3iq9vte0vt+yr35HnNvo2+/EuqvxrMjsqzHcle2DAcJtg78nxvu3L2FvXLtCIGy5KWB/HVtWb1ZY4djU",
	"rgzfVfWu9V7y+xKsmKe4be1rVd5cLr5Fmgqsw57fnQKR0PLr1RRrRtgd63VfHBVWf+rnHuW7r1KJWwRN",
	"3YKlRg9ZJUxa/nUYnUvuyuNKC4m0KpRFU4+Zr++6W9xvybgmGyPCY6ZTkl3zssHNX5HmfrnkWfW6tDyz",
	"p7kUMO3afrnR90r3OLJpPBa5vOaKpFliNjrGiZAOJnt5mzCjJHKKUkEkmcqAaCB8DqcXF/aOkT6ckiRB",
	"qa65ux41JhLNSwkSpcE4sy5BZNe2N6oSOUXtd/dciluDNlCxyBN6zSMSxWgMwuhfZz99bvRk3o1s0mkm",
	"GAWlSYIldGX3n7jlKA1qzBjVdmbsJWrjGJTmY4mVH/53qDZHs/YalkHGp3WlV048ZtxwZ+tPXC1pr7cv",
	"neL+eznfatgUSKnb2CdM7I86Vc2UZaGi/5pEEapWu1Q/CF7vjvz1gyGDEwpH5+XWhIgkQHEGe2ci+ogS",
	"Ts0uFO7XWp2OB4PEvBkLpY9/GP4wtOrMA9KU8ylTWvrf97J9NfYfkeuwUOruYoJEiI951l9wnN3SXbg8",
	"ozs2ZLu1fB4/ZplTEsWJAaMlci16hFITuhlh9YiLCAdCKdh4UlUW81nZ5nJFatVJL5FjpiWRc3+rYyoo",
	"Ktiz12aEros9LO5+DP1dC/t9qER6tA8vKNMKtCTRR9tV03b0swJamQpuAndhD6G3nk93v+jyZ1BJPt3v",
	"wzkS2hM8mZv1ZgeV6SvH1psLGAbIDSvWqq4G9yvrrn14i0brOq1eWaisvDaXGf2nmYTCf42MyRGSKteU",
	"KCYTVVm4Mlk1/m/Od1kmg1OiUTKSGMkGxrUAiSRZVBu91TD+uGEBTuFWyI/u1gm/1MLONRcqGuQsSmTZ",
	"aZZJMTZEyHnZSLhfmdH3nN19uPu/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
