// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for ActivityItemKind.
const (
	ActivityItemKindExpense    ActivityItemKind = "expense"
	ActivityItemKindSettlement ActivityItemKind = "settlement"
)

// Valid indicates whether the value is a known member of the ActivityItemKind enum.
func (e ActivityItemKind) Valid() bool {
	switch e {
	case ActivityItemKindExpense:
		return true
	case ActivityItemKindSettlement:
		return true
	default:
		return false
	}
}

// Defines values for AdminSetUserRoleRequestRole.
const (
	AdminSetUserRoleRequestRoleAdmin AdminSetUserRoleRequestRole = "admin"
	AdminSetUserRoleRequestRoleUser  AdminSetUserRoleRequestRole = "user"
)

// Valid indicates whether the value is a known member of the AdminSetUserRoleRequestRole enum.
func (e AdminSetUserRoleRequestRole) Valid() bool {
	switch e {
	case AdminSetUserRoleRequestRoleAdmin:
		return true
	case AdminSetUserRoleRequestRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for AdminUserRole.
const (
	AdminUserRoleAdmin AdminUserRole = "admin"
	AdminUserRoleUser  AdminUserRole = "user"
)

// Valid indicates whether the value is a known member of the AdminUserRole enum.
func (e AdminUserRole) Valid() bool {
	switch e {
	case AdminUserRoleAdmin:
		return true
	case AdminUserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for AdminUserWeekStart.
const (
	AdminUserWeekStartN0 AdminUserWeekStart = 0
	AdminUserWeekStartN1 AdminUserWeekStart = 1
)

// Valid indicates whether the value is a known member of the AdminUserWeekStart enum.
func (e AdminUserWeekStart) Valid() bool {
	switch e {
	case AdminUserWeekStartN0:
		return true
	case AdminUserWeekStartN1:
		return true
	default:
		return false
	}
}

// Defines values for AdminUserCreateRequestRole.
const (
	AdminUserCreateRequestRoleAdmin AdminUserCreateRequestRole = "admin"
	AdminUserCreateRequestRoleUser  AdminUserCreateRequestRole = "user"
)

// Valid indicates whether the value is a known member of the AdminUserCreateRequestRole enum.
func (e AdminUserCreateRequestRole) Valid() bool {
	switch e {
	case AdminUserCreateRequestRoleAdmin:
		return true
	case AdminUserCreateRequestRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for Cadence.
const (
	Biweekly Cadence = "biweekly"
	Daily    Cadence = "daily"
	Monthly  Cadence = "monthly"
	Weekly   Cadence = "weekly"
	Yearly   Cadence = "yearly"
)

// Valid indicates whether the value is a known member of the Cadence enum.
func (e Cadence) Valid() bool {
	switch e {
	case Biweekly:
		return true
	case Daily:
		return true
	case Monthly:
		return true
	case Weekly:
		return true
	case Yearly:
		return true
	default:
		return false
	}
}

// Defines values for ExpenseRevisionField.
const (
	AmountCents ExpenseRevisionField = "amount_cents"
	CategoryId  ExpenseRevisionField = "category_id"
	Description ExpenseRevisionField = "description"
	IncurredAt  ExpenseRevisionField = "incurred_at"
	Notes       ExpenseRevisionField = "notes"
	PayerId     ExpenseRevisionField = "payer_id"
	Splits      ExpenseRevisionField = "splits"
)

// Valid indicates whether the value is a known member of the ExpenseRevisionField enum.
func (e ExpenseRevisionField) Valid() bool {
	switch e {
	case AmountCents:
		return true
	case CategoryId:
		return true
	case Description:
		return true
	case IncurredAt:
		return true
	case Notes:
		return true
	case PayerId:
		return true
	case Splits:
		return true
	default:
		return false
	}
}

// Defines values for SmtpTlsMode.
const (
	None     SmtpTlsMode = "none"
	Starttls SmtpTlsMode = "starttls"
	Tls      SmtpTlsMode = "tls"
)

// Valid indicates whether the value is a known member of the SmtpTlsMode enum.
func (e SmtpTlsMode) Valid() bool {
	switch e {
	case None:
		return true
	case Starttls:
		return true
	case Tls:
		return true
	default:
		return false
	}
}

// Defines values for SplitMode.
const (
	Equal   SplitMode = "equal"
	Exact   SplitMode = "exact"
	Percent SplitMode = "percent"
	Shares  SplitMode = "shares"
)

// Valid indicates whether the value is a known member of the SplitMode enum.
func (e SplitMode) Valid() bool {
	switch e {
	case Equal:
		return true
	case Exact:
		return true
	case Percent:
		return true
	case Shares:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMeRequestWeekStart.
const (
	UpdateMeRequestWeekStartN0 UpdateMeRequestWeekStart = 0
	UpdateMeRequestWeekStartN1 UpdateMeRequestWeekStart = 1
)

// Valid indicates whether the value is a known member of the UpdateMeRequestWeekStart enum.
func (e UpdateMeRequestWeekStart) Valid() bool {
	switch e {
	case UpdateMeRequestWeekStartN0:
		return true
	case UpdateMeRequestWeekStartN1:
		return true
	default:
		return false
	}
}

// Defines values for UserWeekStart.
const (
	N0 UserWeekStart = 0
	N1 UserWeekStart = 1
)

// Valid indicates whether the value is a known member of the UserWeekStart enum.
func (e UserWeekStart) Valid() bool {
	switch e {
	case N0:
		return true
	case N1:
		return true
	default:
		return false
	}
}

// ActivityItem defines model for ActivityItem.
type ActivityItem struct {
	// Cadence When kind=expense and the expense matches a recurring template by content, the template's cadence. Omitted otherwise.
	Cadence *Cadence `json:"cadence,omitempty"`

	// Expense Present iff kind=expense.
	Expense    *Expense         `json:"expense,omitempty"`
	Kind       ActivityItemKind `json:"kind"`
	OccurredAt time.Time        `json:"occurred_at"`

	// Settlement Present iff kind=settlement.
	Settlement *Settlement `json:"settlement,omitempty"`
}

// ActivityItemKind defines model for ActivityItem.Kind.
type ActivityItemKind string

// ActivityPage defines model for ActivityPage.
type ActivityPage struct {
	Items []ActivityItem `json:"items"`

	// NextCursor Pass to the next request as `cursor`. Absent when there are no more items.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AdminAuditEntry defines model for AdminAuditEntry.
type AdminAuditEntry struct {
	Action        string                  `json:"action"`
	ActorUserId   openapi_types.UUID      `json:"actor_user_id"`
	CreatedAt     time.Time               `json:"created_at"`
	Id            openapi_types.UUID      `json:"id"`
	Ip            *string                 `json:"ip,omitempty"`
	Metadata      *map[string]interface{} `json:"metadata,omitempty"`
	Success       bool                    `json:"success"`
	TargetGroupId *openapi_types.UUID     `json:"target_group_id,omitempty"`
	TargetUserId  *openapi_types.UUID     `json:"target_user_id,omitempty"`
	UserAgent     *string                 `json:"user_agent,omitempty"`
}

// AdminAuditListResponse defines model for AdminAuditListResponse.
type AdminAuditListResponse struct {
	Items  []AdminAuditEntry `json:"items"`
	Limit  int               `json:"limit"`
	Offset int               `json:"offset"`
	Total  int               `json:"total"`
}

// AdminGroup defines model for AdminGroup.
type AdminGroup struct {
	CreatedAt       time.Time          `json:"created_at"`
	CreatedBy       openapi_types.UUID `json:"created_by"`
	DefaultCurrency string             `json:"default_currency"`
	ExpenseCount    int                `json:"expense_count"`
	Id              openapi_types.UUID `json:"id"`
	MemberCount     int                `json:"member_count"`
	Name            string             `json:"name"`
}

// AdminGroupListResponse defines model for AdminGroupListResponse.
type AdminGroupListResponse struct {
	Items  []AdminGroup `json:"items"`
	Limit  int          `json:"limit"`
	Offset int          `json:"offset"`
	Total  int          `json:"total"`
}

// AdminSetUserRoleRequest defines model for AdminSetUserRoleRequest.
type AdminSetUserRoleRequest struct {
	// Password The admin's own password (step-up).
	Password string                      `json:"password"`
	Role     AdminSetUserRoleRequestRole `json:"role"`
}

// AdminSetUserRoleRequestRole defines model for AdminSetUserRoleRequest.Role.
type AdminSetUserRoleRequestRole string

// AdminUser defines model for AdminUser.
type AdminUser struct {
	CreatedAt time.Time `json:"created_at"`

	// DeletedAt Set when the account is soft-deleted.
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
	DisplayName string     `json:"display_name"`

	// Email Decrypted email. Null for soft-deleted users (their encrypted email is scrambled at delete time).
	Email     *openapi_types.Email `json:"email"`
	HasAvatar bool                 `json:"has_avatar"`
	Id        openapi_types.UUID   `json:"id"`
	Role      AdminUserRole        `json:"role"`
	WeekStart AdminUserWeekStart   `json:"week_start"`
}

// AdminUserRole defines model for AdminUser.Role.
type AdminUserRole string

// AdminUserWeekStart defines model for AdminUser.WeekStart.
type AdminUserWeekStart int

// AdminUserCreateRequest defines model for AdminUserCreateRequest.
type AdminUserCreateRequest struct {
	DisplayName string                      `json:"display_name"`
	Email       openapi_types.Email         `json:"email"`
	Role        *AdminUserCreateRequestRole `json:"role,omitempty"`
}

// AdminUserCreateRequestRole defines model for AdminUserCreateRequest.Role.
type AdminUserCreateRequestRole string

// AdminUserListResponse defines model for AdminUserListResponse.
type AdminUserListResponse struct {
	Items  []AdminUser `json:"items"`
	Limit  int         `json:"limit"`
	Offset int         `json:"offset"`
	Total  int         `json:"total"`
}

// Balance defines model for Balance.
type Balance struct {
	DisplayName string `json:"display_name"`

	// NetCents positive = owed to user; negative = user owes
	NetCents int64              `json:"net_cents"`
	UserId   openapi_types.UUID `json:"user_id"`
}

// BalancesResponse defines model for BalancesResponse.
type BalancesResponse struct {
	Net        []Balance        `json:"net"`
	Simplified []SimplifiedDebt `json:"simplified"`
}

// Cadence defines model for Cadence.
type Cadence string

// Category defines model for Category.
type Category struct {
	// GroupLabel Section header for the picker (e.g. `Entertainment`, `No category`).
	GroupLabel string             `json:"group_label"`
	Id         openapi_types.UUID `json:"id"`

	// Label Human-readable name.
	Label string `json:"label"`

	// Slug Stable machine identifier (e.g. `groceries`). The frontend maps this to an icon.
	Slug string `json:"slug"`
}

// ChangeEmailRequest defines model for ChangeEmailRequest.
type ChangeEmailRequest struct {
	NewEmail openapi_types.Email `json:"new_email"`

	// Password The caller's current password (step-up).
	Password string `json:"password"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// ConfirmEmailChangeRequest defines model for ConfirmEmailChangeRequest.
type ConfirmEmailChangeRequest struct {
	// Code 6-digit code received at the new address.
	Code string `json:"code"`
}

// CreateExpenseRequest defines model for CreateExpenseRequest.
type CreateExpenseRequest struct {
	AmountCents int64 `json:"amount_cents"`

	// CategoryId Defaults to the `other` category when omitted.
	CategoryId *openapi_types.UUID `json:"category_id,omitempty"`

	// Currency Defaults to group.default_currency if omitted
	Currency    *string    `json:"currency,omitempty"`
	Description string     `json:"description"`
	IncurredAt  *time.Time `json:"incurred_at,omitempty"`
	Mode        SplitMode  `json:"mode"`

	// Notes Optional free-form notes about the expense.
	Notes   *string            `json:"notes,omitempty"`
	PayerId openapi_types.UUID `json:"payer_id"`
	Splits  []SplitInput       `json:"splits"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	DefaultCurrency *string `json:"default_currency,omitempty"`
	Name            string  `json:"name"`
}

// CreateRecurringExpenseRequest defines model for CreateRecurringExpenseRequest.
type CreateRecurringExpenseRequest struct {
	AmountCents int64   `json:"amount_cents"`
	Cadence     Cadence `json:"cadence"`

	// CategoryId Defaults to the `other` category when omitted.
	CategoryId *openapi_types.UUID `json:"category_id,omitempty"`

	// Currency Defaults to group.default_currency if omitted
	Currency    *string            `json:"currency,omitempty"`
	Description string             `json:"description"`
	Mode        SplitMode          `json:"mode"`
	NextRunAt   time.Time          `json:"next_run_at"`
	PayerId     openapi_types.UUID `json:"payer_id"`
	Splits      []SplitInput       `json:"splits"`
}

// CreateSettlementRequest defines model for CreateSettlementRequest.
type CreateSettlementRequest struct {
	AmountCents int64 `json:"amount_cents"`

	// FromUserId Member who is paying. Optional, defaults to the authenticated user
	// when omitted. Must be a current group member, and must differ from
	// `to_user_id`.
	FromUserId *openapi_types.UUID `json:"from_user_id,omitempty"`
	Note       *string             `json:"note,omitempty"`
	SettledAt  *time.Time          `json:"settled_at,omitempty"`
	ToUserId   openapi_types.UUID  `json:"to_user_id"`
}

// DefaultSplitEntry defines model for DefaultSplitEntry.
type DefaultSplitEntry struct {
	// BasisPoints 0..10000; the two entries must sum to exactly 10000.
	BasisPoints int                `json:"basis_points"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Expense defines model for Expense.
type Expense struct {
	AmountCents int64              `json:"amount_cents"`
	CategoryId  openapi_types.UUID `json:"category_id"`
	CreatedAt   time.Time          `json:"created_at"`

	// CreatedBy User who recorded the expense. Distinct from `payer_id` (who fronted
	// the money) - any group member may create an expense on behalf of any
	// other member, and the history attributes the action to this user.
	CreatedBy   openapi_types.UUID `json:"created_by"`
	Currency    string             `json:"currency"`
	Description string             `json:"description"`
	GroupId     openapi_types.UUID `json:"group_id"`
	Id          openapi_types.UUID `json:"id"`
	IncurredAt  time.Time          `json:"incurred_at"`
	Notes       string             `json:"notes"`
	PayerId     openapi_types.UUID `json:"payer_id"`
	Splits      []Split            `json:"splits"`
}

// ExpenseRevision defines model for ExpenseRevision.
type ExpenseRevision struct {
	EditedAt  time.Time          `json:"edited_at"`
	EditedBy  openapi_types.UUID `json:"edited_by"`
	ExpenseId openapi_types.UUID `json:"expense_id"`

	// Field Which field was changed.
	Field ExpenseRevisionField `json:"field"`
	Id    openapi_types.UUID   `json:"id"`

	// NewValue New value, stringified.
	NewValue string `json:"new_value"`

	// OldValue Previous value, stringified.
	OldValue string `json:"old_value"`
}

// ExpenseRevisionField Which field was changed.
type ExpenseRevisionField string

// Group defines model for Group.
type Group struct {
	CreatedAt time.Time          `json:"created_at"`
	CreatedBy openapi_types.UUID `json:"created_by"`

	// DefaultCurrency ISO-4217 code used when expenses omit currency
	DefaultCurrency string `json:"default_currency"`

	// DefaultSplit Optional 2-member percentage split that prefills the create-expense form.
	// Automatically cleared by the server when the group grows past 2 members.
	DefaultSplit *[]DefaultSplitEntry `json:"default_split,omitempty"`
	Id           openapi_types.UUID   `json:"id"`
	Members      []GroupMember        `json:"members"`
	Name         string               `json:"name"`
}

// GroupMember defines model for GroupMember.
type GroupMember struct {
	AvatarUpdatedAt *time.Time `json:"avatar_updated_at,omitempty"`

	// DeletedAt Set when the user has soft-deleted their account; `display_name` is a tombstone.
	DeletedAt   *time.Time         `json:"deleted_at,omitempty"`
	DisplayName string             `json:"display_name"`
	HasAvatar   bool               `json:"has_avatar"`
	JoinedAt    time.Time          `json:"joined_at"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// ImportSplitwiseBalance defines model for ImportSplitwiseBalance.
type ImportSplitwiseBalance struct {
	// CsvName Member name as it appears in the CSV header.
	CsvName string `json:"csv_name"`

	// NetCents Net cents; positive = member is owed, negative = member owes.
	NetCents int64 `json:"net_cents"`
}

// ImportSplitwiseMember defines model for ImportSplitwiseMember.
type ImportSplitwiseMember struct {
	// CsvName Name as it appears in the CSV column header.
	CsvName string              `json:"csv_name"`
	Email   openapi_types.Email `json:"email"`
}

// ImportSplitwisePreviewRow defines model for ImportSplitwisePreviewRow.
type ImportSplitwisePreviewRow struct {
	AmountCents  int64     `json:"amount_cents"`
	CategorySlug string    `json:"category_slug"`
	Currency     string    `json:"currency"`
	Description  string    `json:"description"`
	IncurredAt   time.Time `json:"incurred_at"`
	PayerCsvName string    `json:"payer_csv_name"`
}

// ImportSplitwiseRequest defines model for ImportSplitwiseRequest.
type ImportSplitwiseRequest struct {
	// Csv Raw CSV text exactly as exported by Splitwise. Hard cap 256 KiB.
	Csv             string `json:"csv"`
	DefaultCurrency string `json:"default_currency"`

	// DryRun When true, parses the CSV and returns the preview without writing anything.
	DryRun    *bool  `json:"dry_run,omitempty"`
	GroupName string `json:"group_name"`

	// Members One entry per CSV user column, in column order. Must match the header exactly.
	Members []ImportSplitwiseMember `json:"members"`
}

// ImportSplitwiseResponse defines model for ImportSplitwiseResponse.
type ImportSplitwiseResponse struct {
	// Balances Projected net balance per member after the import, derived from the expenses AND settlements that will actually be created (sign convention matches /v1/groups/{id}/balances).
	Balances []ImportSplitwiseBalance `json:"balances"`

	// CsvCurrencies Distinct ISO currency codes seen in the CSV, in first-seen order.
	// DoTheSplit groups are single-currency, so a length > 1 means the
	// CSV mixes currencies and the imported values will be stored under
	// the chosen `default_currency` regardless of their original code.
	// UI clients should warn the user in that case.
	CsvCurrencies   []string `json:"csv_currencies"`
	DefaultCurrency string   `json:"default_currency"`

	// ExpenseCount Number of valid expenses parsed from the CSV.
	ExpenseCount int `json:"expense_count"`

	// GroupId Set only when the import was committed (`dry_run: false`).
	GroupId   *openapi_types.UUID         `json:"group_id,omitempty"`
	GroupName string                      `json:"group_name"`
	Members   []ImportSplitwiseMember     `json:"members"`
	Preview   []ImportSplitwisePreviewRow `json:"preview"`

	// SettlementCount Number of valid settlements parsed from the CSV (rows whose Splitwise category is "Payment").
	SettlementCount   int                                `json:"settlement_count"`
	SettlementPreview []ImportSplitwiseSettlementPreview `json:"settlement_preview"`

	// Skipped Raw CSV records (rejoined with commas) for rows that were skipped, capped at 50 entries. Useful for surfacing why an import didn't include certain rows.
	Skipped []string `json:"skipped"`

	// SkippedCount Number of rows skipped (malformed, structurally invalid, or the trailing "Total balance" row).
	SkippedCount int `json:"skipped_count"`
}

// ImportSplitwiseSettlementPreview defines model for ImportSplitwiseSettlementPreview.
type ImportSplitwiseSettlementPreview struct {
	AmountCents int64  `json:"amount_cents"`
	Currency    string `json:"currency"`

	// FromCsvName Member who paid (CSV column header).
	FromCsvName string    `json:"from_csv_name"`
	Note        string    `json:"note"`
	SettledAt   time.Time `json:"settled_at"`

	// ToCsvName Member who received the payment (CSV column header).
	ToCsvName string `json:"to_csv_name"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// NotificationPrefs Per-user, per-event email opt-in flags. All default to false (off).
// The server only emails when the corresponding flag is true AND SMTP is
// configured.
type NotificationPrefs struct {
	// NotifyGroupAdded Email me when I am added to a new group.
	NotifyGroupAdded *bool `json:"notify_group_added,omitempty"`

	// NotifyRecurringRun Email me when a recurring expense is materialized in one of my groups.
	NotifyRecurringRun *bool `json:"notify_recurring_run,omitempty"`

	// NotifySettlement Email me when a settlement is recorded in one of my groups.
	NotifySettlement *bool `json:"notify_settlement,omitempty"`
}

// PasswordResetConfirm defines model for PasswordResetConfirm.
type PasswordResetConfirm struct {
	// Code 6-digit numeric code received by email.
	Code        string              `json:"code"`
	Email       openapi_types.Email `json:"email"`
	NewPassword string              `json:"new_password"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// RecurringExpense defines model for RecurringExpense.
type RecurringExpense struct {
	AmountCents int64              `json:"amount_cents"`
	Cadence     Cadence            `json:"cadence"`
	CategoryId  openapi_types.UUID `json:"category_id"`
	CreatedAt   time.Time          `json:"created_at"`
	Currency    string             `json:"currency"`
	Description string             `json:"description"`
	GroupId     openapi_types.UUID `json:"group_id"`
	Id          openapi_types.UUID `json:"id"`
	Mode        SplitMode          `json:"mode"`
	NextRunAt   time.Time          `json:"next_run_at"`
	PayerId     openapi_types.UUID `json:"payer_id"`
	Splits      []SplitInput       `json:"splits"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	User User `json:"user"`

	// VerificationRequired True when the user must POST a 6-digit code to `/v1/auth/verify` before logging in. False when SMTP is unconfigured and the account was auto-verified.
	VerificationRequired bool `json:"verification_required"`
}

// ResendVerificationRequest defines model for ResendVerificationRequest.
type ResendVerificationRequest struct {
	Email openapi_types.Email `json:"email"`
}

// SearchGroupRef Group descriptor returned alongside search results so the client can
// render the "GroupA" section heading, payer/recipient avatars, and the
// per-group filter without a follow-up `/v1/groups` round-trip.
type SearchGroupRef struct {
	DefaultCurrency string             `json:"default_currency"`
	Id              openapi_types.UUID `json:"id"`
	Members         []GroupMember      `json:"members"`
	Name            string             `json:"name"`
}

// SearchResponse Flat list of matching expenses and settlements, newest first across
// all groups. The client groups them by `group_id` for display. The
// `groups` field is the set of groups the caller is a member of (or the
// subset they filtered to) and is what the per-group filter chip row
// is built from - it is *not* limited to groups that produced a hit.
// `available_category_ids` lists every distinct category present among
// the expenses that match `q` + `group_id` (independent of the active
// `category_id` filter), so the client can hide categories that have
// no hits in the current search from the category picker.
type SearchResponse struct {
	// AvailableCategoryIds Distinct expense categories matching `q` + `group_id`, ignoring
	// the active `category_id` filter. Empty when no expenses match.
	AvailableCategoryIds []openapi_types.UUID `json:"available_category_ids"`
	Groups               []SearchGroupRef     `json:"groups"`
	Items                []ActivityItem       `json:"items"`
	Query                string               `json:"query"`
}

// SetAvatarRequest defines model for SetAvatarRequest.
type SetAvatarRequest struct {
	// PngBase64 Base64-encoded PNG. Decoded size must be <= 1024 bytes and the image exactly 8x8 pixels.
	PngBase64 string `json:"png_base64"`
}

// Settlement defines model for Settlement.
type Settlement struct {
	AmountCents int64              `json:"amount_cents"`
	CreatedAt   time.Time          `json:"created_at"`
	FromUserId  openapi_types.UUID `json:"from_user_id"`
	GroupId     openapi_types.UUID `json:"group_id"`
	Id          openapi_types.UUID `json:"id"`
	Note        *string            `json:"note,omitempty"`
	SettledAt   time.Time          `json:"settled_at"`
	ToUserId    openapi_types.UUID `json:"to_user_id"`
}

// SetupCompleteRequest defines model for SetupCompleteRequest.
type SetupCompleteRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
	Token       string              `json:"token"`
}

// SetupStatus defines model for SetupStatus.
type SetupStatus struct {
	// Locked True after the install ceremony has been completed; false while it is still pending.
	Locked bool `json:"locked"`
}

// SimplifiedDebt defines model for SimplifiedDebt.
type SimplifiedDebt struct {
	AmountCents int64              `json:"amount_cents"`
	FromUserId  openapi_types.UUID `json:"from_user_id"`
	ToUserId    openapi_types.UUID `json:"to_user_id"`
}

// SmtpConfig defines model for SmtpConfig.
type SmtpConfig struct {
	FromAddress openapi_types.Email `json:"from_address"`
	Host        string              `json:"host"`

	// PasswordSet True when an encrypted password is stored. The cleartext is never returned.
	PasswordSet bool                `json:"password_set"`
	Port        int                 `json:"port"`
	TlsMode     SmtpTlsMode         `json:"tls_mode"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
	UpdatedBy   *openapi_types.UUID `json:"updated_by,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// SmtpConfigUpdateRequest defines model for SmtpConfigUpdateRequest.
type SmtpConfigUpdateRequest struct {
	// AllowPlaintextCredentials Required when tls_mode='none' and a username/password is provided.
	AllowPlaintextCredentials *bool               `json:"allow_plaintext_credentials,omitempty"`
	FromAddress               openapi_types.Email `json:"from_address"`
	Host                      string              `json:"host"`
	Port                      int                 `json:"port"`

	// SmtpPassword SMTP password. Pass null to leave the existing one untouched; pass empty string to clear it; pass a non-empty value to set a new one.
	SmtpPassword *string     `json:"smtp_password,omitempty"`
	TlsMode      SmtpTlsMode `json:"tls_mode"`
	Username     *string     `json:"username,omitempty"`
}

// SmtpPasswordResponse defines model for SmtpPasswordResponse.
type SmtpPasswordResponse struct {
	// Password Cleartext SMTP password. Empty string when no password is stored.
	Password string `json:"password"`
}

// SmtpTestResponse defines model for SmtpTestResponse.
type SmtpTestResponse struct {
	// Error Short, non-sensitive error code on failure (e.g. "dial_timeout", "auth_failed", "tls_handshake_failed").
	Error   *string `json:"error,omitempty"`
	Success bool    `json:"success"`
}

// SmtpTlsMode defines model for SmtpTlsMode.
type SmtpTlsMode string

// Split defines model for Split.
type Split struct {
	ShareCents int64              `json:"share_cents"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// SplitInput defines model for SplitInput.
type SplitInput struct {
	UserId openapi_types.UUID `json:"user_id"`
	Value  *int64             `json:"value,omitempty"`
}

// SplitMode defines model for SplitMode.
type SplitMode string

// StepUpRequest defines model for StepUpRequest.
type StepUpRequest struct {
	// Password The admin's own password, re-entered for the destructive action.
	Password string `json:"password"`
}

// UpdateExpenseRequest defines model for UpdateExpenseRequest.
type UpdateExpenseRequest struct {
	AmountCents *int64              `json:"amount_cents,omitempty"`
	CategoryId  *openapi_types.UUID `json:"category_id,omitempty"`
	Description *string             `json:"description,omitempty"`

	// IncurredAt When the expense was incurred (independent of when it was recorded).
	// Defaults to the creation time if omitted on create, then immutable
	// unless explicitly set here.
	IncurredAt *time.Time `json:"incurred_at,omitempty"`

	// Mode Must be supplied together with `splits`. When both are present, the server
	// re-resolves per-user shares. When neither is present, existing splits are
	// rescaled proportionally if `amount_cents` changes.
	Mode *SplitMode `json:"mode,omitempty"`

	// Notes Optional free-form notes about the expense.
	Notes *string `json:"notes,omitempty"`

	// PayerId New payer; must be a current group member.
	PayerId *openapi_types.UUID `json:"payer_id,omitempty"`

	// Splits Must be supplied together with `mode`.
	Splits *[]SplitInput `json:"splits,omitempty"`
}

// UpdateGroupRequest defines model for UpdateGroupRequest.
type UpdateGroupRequest struct {
	// CreatedBy Transfer group ownership to another member. Only the current owner
	// may set this; the target must already be a member of the group.
	CreatedBy       *openapi_types.UUID `json:"created_by,omitempty"`
	DefaultCurrency *string             `json:"default_currency,omitempty"`

	// DefaultSplit Set the default 2-member split. Pass an empty array (or null) to clear it.
	// Only valid when the group has exactly 2 members.
	DefaultSplit *[]DefaultSplitEntry `json:"default_split,omitempty"`
	Name         *string              `json:"name,omitempty"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	DisplayName *string `json:"display_name,omitempty"`

	// Timezone IANA timezone (e.g. "Europe/Madrid"). Send an empty string to revert to device detection.
	Timezone *string `json:"timezone,omitempty"`

	// WeekStart First day of the week. 0 = Sunday, 1 = Monday.
	WeekStart *UpdateMeRequestWeekStart `json:"week_start,omitempty"`
}

// UpdateMeRequestWeekStart First day of the week. 0 = Sunday, 1 = Monday.
type UpdateMeRequestWeekStart int

// UpdateSettlementRequest defines model for UpdateSettlementRequest.
type UpdateSettlementRequest struct {
	AmountCents *int64              `json:"amount_cents,omitempty"`
	FromUserId  *openapi_types.UUID `json:"from_user_id,omitempty"`
	Note        *string             `json:"note,omitempty"`
	SettledAt   *time.Time          `json:"settled_at,omitempty"`
	ToUserId    *openapi_types.UUID `json:"to_user_id,omitempty"`
}

// User defines model for User.
type User struct {
	// AvatarUpdatedAt Cache-buster for the avatar URL. Changes on every upload/delete.
	AvatarUpdatedAt *time.Time `json:"avatar_updated_at,omitempty"`
	CreatedAt       time.Time  `json:"created_at"`

	// DeletedAt Set when the account has been soft-deleted; `display_name` is then a tombstone.
	DeletedAt   *time.Time          `json:"deleted_at,omitempty"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`

	// EmailVerifiedAt When the email address was confirmed. Null until the user verifies, or set automatically at registration when SMTP is unconfigured.
	EmailVerifiedAt *time.Time `json:"email_verified_at,omitempty"`

	// HasAvatar True when the user has uploaded a pixel avatar. Fetch it at `/v1/users/{id}/avatar`.
	HasAvatar bool               `json:"has_avatar"`
	Id        openapi_types.UUID `json:"id"`

	// IsAdmin True when the user has the admin role. Read-only; promotion only happens via the bootstrap path or an admin endpoint.
	IsAdmin *bool `json:"is_admin,omitempty"`

	// Timezone IANA timezone (e.g. "Europe/Madrid"). Null means the client should use the device-detected zone.
	Timezone *string `json:"timezone,omitempty"`

	// WeekStart First day of the week in calendar UIs. 0 = Sunday, 1 = Monday.
	WeekStart UserWeekStart `json:"week_start"`
}

// UserWeekStart First day of the week in calendar UIs. 0 = Sunday, 1 = Monday.
type UserWeekStart int

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	// Code 6-digit numeric code received by email.
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
}

// ExpenseId defines model for ExpenseId.
type ExpenseId = openapi_types.UUID

// GroupId defines model for GroupId.
type GroupId = openapi_types.UUID

// RecurringId defines model for RecurringId.
type RecurringId = openapi_types.UUID

// SettlementId defines model for SettlementId.
type SettlementId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// SetupRequired defines model for SetupRequired.
type SetupRequired = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// AdminListAuditLogParams defines parameters for AdminListAuditLog.
type AdminListAuditLogParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Action *string `form:"action,omitempty" json:"action,omitempty"`
}

// AdminListGroupsParams defines parameters for AdminListGroups.
type AdminListGroupsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminListUsersParams defines parameters for AdminListUsers.
type AdminListUsersParams struct {
	Limit          *int  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset         *int  `form:"offset,omitempty" json:"offset,omitempty"`
	IncludeDeleted *bool `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// ListActivityParams defines parameters for ListActivity.
type ListActivityParams struct {
	// Limit Max items to return. Defaults to 50.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned by a previous response; omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	// Q Substring to match. Whitespace is trimmed.
	Q string `form:"q" json:"q"`

	// GroupId Repeat to filter to one or more groups. Omit to search all groups the caller belongs to.
	GroupId *[]openapi_types.UUID `form:"group_id,omitempty" json:"group_id,omitempty"`

	// CategoryId Narrow results to a single category. When set, settlements are
	// excluded from the response. Unknown id silently yields zero matches.
	CategoryId *openapi_types.UUID `form:"category_id,omitempty" json:"category_id,omitempty"`

	// Limit Max items returned. Defaults to 100.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// AdminDeleteGroupJSONRequestBody defines body for AdminDeleteGroup for application/json ContentType.
type AdminDeleteGroupJSONRequestBody = StepUpRequest

// AdminUpdateSmtpConfigJSONRequestBody defines body for AdminUpdateSmtpConfig for application/json ContentType.
type AdminUpdateSmtpConfigJSONRequestBody = SmtpConfigUpdateRequest

// AdminCreateUserJSONRequestBody defines body for AdminCreateUser for application/json ContentType.
type AdminCreateUserJSONRequestBody = AdminUserCreateRequest

// AdminDeleteUserJSONRequestBody defines body for AdminDeleteUser for application/json ContentType.
type AdminDeleteUserJSONRequestBody = StepUpRequest

// AdminResetUserPasswordJSONRequestBody defines body for AdminResetUserPassword for application/json ContentType.
type AdminResetUserPasswordJSONRequestBody = StepUpRequest

// AdminSetUserRoleJSONRequestBody defines body for AdminSetUserRole for application/json ContentType.
type AdminSetUserRoleJSONRequestBody = AdminSetUserRoleRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = PasswordResetConfirm

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody = ResendVerificationRequest

// UpdateExpenseJSONRequestBody defines body for UpdateExpense for application/json ContentType.
type UpdateExpenseJSONRequestBody = UpdateExpenseRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = UpdateGroupRequest

// CreateExpenseJSONRequestBody defines body for CreateExpense for application/json ContentType.
type CreateExpenseJSONRequestBody = CreateExpenseRequest

// AddGroupMemberJSONRequestBody defines body for AddGroupMember for application/json ContentType.
type AddGroupMemberJSONRequestBody = AddMemberRequest

// CreateRecurringExpenseJSONRequestBody defines body for CreateRecurringExpense for application/json ContentType.
type CreateRecurringExpenseJSONRequestBody = CreateRecurringExpenseRequest

// CreateSettlementJSONRequestBody defines body for CreateSettlement for application/json ContentType.
type CreateSettlementJSONRequestBody = CreateSettlementRequest

// ImportSplitwiseJSONRequestBody defines body for ImportSplitwise for application/json ContentType.
type ImportSplitwiseJSONRequestBody = ImportSplitwiseRequest

// DeleteMeJSONRequestBody defines body for DeleteMe for application/json ContentType.
type DeleteMeJSONRequestBody = StepUpRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// SetAvatarJSONRequestBody defines body for SetAvatar for application/json ContentType.
type SetAvatarJSONRequestBody = SetAvatarRequest

// ChangeEmailConfirmJSONRequestBody defines body for ChangeEmailConfirm for application/json ContentType.
type ChangeEmailConfirmJSONRequestBody = ConfirmEmailChangeRequest

// ChangeEmailRequestJSONRequestBody defines body for ChangeEmailRequest for application/json ContentType.
type ChangeEmailRequestJSONRequestBody = ChangeEmailRequest

// UpdateMyNotificationsJSONRequestBody defines body for UpdateMyNotifications for application/json ContentType.
type UpdateMyNotificationsJSONRequestBody = NotificationPrefs

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// UpdateSettlementJSONRequestBody defines body for UpdateSettlement for application/json ContentType.
type UpdateSettlementJSONRequestBody = UpdateSettlementRequest

// CompleteSetupJSONRequestBody defines body for CompleteSetup for application/json ContentType.
type CompleteSetupJSONRequestBody = SetupCompleteRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L3rchu30ij6Kl08X5Wl7xtSF19WIlfqHFt2snyW7bgkO+ucCrNFcKZJYnkGmAAY0UzKf/cD7EfcT7IL",
	"DWBuHN4kUbbzrVpVKxZnBpdGd6Pv/WcvllkuBQqje2d/9nKmWIYGFf318lOOQuOrxP7BRe+slzMz60U9",
	"wTLsnfV40ot6Cn8vuMKkd2ZUgVFPxzPMmP1iIlXGTO+sVxT0plnk9ittFBfT3ufPUe8nJYt8f8NfYFwo",
	"+9f+prhEY1LMUJh9zfHZfqxzKTTSoTxnyQX+XqA29q9YCoOC/snyPOUxM1yKo39pKexv1TT/oXDSO+v9",
	"X0fVgR+5p/ropVJSuakS1LHiuR2kd9Z7Ja5ZyhPgIi8MHGQstavFBP7fy5/fRjBhPMUE6B2aNwKpoBAf",
	"hZwLmHBMk8NB73PUO5dikvL4HlbsQQOxn1HDnJsZ4CeuDRdT0IYZhAMcTAeQFG56BMwYT91Sf5RqzJME",
	"xf7X+qwwMxSGlpDAuDAgpIEcVcaN/WUiFZgZ16BQy0LFSAt8K82PshDJfcDSTQuJRE1rIzDCgVTANcwI",
	"TDBegJYT008wRYMOiJeornmMHwS7Zjxl4xT3v1o7J9LC7EoVsmThz/nFcyiEQhbP7ErCCk2RX5REuX9C",
	"0oaJGO3yuCUNpU1fFQK0XQdkMsGncM01N3BEP9Ei30v5homFx2l9DyduiSHlGTeYDOACjVoAmxi0eIgw",
	"oh/6z+wPI5ghS1ANelHP/YuWV3vD/tk+oViKREMhDE9pxDjlKAxkbAHKfmlHq7aQccGzIuudnZRckQuD",
	"U6S1f456HwQrzEwq/sd9nOEbrrVlIRb7PV/UqDWXAmIpP3JLnp/D+gkaz2LDr7lZvDKY0e2qZI7KcMfI",
	"Y5agiIkyWJr+POmd/bp+Zef+g8+/tZf2zxkK+MhF8gO6KxuYSAjC4e+MmXiGGhiocCmCwSxP7YmPF+BB",
	"F9FH4cEDDX6RA/jZMyVpZqjmXDtm5Ifffg9epOjYwzuF2iIDn0waW6F57A92EhQWH34t5416uryAe78t",
	"XZ5RT8Z2t5hcMdO4bBNmsG94hr2Oj2pjbr2xShDYZm/VDA5pKvHgV7fX5sqrncnxvzA2dpEBud6xKS4j",
	"FzeYNf+xbvENRP1cTsaUYgv7t8BP5ioulJYdZP2OaQ1GEubYF0H5O5hpGLmPRgN4NiYIzC2mWhRCYApB",
	"SMikQqBVDjolrDpo3GY6oZEkbzAbo6rJRixJuF0jS9/VYDNhqcaoBS4SABoI4n7ZtCD3VveCMi6eFQk3",
	"L4VRi+UTYrGD35/L+MdiI9VVoVFd8WQLGTHqxQqtELETlm85NM/ta6JI/T3u5Nel1zI0LGGGrQa8+3DF",
	"QBXgdBHHqHUNMGMpU2SCEJOpKZqrqdUbVsBm40r9GGvAu3EI+pZNPYPY8Hobh+0MzROOAjJUu28c6Xr8",
	"es21ufAawq0ZQQtrO3gBiQebrueoJycTjc33jrveM9KwdNNrnWwgfBuWVM65ElykbnZcxDcgnvDNeLEV",
	"ESU4YUVKPFShiOmjjH16jWJqZr2zh5Hdfu2vpQH8hXcVy0JsAdUtaTsjlrntoE6f/XMb/KZXO7bdAFwD",
	"x1uLae94/ZneOQk4TPlrYf8lmg8a1YVM8WaXZM60nkuVLIsA72cIzM7xQINV/cObcKAN5v0iP7R3ew3F",
	"TzqQUUmnJgYZz3JHyxrtuB2yXQsq9HVUrXElGCwM7oYHOI03fNPWdSpZB1hMSGyVv5qqnFiYbDkT13nK",
	"FlcrKDCq5JfmKl5grBa5FdvphQG8LdKU7Ar1dYCFtIYDM0OuAEXjG1p0rFg2TjEBZsB9BHaph40dBIlp",
	"4+05Y/qKXTPDVPclvyXz2hFfot4c8eOVNkyZ2mfH0clvm0nOLiDsr3EYUUC8Biur7bAx7VqkPKcRtiVN",
	"/MSy3AGgiR29ZymPsVzvWY/Zv/8f//5AqmlY9JkD2ec2nbexrXZRfXe8kYy3FqWrE/TXRFhQdEMW0HlA",
	"a0F+5/fGBw/Qv8a18ZylzFso1mPI0skKNFdxcCo0eVIuNTf8GuEHkHNMrOZoj/kpCJwy/8D+YJ/qOn/h",
	"wjx51OsCx/aaUgsmlQDeIupq/WvgolejjnCnuBXiBCh3oI3mWZ7yCXfmra1Guyw/eYFjszxoCwJ2oY15",
	"uvZ7XlmqAmUmjKcLz9zoH2Ne/jOTwszoXwtkKl10MuNzZnAquxRjp9ylbIxppw3R/stbH72JHCHn8UdU",
	"3t47eikMKsO4yFCYUQSjtxJiP9/ocHALZXjFqv5eZEz0FbLEXnxgkahzFp0W0449GfoqY/GMCwSeoDD2",
	"MMr9TJWMUXHUo8MBWFlroshcl0DGcu18BEYCE8BjKbYwo9i90VrCjqIG1DtxYMbEFF9aFnuDK0rg/Kpx",
	"Hw0Ezss7KZZZXXQ768VSKYxNfyaVxv6YGYNq0deG2eGW7qva4B23Tu32On38qONQ1ou1MUtTVA80OB3G",
	"3ES2XaK5sN4N8qqD+Tv/ys2EdjtZfYcNcDxpLvy4y4CaJlt/v2njjbGi5tI69y/FhKuMkM7B4gaoF8vE",
	"jvr9yd8eP3q0jDzucfvkn/QTPuUG7FNQGCO/dtKvM3LOgSWJQk0myxpEmvB4Yo/Xoq4d8X/8etz//rc/",
	"n3z+j43kSUvqhAdJiN6EfgNQsMyqIeFiPj0+Pj5uW6r/Lg2xg8xBDX8vmEPThb9ie39jJ8nj8ffYP46P",
	"Wf8ROzntf88eP+4fx48fx5PT8ZPJ+MSylzzldpZf/6yu5+2+/RzVP/k+PsaH7OFJ/8n4dNJ/dJL8rT+e",
	"fHfc/xt7ODkZP0keJqePep9/WzrX5l7/XBYj1kti4brwYkVbrSJ5tbR6j8gpMirvGKf5SecxaehIK+23",
	"NbvQ6rmIRw/aRhXgkzBXExs3W5UaUzVp+3izpM/FDXwrmae3tTKMxZ039kUrSkqDHWLkz7nDeJgoxL6d",
	"G+hNYGNZmLrvq0Wjp4T1HbfAYntze0DubWUy+/orkRdExRkXr9xXJxuEs/qOoyZG1xbsYVquajXnIKvW",
	"TRTMJetl7+WHiyrC5b3iucXP11yPpehQKDusn5XO54baCW9vopm2L+FVymFQw72XdEdue8dMqJS7t/IL",
	"/5ttbcO2dudA+MlcqULsxOf+OvykwsMmKFYTT+UL/yJkM1Eyq7v3WmEc5GaA+UwC15CzBRfTAYTrJIKk",
	"RSWsEaVlhx2KBqHAm0IbGCOwUkcgjAfn0IgoFiOz7yR8MrFKq5LZUIyMDIscDYZiG3KzF1wXwq8IYNjt",
	"Yq6Ws7sdpfZtC6+6kMTzBsLi0jm+A3qMmeb6Kpe80750PBicWMn2qQtlmUtAYazy7M5AF5k9WfzEYpMu",
	"gF71EoJHKScWrzfA3YHFqbGLLjC5QKRlT4VnXx3OPK19LMgW+kX1fufcVVzPjqS5UZTeSyxD0x3bRIgP",
	"2pO7wliqBBuBUQN4QZGhsSGyhFFggyM4sN84S0syFPabTApcHEIfmFg0aJwi2NwagIky6EoKGOOMpROQ",
	"E/vNUNCN22AMdtwZ18bev8wYxceFlWKd24hMXcSHuCbWsyWjqN/Lm27PpefrgituHERyE1WhlPzv/3Ld",
	"aDelqUpIReuv1pr7u3bLNjzhdQC1nEm1a7gipACdNcR7gddc+0NuRTslfFcC859sGe4QfPdbnhBFii8T",
	"7j9nPJ65MHKYMw0xmYBIMi3N0GvB3oBXDfIlRJtQb0N0ZywXOL+6ZmnRYVB6i3OgRxG498na3mkklmmy",
	"apR3Cq+5LPR2Q3U6MauTqR9qVMOJcB71ldT31oVyX1dkTSv2+vLn/qPTk785Y16hMXGKjgeFJkEOajS6",
	"oy7i5iecWmOmOO37qyJHZRGUTRHoGzAzZiBXOOFp6hi/A0E/XCMWBoOheFYYmTEriKbpAuIUmcIExgv6",
	"RLvo9zLkwN1OUyXnVsbVBk79raPdFbIVK1wW1D4TdLy6cVrXPU6XvVc7BSFtz6AJ15wU3xmreh9RSno1",
	"FfiVLUtOFA9wVeTJ/gJNyG86Y80wE3BxHT4I5SmM6r7OkVWCGBiZjbWRAu8wJmVTmMe/JBc7AuLuHb3V",
	"IhoL7jrdV1kulSOGOde40jke6+sSKJ2qp30ITAM3wPIcmaKcEHt+55e/1PIqdvGqv0UD9Ogp1BzsnuVw",
	"Ta72qO5i94/kHPVgGy97W4cIm9zkK29BraKOHRS+1RB9uxaUsUyLTNQguqdIltWwWR0f3oIL3ew4v5Dz",
	"u9W5gsd5rYpwG+Pb3Yj6Tjirn/N6EDflvqYYt1r4bkJladYtjukm/kd93TvrvWAGoxfVqqMQ/xCdS22i",
	"c7/IiIK3oudyPBSnx6eP+scn/eOT6FxOJojRCy4oAakw0aPB8XH08sNFdGr/0bf/T/f6SlN9ohZXqhAh",
	"KM+pLt5+/05JXb/bzn6t09yGgLJYZuSyq33wXI5rr4/luPnysrOOYPTnUjLanKjY4CdT2muYtnKbVMaJ",
	"PuXBDODvTCUQsxxOHz+Bf/DnbbfPk9OTR4/2EZpdQrbm1PBo0JGlReCHnCnttXy7RSYSUGgKJdxvueMG",
	"lLsqCwNzxSl7lYmFmXExrd0OtQu1fqa7Ru3VhLCWACuQDGgLK7jSYknIcKw1stzWc1mpLJN1xlDKNnOm",
	"DRen449vsK3k2X1rNKTPh+vFz2We3GtAqFPsWyfcLXGCVbFfYx8d1qW+STsaJiDQgH+P4Opv4yrXktNs",
	"ESSoKPSAjFM1u5WGZ29fQJVGpp0aMedpCiw2BekI46BKJHCg+dQelbhGQValkBB4dH1yRGDRR3/y5PNR",
	"WP3hTc+qFs629WFFxD38QfAu0JVWuleXP5e6Gml0GjSiqF37UZVhS08cYg7FC/l+hrRMpx1pykDTXExT",
	"7IchI9ASGKREKjAsjo8fIpxAhsyR5lBYEsj4JwwRQXa9pSXPHZvLiS9Qu/MYI2gjrbJWiASVsyXGM6lR",
	"wKiNhSNQOGUqSVFrkBMvvEvFp9yqkXbHg6H48MrnzmrQM1mQgUTVdACCBjMQM40thW8n3tY+prvPY2nJ",
	"c4WTSieuqECF7cQwa2RwfvnLoFPyqVsvlzUlKdJFpS6503K2JZn5BNeDkWfoZ0BcfHS4lSu0yXxvreTe",
	"ngHaO5ZukZvOWRNJG/M+6YhTLfnQtgdb51wdZwsHZLmYWyKpLvnKU801DHvv2MIOMOwddqNCbVW3BEXl",
	"0PRA2QyRjzzPMVkt1ThnhIYDhU4HdYUqLB4yfUiBrQQCx9bRcio3ZGSFnNxFoz0+Ds6tAXzQOCl8ckeh",
	"Jiy2AsN8tqCwUIfoCU/EAwNcxGmRIMQuSJbmaXD7Zewtt/r4eOVeNx89bci/XasmQnbMIjaFolvLJ9dT",
	"LRFy4SnGU7uZYe+9NCwNF+ewZwfsPPvW5b/ttd9mTx2I3d5tddJRdfFXpNeJhEu33RbixjIG3omaeFM2",
	"Ti72jYaO+UxCzngCB0vaeHcUdnBw35VDe6sVluGdJHk7nrLlitsxRXb5jcWu00abMGyutwsjXsspF3tO",
	"b29GQ2+XbrM2hPetNHziC3G8UzjRG1feEplR9a1EE1kxuY9WevV5aTI3fSvopWyqB/AsTUPkBhjpbm44",
	"kJPJ4WAo3lcGchIAaABdyQEUbm7F+cSyGTuivWCspkZS9uWb9++A66GIpZjwaaEwcTJVK9LabnXhc9NZ",
	"knRxfwplhgzd3K+AZUBvUvg+BRa7YKlO/c5PUBbwqLTO1VPU630EfwLXVvpHxVnK/8DECotSoGXQmXdr",
	"67ULaJbHWD979S5QISPvgd9yys8dGFWFw2s0PkL8BvHgj747Pfn+4VqrRitCfde0hPWR5aLIUPG4FWE+",
	"9sh5N3Hl60yYG9Mibpc4sIJX+NCTjZH/jUO+gdFtnalqa964AURblwJpx5LekYX3lrGh+4nD+doCT/5q",
	"wZ57D0ppxExsFwi6sVbJBU65NtvX5rlpbvMt88j2lfe8UwbanbDZWpLVxmTo6nBWGTQLXzFhHZaGxOdr",
	"VKW8d6Vq9fVamXVWtmq6rSk6893Pl++BQSP9ykgYHV2fHLHCzI5o/MUIxjiRCiGV06kVbbgYwI8k89Gg",
	"XmKDoiaylTa6UI1hzjSwwsi+W3MjhKYugbT9yL1Vu+yGrkaR/FJ7/1u/zS6RqXjmU0kmy0dLTyD8JpV3",
	"bNgDSKWYap5YYdyOAQo1RVprWa8GGDMxFApF4k3hQzfks2EPdC37l4tpBMS5jhTGPKdvnftel6GVQ2HV",
	"BhcMM+GpsSqf96kwmMg0lfN+kTv8cmLoCJQsRNI3iuddUv6tLaDfcFTMOveIQ4s6E2mixY8pM5BybUjo",
	"Zyae1VQSZ0Cv2QQjqwuhNs6ODyxWUuuhYGkatAXKg/YY4835ZoaZlaBH4QockTXMc0D6YihG4ZhdXCHX",
	"PnyK1lUN5PN+XXRMiJWYUOlTQitdjO03ZoYLj1ikxB3SRrjVLX2y6BL+xTOeg5LzoeAaxgVPfeRxHzjp",
	"SP8ppPnPUISzTJ/RIUxMJkVsaQlm3AyGYlRWWL2qXd16RKDWgNeoFhYCznlS2k9zX5CQZVJMnUOiPAqa",
	"yHnwRr+P4L/q8DzgIsHc0qYw3jtBYcrXFrK1BYz8bg+jZeKGmWUB/mUeJpwxO4aQdl9lEEfIp/D8orQQ",
	"V/ugvP8uOu2GyxrHUtCOawsr0bQNhwj4VEhLQg52DgTQBYEBvMxy450OQlZgpsFbvpmNXKFN1g43tpcl",
	"m7y7Y8C7rRv5e4FqsZntuNeiskSJ31W06hC7+Y95Rsz/hrWtxPRqzDQ+ebSMIs/p9z4KK44k8O7tTwN4",
	"ge4Pzf9AJ7qM0bkL4x/g5Pj0EYwXpuEYZFMsoxi++/Qd5PwTpu0E8pPHxzvmMdYWvgIsNVvN7bXOG+iE",
	"7XSsLV1pd6sH3rVl+caRiG0drQGdaE0mVcuuvEHlovrW59IKiuaGyavfoDpk4fcRxW3rVLhBohupUwT4",
	"S8NMoXeEdyrjjyt1pVpkiNDGykExKsykWFC87xhRQOyPO3nq7d/zGU/RixXa8DQFe3WviB9qwcCvpnOL",
	"zRJDu/OV3dI3N1+KtyDHrcmvExCZyckCPV0GAg3sq4Rs53mZSUeiK+nhytcGW6VKM1Er3leWqaGzlwqT",
	"IDIjUxRSxzUIKx+WClq30T+Xrl5emSD55PHjh483HaJJ9dVWtrfM5O9THaxvN4mOD990J4xsVcs3sLjd",
	"KvnOXNQkAShqHngNAK3zW49HH2gvN8yattrsVZ4yewyfzFWskCpJsVRvjk0MrRC8UcYv/ocHQgp8QFIM",
	"gwCpozpu5Upe82QV8tycCjZcLzfDSp2Z/Gp1vScyG4XHA6DC5hYlrBaWIrtGH4Hne4lIgVAII4t4Znmu",
	"/RCQhH23TvsZkRtw4x8zEFL03UsUImbfsYqkc/75BIzNJaxvSF17RvVVuF3z5qwwMa4+k/OSX7VO52Ud",
	"0kG76uB6G6+AtY4ogiCuqxKJIU27hUszit+0x61R+IwMetdZNaWg9jmFCt1ohr2Es/TKcjlZmGEvgmGP",
	"FWZ25brsuB8sqGdMJHrGPmL5pDuYYk0h9RYEwpsrAeBRqFb/z/IFK5IapoxJPRZ05k5ehsS4Jtj0jCnc",
	"RkbYV/59fQGdG6/8Lrvx4V1ElzLPc6f9r9jTyl20Dy9U9SJ11JK1S0kMQFlxjgbzD/l9VY6OQGEfhbOr",
	"hSqPCbpAMUtKLjl+19J7a2ndXb47FvzJuKj/erLfOmRbpMPeYUWvrvSFWk+ZOdMQvliyDBJH5s7LEsI+",
	"DgdD0S5CRHoslTngGdZqAlkG6XRc6kkjgGdZQYUyh6IQFB2Nn/KUx9ykC7pCZ6iwVR9hq0pkW/Z3qZzE",
	"S+1dQgEYXeR5yslqO0Wq9EAxnSPnPx0NgEA4lmZGoefeCBvVEniHQmFfoZbpNWqyHZNvzJGl/14gp7FJ",
	"+PIjVP3NaCo7vB1Kxyy1uoCS9uYmFE6p8NKojpYjn1lPqcFfpuLacrI8PX1amta6a+tsFZld+dt3OzWL",
	"H6OtsyB2qcm0gvPsVJ5tE99ZVxHlvWJCT1B5WMq5QKVnroYba9QoGcDPIl00bPH09lBkzFGdmXHtS+1Q",
	"XxV3Yix1Ddjo5Cr3SZmZvmUdk9vnZq3Pzr90LpwycrBM0qf3vQZg1WqSNekAyQVkhefDung/GAoClAtu",
	"b2XhzyhpzVl+95OGv0KYX/L+7VgvbwWevrmzy/F2JkbL2P+wcuhyyYdnb59BeFzK1y8LO/nRG5YoTlIz",
	"XKJVbMWS1qbwGhUFkiZ4zWOLIAYrgaMWmPdoY5+BlhuU/JkJWwRysC8P4Bh+gMtCJGwRwQn8AG+k/Xet",
	"0snKNgUrzmj3Emx7FmR2tup9VcXOlqGst67x0NJnWTzD/rjQpla+3H0HHy5eD8AVOtZW/nHe2yJPJUuO",
	"XDWH7esz3EtHk9L2XC840VViwrhw4H3UmdghuJ0eXIV4nw1SLkUyeyuHzxGjYGNMfB+Vqo8lCWl+WE2J",
	"K2TTaRRsYQYUhVopJ++uDFRaCZodG6tsjLiyh+eQiwIKyCHpUXEAP6KJZ1RXwbjwGGoS43JE3TujbpPf",
	"tn47feXaemy7UhM0RVAyxQFcIEv6UqSLp1a+zSQBlcL7Zyy3Yihcc0ZfjaU0Fuw55MzM7Okw4YdCkVAF",
	"vgG1aGaJvcRb4K13n7v1hUN4UyaThqAIn8JZaPTSiL1z+u7OwQT+2NYsuPPFQ+nbLEWRWO7zSt/mItq2",
	"X86NG+VQEN3iph0Itg/7/2sF8q8LxF+GMl2ncaG4WVxa6TMAQH7k+KywcyxfC40WuEAVWbiGUWL0le+P",
	"O7KXGTkm4O/v37+DBPNULlzyJxPJUIyurv4utek3viEWMDr/+ed/vHp5dfny/MPFyx8s4vtqqdRp3c1a",
	"VaKuDVBBkeX8H7hwLX3xkwU3S1/IuDtBPyliAzqWueuhy1Q845YOC2WnKZTFmZkxuT47OppyMyvGFmmO",
	"/lWknIk+S5mKpThKrBJFSsTROJXjo4xxcfT89YeX7y5evX0/yBJnbZnI0LaYuebofhtVqvqN5uwtN8em",
	"tPcq2i6TYtrQpK0+Yv/nrV99PWMkDD9796qUUmoJ9CzP6YPzsqCAPhsKgP+kRCyqkxlS4JlC8HzCVSiC",
	"AyFhkkpm9OGg+ujVC/fuhw+vXujwe1V71+IYJ2VM5uz3Alu9l+FgDcJFdjSATiyT7pXLQ7qyx4tarHEq",
	"p1yM/FJcDlljSovllyzDS27wh9fs0+gpFerA8lbRoDBd2CkoxM3C8fzy4kc/YmhVP5YJR/uqJcFm93wN",
	"B6MuBlelpvvF8cxD+uLHc3j48OH38OH9OZ3QL6jsmrmY+gN6XmguyHxWrjLl1+hqE9DuRwN4rpB9tOfv",
	"LUPwv//n/7LPTgM4RkczZKmZ/TEiMhkdkb5v/6LjnigWcnrr4HAUhfD25/dWXLILC7l0lg17/4ongjev",
	"3i9hv7TY6XrhSzU98h/pI/suXdAmbdKPRWAXsK1DeeDTwTGVWcxRsJz3znoPB8eDh+SnNTNiCmFv1I3I",
	"+dwt5AkJXyW9s97f/XPLW51fiL47PT7uMJv9o8FWe2e//hb1dJFlTC16Z73X/BqF96OxqSZnG43e+81+",
	"5uG6ciUX7vG2C4l6j48frrI3lEMcdfTvX7eHCwrHtjh1kHMx1fDi+eGq/VjisqLXESsSZ5Lp3Bd1U3vN",
	"tXEtbqUr16RYhiZUKKILIIQOepwJTc2qVu+l2/vxca3I82mjxHNXf/moewLfLa1zhuNNXpvuIavev+WQ",
	"7Tv8t+7zvZN+9ysaCXc0wHcI9Oj4ZDMCNTrz00dbYN2PUo15kqBzUNZJRBsvrxPSlAW9D+jHOqr5ToFN",
	"TKuCZNej2k8h7PRbR7S9o8ty092vDl3KTAGfPFDFzokYd8McUnrdAaTojFIdGPSCHrpCuN0oZO+X6oBJ",
	"R6pEc6fSVWewySb1m/sYtXkuk8WdHW/Ty/u5qT7YNX5ewq1HXd0/yBDkjvJ481E+Z2V3s/tCGfvFo81f",
	"vJXmR1kIN8XpwzuDsyvu30E1l66pHChmsO+zQAYtDL+sjG21UvQOpyMIbek2IbfOTL6eKf6EphbiuEem",
	"UpvlyzKSnbGicS4/oY9SCsY8p7asZjZRz4eXdADf2/Gb8N8Dwa+IPdyK9O8LA9zSvmp+0kAEt97dcGGJ",
	"No/qUTPTrtBf395bL9WPbITKAdNV1O8ACLnIcOpsLyRS9VM5nSK9OqIVXF1znF814iVHqwKIh6JM8bT6",
	"808v30NzJyPoO/nN92Bxhk6uIcHE9dUZiqAkRjCnsv8Z+9hsgxGiPfxm7fqsYuK0xw76ucBrZGk9/HDf",
	"HGwpzPEr4WV7vrC8C0NIA5UTg5wgKwIym7TizsnFwLgqiU3s3YViNIqkb7xlOPeRxG17pUg0MGcd6hMe",
	"2w+8u8fMlCymM18VqEwdpxX5CkJG+gKOLKWqZCF6LXiVmo6jAVwuRDxTUshCn5XEScE5ReqL4kxSZ+hP",
	"uEKKEvDpj+FYyWImCzOWn2rZyYfRUGgZoki1r/qGwLMME84MVgM55enDq5XEYqESQl1fehPxXmmlEVPb",
	"gVUXDjzeV6HJT28MZrkZfCPCgIstAEXIXcMwWZ2Ij3kMPsZdML2N5B1nakF8f+LbbgcaSyF8Lr/dybdy",
	"pnaTjWCom9/w5E7dbJP4oF1hwr+o7cuXorzykQPdY3tn3lIQ+97NHBb4X72VgxBpvY6xmke4fo0fXFWT",
	"fagXJRxDW9UdtIuTu19F1wm6lX31xorvN39hOX3Kgx+3RJVz35jOxVJUTel24VS72MA8Ov3bBPYXNIHt",
	"hoZf0Gb21CrEalFLnI6lTBM5F2utaY5GtjClRevtZvdKA/u+A795oxzzZf7rp7sD32tYYlaolbFi2Tj1",
	"JgsfCm9HeKArVXbG9CwChdfyI4baPKF6Togt8MEWmSth5SvVUmWjVlk0V1dnQRV1KNpwKATlTfjJ6qqs",
	"NkwkTCVgwYUGJqmcO2uO0wxdHrjFLT0UDKyeJRVTiyrdcrWVRTtkrxlZ/nsz/gAIcKB2Wt/vBRaWJznE",
	"eKBDKIn22JAM/u0r2ZOvBH0FHiJ9VmJ0v348u7pOaqxBSRdfmDMTz1bcB5eORC7sq98uebS38oU8BWtv",
	"pW/AUfCXlrra1PeOIrMRpIIE6V/bS1iB4spQvNX2LiqNvycNtlF2/55xfRWav3beGi6etmMSnYHGdSyg",
	"5Vyi6Z+7KNnGtG2m8fmW+L9fXHvm800oz1XDOOSbNnI0Zsx5ISghpTTHL9CbF0+3IKL3Ur5hYuGPW6+P",
	"3JNTIKwrEbdoRLl5vJWFWYu49vk2coU/c/t6yxIkqSUgHJBnrhQtDtevrHkPHsVVIf3ulfpK+43C7Hui",
	"uM4K/18J5VXSnTSM1MxlAhzchgJ3v7ROjvdPf/UCxk79wE851QuSqkz2LXSQY++a1EIhu5r85sXrQlPK",
	"5gwbytFOqK+qZJJu3e5ZOmcL7b1xiYbT40eUKX0teVJmwiHlgRCAnJtPs6zy4A2FnrEcnbvP+8rnM5dt",
	"XjEyeuqqcTvICml80j8VnXVvhc59TIS6o160pXPhGlAEdYNSualzlpDUOHIofHLUAC5q1zb1IHz1rkvL",
	"8+dz73R/WzXsWRxjbiUSeOYAk7EFFZl11wOB8hZq111j+HOccrGM3gfau6sbqn9ILtrA4gMurcbsf9Zz",
	"EGv+bouSAuclclNSloZChFv1rOGfHoqxTBYPNIw6C6NTAuiIUnciELIjjUKjiXw0SrnT6yWWY1HbHVvl",
	"RfVO9vf1KvJDQWXkuVlbOr40nqTS1Y9vAENIU+/300h65a268Q2Peyj4WqN8NJo64TR2/a9CG0j5R6ph",
	"z0U36fnz2w+5tbsy3LNPZqnvwGrXzAAuu1Cm1s1xDeKR9/Cer+TtciyMq/ZB4L6ZlnfHTCgcia9G55sd",
	"rOEwjqRWC421lM09IXFHUuhXIin+4rnDvyXE+5AQHR7YC9RVuG3l2nMz21FIdKhN9nKRbCEbuuBLKxo2",
	"+/cuS3ml/BbWOhT1xUZrZcsd5LZ245G9XSOrOpzchehm+VCH+KZRmK9GdnMQ8Ld+DeuWJJiVGFf1HFgZ",
	"EfSaa3NevXZLhrZV3SE/3aKj79TduQM7glpCzmFXS4YDjZhgUpd8a8ArARoynTeGLTg3fWjMtmSc79pJ",
	"9cqR/+5V0utwxG4KCvj6IxgbaSblaRxUKScud7x+GAHwqz3kP6HZC7jv8I7zy/uWvd6ufEvp9y7Pzmf7",
	"k+i88txKX1art2fCqQCjz00/g1Ht+ShqFRWMmu1QIhiFgn+jwVBclnUKYVWZQifYdxYqjFzlQ3VNtyey",
	"eOZR8QGl3DOyilDRRHuHKDknnS2n8pSkPI5Co2eF15wcsaOhmEjlnfJumq5rtVEj9NYIfPe3cWcN03uW",
	"iNfQz1/RP9eV+VPbdQQOhaOyaxHlRhAxwIH7jwylGKk4jlTryLPrhjsq0Xit/FCiRXj5CzLgrSSQ1oL3",
	"KojcO4cu0hQw4QZmXBupqDBT/ZqVaVJ2QFuPCxsS3Bu57fs/NJcCfb8yY71xmw/NJ3PgGKnnIBhZA6AH",
	"1+rQaGd2Cqnc+2DTtRm+kPnNn9JXEA7dHas89dBfOrQGzm8p36/Iyt/A7eirv6hs/yLEu/rc8frF8xRi",
	"pmOWoD5cQTXdsU61Ksa3hPW+5KLdCe54/wT375gl0y1ElcipULCMgoicYF7Waw51oQ+3YxRHzPcrXHtV",
	"hqaGN8fhaKnUOPsEdHe64sKmUGIA9Ur4j48HoaTdDbO6TrbJ6moXdKdCanGhdL1N75jMqFailIUu/VhP",
	"qTB/WQvO9WXN2RRXLdwN++XKGvlTfMemazX5b6CaAEk4FugZKkrS91uDCfrmGCWl1LvmRvZ4uLC8peEo",
	"DujdSSFjljIRr7FD/oTmeXjnDi/Uuzv4sLqvMWnvJzQg0ECAMvwX6LKZHuSMu2CNBMdG1w+2dnzlAXUe",
	"X6kbbKEGfsHz20X5+8qUvhW6R1Vbs0GDq01saxSPm1qX9i1DNVb3hdSWNbalbyCPs1PVKVX+LXR8R+W1",
	"3vCrcnuTej/4rw2RniWJW9mX1H1Dr/yOYOMk+SubKJ8lSdWUxchKeODimhus2llXsYjbytceMY/+LDSq",
	"V23NfLnzV9PoGTMBCjN57aqaCSn64VHoRvNMLMLKM7YYCv+6mWGmkXomHVCjxkNfq6gaWUjjezhK5TZn",
	"v0ygPxS1/jehMY5UMClCCUGgLfgCxAFLHX8fDMX7Mt/vga5f7qWo7F1lHqihEcwfqCQcuN4VUORD4e4L",
	"6pdPa/NxrZlPztM8RWE/pBLDGuRkQnLCAF7V+upQHSUNRe5CHiY4p9ADJqrGMxEBN+fCyvqjRoOcEXA9",
	"FBRGbsXMevuC7hADC8I7YTRRZx6Uw6I7zo/tMN241QeU+OtS/oUnrkBCpdXH7VxbzJACnwZUoaCLsvGp",
	"p7BteYFCq51zMe1vJZRehNe/Eem0vd5txdRl+bEEVGn6N5jlKbNU3q0DlF9sFCWXVvl1ypTtZX6xkNT2",
	"md69lHkHAuMajFmBJB3kqcsGUevp8rL23tdNkdVKb06LNagAxeO3Sa8Otk3EV1vQ10l2y03C7png6kf2",
	"7St0F9TmlEL9w7bgQAoM123OFjr0VzxciVOeVnmWS2VBZQWzOfedpztjUN8xRU094DK8C+eXv1jeIJUr",
	"l+k7huaubKYOCQpFaobiYJSoxZUqxBlQisYh2dlllnFLAwZqz33TCRgvfNtWMXWh4kNBdBKBa11qf/d7",
	"dgUsXDGL8hsLEyvUS4WV3SRHNRSuf6KSc+pdUe0nLvuMnAGF+yg5f1BrkBrLtMiEbzQW6m5oPhWYDEVd",
	"KPcOhCCbKzmHgxFFCkEfcsaT0eEA3uKUlYlVvplqrDDhRioNB/Y1t3iSrCmRRM7xMIJc+kbf5Ycko0ul",
	"B/BsKOaYptQ4FWmPoAvnEXC6gJXYqbtV4SKYjUxR2UUfEvRmTAMzQ5Ei08b1nvflnAggmic4gAtJp8sM",
	"XHNpLwRf9vyaKc4sOrI0HQo7X+QS1CyMIrsQMFLChCmYKJmBe2OcMvGRolWoqIliPKWAq2HvvTQsDUAd",
	"9uxuDmm7+iPPc0wqdYUOXhbCUL7yUIz8G1f0o68pa8X12IALiR+K0QtmMHpRi6EJoajRudQmOvdun2hY",
	"HB8/jK22cEL/xNovp/6XwWDg9BoUE6li6jcyFD9aqdcCaz5DZVXe1PA8DQdHJ3xAP/bDwdPrhxFBu0IH",
	"GGMsqfkKaLQM3JQo/TT0rA67gKnLBBr9+vHoH7+NhkIXkwn/5Cu5gKN4TLzCSAVTeZrC2E5MpW4JVoZA",
	"H14eChddRKL6GIHCzgNaeioRMuOCpRBLbVxFUK4hZhrhoLkZqkuSTvqOHriGREk6zTHGrNAIVYshl3uj",
	"i5y41FBYfHSxTLmlegcBIqWatbtseqys5u01YTqON3VuQe9ZfZ24gb0CgE0ZF94LQmifMMPGdgshWJ4I",
	"g1rWuPrBPjUMQ4xhMGUM4IPvsOMnm/raOVL0KROLIhzzlMU4k2mCqkqCk5ZtIJ8K+IgLezrMN3x96hkq",
	"S70xgUwZccp41kwcsxLFpKCmOFSCx27970wlQF4+fQanj5/AP/hzUGxuefhTeHx8fEyY9xQelir8UxeB",
	"CSn1/RoK+1U8Y5bLVCHitO+M0fnZw+5zoVE4/mTpsoLoULigakjZGFNIuTaR5fVU3nbM4o8UMUnX1qjL",
	"DvCKcLFk1nsKmWnN8oW8+EurWO1keuduWzhwgaytW9ZKG3cpSu2wMC9XLS3MX+9fKPLHbaC0RtI1tEKk",
	"OTgdDCpqqItSXmqqxKgMN0cHvdkXyt5NQalQ+6LsrlrmkzlD3b3Kx99WOb+leMCDsgGthnpfygh0rIqx",
	"TzCOwJfSYGlaVurqSLZekeHg8eme8w3Pa/u8C3r8Cc0S/LpAsDYYbG+k1e5E/pUkfd57LFdLAaU4qc2n",
	"VjLHo3q74HU88llo0roFv3LNrBvc6bb7Cl6exr4e6NA4+8BKK7qUVbjghrOUemh7Ku+k3s7mK5doapvd",
	"w6UQxr/1veD2rtn1F0O4D9Q9GpiA7z59Fw7j3duf4MDK5k8e9VHEMsEkAqeX/QAnx6ePYLwwqA/XoSWx",
	"4SOnrPc7ahO1bHkCdBHHqBvqf1lTxbdjjxrsvDQBuOIpVsX3pRidsYLBRKGedRSr4FoXVsOVDYQkLc0q",
	"r1Yt0JCGCl1dArNr8U5J66G80Z7MfG50NxNN+pXxS1pZOKCnlO37xbPlb2Y33LV2w18pJ79Wp4nwrZaG",
	"74jQW912S8Nvs4GNdZq83Ohq08QsTYkNBAItK+sET7wuLMQxcWYVi3o03VBwDTOrXpO63kjiNvIjCmIP",
	"ZP7IUWmujU8pJNPRgMYYDUWzgf27ny/fO+ZE2f8WMo2KPkYOxWgN7wu9l/xeQsW7j4i5hrlUZPgohLHL",
	"9584loiJ3sCBAurviQMtT7QV6zldPt5zqnpMRnU+6ahadPgU2JxxsjB7GLiSCb2vmhF8LaU6QwUqj3iO",
	"cCepnFdFqDyqVuWhHBquvcmFNCX9rI0qfrN423h1j7dRfaJ3Cid6f9lpXVoUmWSrFUCucIIKfUj1jgpW",
	"B9TunopXAOz+5IetTuzLKl8+aeVWh12RTVfF+S4W3uhtty/2XRXmu6PS6I7HfLEcQyeNdJxU1XTO706D",
	"TJPy59WMbjnYacvMxFsH6JQD3CxR8YvkHFbxK9vFrWhkyrHAzjaY5y3vBuhi7LQAJ22BvA4FmHy4TKNw",
	"xdFISINUAILqWpQl/GpufHpl5NwuA3C9zJyHJVRiMtInIVfdAVFR2YngCpeTCPAT9bsCXRkpyRXsPeTO",
	"VeXysKidA2rTd6lWvot1ra/1wXgBIxkTCidXzIwiu2oBo9jZ9+1Phz5AVeaurAYozJ3xf0SjXPFkBCU2",
	"gWBKSR8f4IDurnup0bv49dPgnkw0NDcqpKlv1rmDgxuYTwU1f2wtp1EipGMhykOawpRdLZOhCN8QyCh9",
	"BjUMy5h5ks2HPeg3onkYxRoQ9Kn0qhgKbsrak5qL2JeEpCJTQpbVGiqHod3yghxv5LD3dby6xOtLh7BL",
	"tNySyko0NX60Afxzxg3qnPo4ajCKSkuuSrH7fW1obMY+vSYHYdXyrfx7OVB2KTvwgjDFLm3CU+NCxeuB",
	"Gw4dBvBz5gptenypIWgNPao8fLsX/JSnVvPzS+7aWsDORv5gGQa2Ieq3Hf0V9bRZpPYH+2FHfuZbQrcu",
	"bKuhAdUHddjSxKuhKBGLvFb18p917KmoYeEYzTIadSZSViTS2yX0eU0WauAxzSTUk+ObZKG6xNPtmwvu",
	"M/fP0d02mX/3LnS4pVXhTpZ3NfDI8feG6WIainZUkWLEV2oXYznAlvLGLWISq0//O9Q7awTxrat41o4I",
	"XaXf7hHyx/cUkPlt9vyqHeR4ARTYRYfYbxdZWort3bYMmuX6V1aF8IXOjKz/1a6KRqJkNBQjNx/JaQN4",
	"Ls3MCkDGCjPBRBnUk7Jq26QlmD7QZeilZSj0XcInE/RxfBQaSJE7LneqjsQUMoYJN6vrnN0tzu7LC3zD",
	"MOb7opr/LjXPbsoyq7usyF1/rdUm/l98RGBQUUyRe6P8gfe4GQnP3r0CbRJZGIqOpYp+YykNzGfc6g8u",
	"JFYbK6rGqDCTYmGlbe+zOKyClf08NIJTwwry8ZEjQ8kUf6D1DuBVglkuLSadkfZpz08Yusm1j1kJHkon",
	"ew3Fo5Nj+MkK1M16wbSbTpO974FBdcP355su8jDRF8oJWOUqpL5f/li+hqLad5nUvspu/8oHxNcQffD1",
	"uhsJe0q/YuzRyEfHdhFcnMr9t4whuu2rQngo1pMXyk78IUR30ORSRd7mT9owU6z1YxAULt1r+71zymnW",
	"pDetLFnt6pWH6uRtIM2YdoW2y1NcA5laN8QqnKjTUhemdT1JJWUZV0Ej9YgMnxcgC+UsIT7EZMxNxvKh",
	"KCjwxBUrIpUp5SjMU38rqGtUUORUVpZyWIhfC2QKtekL5NPZWBZqKDTLchfl7HqC2DWxKfVW5QYUCstM",
	"IFZc58AMJU6fX16C5n/gAM5JTdNDQVKXi5lnlGTu8zPc9Vc6vWtNYQfw3IWLaNAzWaTJUMQsnqG9r0b/",
	"9/UPfzqoXPnAiCtmPo+qsvCWkLBcXelopshzCxq6ILuuEN+XuAxv+gq6E/OMTfEoF9Mm5pcDj7lgZIhY",
	"YttL4dZvf3KBRd+KtmnR1LdDfKAh558wdbkOtTAqQqG+l9cZCRBdTogmpVsA23vvmX169utv9hgcUXRZ",
	"IV/LmKWQ4DUcvJDxR1RgWafUaCcqVNo7682Myc+OjlL75kxqc/bd8XfHJNT7hSzTeb2fAaVV0H9kYaKg",
	"1LjErVTKj0U+qDCOtrRsu3L1S52S45ShGc+bRR5CWx6WJPbSYVWpiJgJYEniFCE9aFkZdcd0IQndUS9T",
	"Y26oH7LLfclkghoO8PeCpZHLY4kgR2VVvMhxAn04gJo9IRmAVRs1GMXijxQY1lWDura0Mml+eXGXLluj",
	"qzo+ZvJfHP4LdFpMDwdwgSwhNdfOd30yWDIq8s4JLAIUFhUbtarIYrWqWtUA3royFcTVaxOV9aqWpxn9",
	"fy7R6v8fgaLUSZ+6JicTXZu4NlhdcVge732ZNp8xg4qz1FI2cEFF91haGd/8rTFm8ccp5dtRDA2q2lSV",
	"G6rDkEp12Gr11VwlNjlZbd6rJfJHUK8QVUf9UJmt40SU1LrvMyOKNO0b/GSCyZ3cWwEbat/pI3JstdYC",
	"7se6EcSltjXgTHbG5XU8L9KPfZdkQbEh/sRmi0Q5FXCsmEj6AueNNA4B+MmgEiyl25nH+ED7ZI4B+MD1",
	"dNFM9tDtNI/a+kKax/ICX/NrFFaVspu2giinv3Ilx3bT1MHM0hom9fFmyNJOtvPKSq0ixv6cJ15ULBmb",
	"JS/vJK5Uwaf2AIwqXGO+a1TjsmSMVZB9HE7pZ+Y+T89JtDCWyaKOEKQML6/qx1Jaa0vVA3jmZvatsXhK",
	"viwn47rmqU1yKvLe598+/58AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
