// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	CookieAuthScopes cookieAuthContextKey = "cookieAuth.Scopes"
)

// Defines values for ActivityItemKind.
const (
	ActivityItemKindExpense    ActivityItemKind = "expense"
	ActivityItemKindSettlement ActivityItemKind = "settlement"
)

// Valid indicates whether the value is a known member of the ActivityItemKind enum.
func (e ActivityItemKind) Valid() bool {
	switch e {
	case ActivityItemKindExpense:
		return true
	case ActivityItemKindSettlement:
		return true
	default:
		return false
	}
}

// Defines values for AdminSetUserRoleRequestRole.
const (
	AdminSetUserRoleRequestRoleAdmin AdminSetUserRoleRequestRole = "admin"
	AdminSetUserRoleRequestRoleUser  AdminSetUserRoleRequestRole = "user"
)

// Valid indicates whether the value is a known member of the AdminSetUserRoleRequestRole enum.
func (e AdminSetUserRoleRequestRole) Valid() bool {
	switch e {
	case AdminSetUserRoleRequestRoleAdmin:
		return true
	case AdminSetUserRoleRequestRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for AdminUserRole.
const (
	AdminUserRoleAdmin AdminUserRole = "admin"
	AdminUserRoleUser  AdminUserRole = "user"
)

// Valid indicates whether the value is a known member of the AdminUserRole enum.
func (e AdminUserRole) Valid() bool {
	switch e {
	case AdminUserRoleAdmin:
		return true
	case AdminUserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for AdminUserWeekStart.
const (
	AdminUserWeekStartN0 AdminUserWeekStart = 0
	AdminUserWeekStartN1 AdminUserWeekStart = 1
)

// Valid indicates whether the value is a known member of the AdminUserWeekStart enum.
func (e AdminUserWeekStart) Valid() bool {
	switch e {
	case AdminUserWeekStartN0:
		return true
	case AdminUserWeekStartN1:
		return true
	default:
		return false
	}
}

// Defines values for AdminUserCreateRequestRole.
const (
	AdminUserCreateRequestRoleAdmin AdminUserCreateRequestRole = "admin"
	AdminUserCreateRequestRoleUser  AdminUserCreateRequestRole = "user"
)

// Valid indicates whether the value is a known member of the AdminUserCreateRequestRole enum.
func (e AdminUserCreateRequestRole) Valid() bool {
	switch e {
	case AdminUserCreateRequestRoleAdmin:
		return true
	case AdminUserCreateRequestRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for Cadence.
const (
	Biweekly Cadence = "biweekly"
	Daily    Cadence = "daily"
	Monthly  Cadence = "monthly"
	Weekly   Cadence = "weekly"
	Yearly   Cadence = "yearly"
)

// Valid indicates whether the value is a known member of the Cadence enum.
func (e Cadence) Valid() bool {
	switch e {
	case Biweekly:
		return true
	case Daily:
		return true
	case Monthly:
		return true
	case Weekly:
		return true
	case Yearly:
		return true
	default:
		return false
	}
}

// Defines values for ExpenseRevisionField.
const (
	AmountCents ExpenseRevisionField = "amount_cents"
	CategoryId  ExpenseRevisionField = "category_id"
	Description ExpenseRevisionField = "description"
	IncurredAt  ExpenseRevisionField = "incurred_at"
	Notes       ExpenseRevisionField = "notes"
	PayerId     ExpenseRevisionField = "payer_id"
	Splits      ExpenseRevisionField = "splits"
)

// Valid indicates whether the value is a known member of the ExpenseRevisionField enum.
func (e ExpenseRevisionField) Valid() bool {
	switch e {
	case AmountCents:
		return true
	case CategoryId:
		return true
	case Description:
		return true
	case IncurredAt:
		return true
	case Notes:
		return true
	case PayerId:
		return true
	case Splits:
		return true
	default:
		return false
	}
}

// Defines values for SmtpTlsMode.
const (
	None     SmtpTlsMode = "none"
	Starttls SmtpTlsMode = "starttls"
	Tls      SmtpTlsMode = "tls"
)

// Valid indicates whether the value is a known member of the SmtpTlsMode enum.
func (e SmtpTlsMode) Valid() bool {
	switch e {
	case None:
		return true
	case Starttls:
		return true
	case Tls:
		return true
	default:
		return false
	}
}

// Defines values for SplitMode.
const (
	Equal   SplitMode = "equal"
	Exact   SplitMode = "exact"
	Percent SplitMode = "percent"
	Shares  SplitMode = "shares"
)

// Valid indicates whether the value is a known member of the SplitMode enum.
func (e SplitMode) Valid() bool {
	switch e {
	case Equal:
		return true
	case Exact:
		return true
	case Percent:
		return true
	case Shares:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMeRequestWeekStart.
const (
	UpdateMeRequestWeekStartN0 UpdateMeRequestWeekStart = 0
	UpdateMeRequestWeekStartN1 UpdateMeRequestWeekStart = 1
)

// Valid indicates whether the value is a known member of the UpdateMeRequestWeekStart enum.
func (e UpdateMeRequestWeekStart) Valid() bool {
	switch e {
	case UpdateMeRequestWeekStartN0:
		return true
	case UpdateMeRequestWeekStartN1:
		return true
	default:
		return false
	}
}

// Defines values for UserWeekStart.
const (
	N0 UserWeekStart = 0
	N1 UserWeekStart = 1
)

// Valid indicates whether the value is a known member of the UserWeekStart enum.
func (e UserWeekStart) Valid() bool {
	switch e {
	case N0:
		return true
	case N1:
		return true
	default:
		return false
	}
}

// ActivityItem defines model for ActivityItem.
type ActivityItem struct {
	// Cadence When kind=expense and the expense matches a recurring template by content, the template's cadence. Omitted otherwise.
	Cadence *Cadence `json:"cadence,omitempty"`

	// Expense Present iff kind=expense.
	Expense    *Expense         `json:"expense,omitempty"`
	Kind       ActivityItemKind `json:"kind"`
	OccurredAt time.Time        `json:"occurred_at"`

	// Settlement Present iff kind=settlement.
	Settlement *Settlement `json:"settlement,omitempty"`
}

// ActivityItemKind defines model for ActivityItem.Kind.
type ActivityItemKind string

// ActivityPage defines model for ActivityPage.
type ActivityPage struct {
	Items []ActivityItem `json:"items"`

	// NextCursor Pass to the next request as `cursor`. Absent when there are no more items.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// AddMemberRequest defines model for AddMemberRequest.
type AddMemberRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AdminAuditEntry defines model for AdminAuditEntry.
type AdminAuditEntry struct {
	Action        string                  `json:"action"`
	ActorUserId   openapi_types.UUID      `json:"actor_user_id"`
	CreatedAt     time.Time               `json:"created_at"`
	Id            openapi_types.UUID      `json:"id"`
	Ip            *string                 `json:"ip,omitempty"`
	Metadata      *map[string]interface{} `json:"metadata,omitempty"`
	Success       bool                    `json:"success"`
	TargetGroupId *openapi_types.UUID     `json:"target_group_id,omitempty"`
	TargetUserId  *openapi_types.UUID     `json:"target_user_id,omitempty"`
	UserAgent     *string                 `json:"user_agent,omitempty"`
}

// AdminAuditListResponse defines model for AdminAuditListResponse.
type AdminAuditListResponse struct {
	Items  []AdminAuditEntry `json:"items"`
	Limit  int               `json:"limit"`
	Offset int               `json:"offset"`
	Total  int               `json:"total"`
}

// AdminGroup defines model for AdminGroup.
type AdminGroup struct {
	CreatedAt       time.Time          `json:"created_at"`
	CreatedBy       openapi_types.UUID `json:"created_by"`
	DefaultCurrency string             `json:"default_currency"`
	ExpenseCount    int                `json:"expense_count"`
	Id              openapi_types.UUID `json:"id"`
	MemberCount     int                `json:"member_count"`
	Name            string             `json:"name"`
}

// AdminGroupListResponse defines model for AdminGroupListResponse.
type AdminGroupListResponse struct {
	Items  []AdminGroup `json:"items"`
	Limit  int          `json:"limit"`
	Offset int          `json:"offset"`
	Total  int          `json:"total"`
}

// AdminSetUserRoleRequest defines model for AdminSetUserRoleRequest.
type AdminSetUserRoleRequest struct {
	// Password The admin's own password (step-up).
	Password string                      `json:"password"`
	Role     AdminSetUserRoleRequestRole `json:"role"`
}

// AdminSetUserRoleRequestRole defines model for AdminSetUserRoleRequest.Role.
type AdminSetUserRoleRequestRole string

// AdminUser defines model for AdminUser.
type AdminUser struct {
	CreatedAt time.Time `json:"created_at"`

	// DeletedAt Set when the account is soft-deleted.
	DeletedAt   *time.Time `json:"deleted_at,omitempty"`
	DisplayName string     `json:"display_name"`

	// Email Decrypted email. Null for soft-deleted users (their encrypted email is scrambled at delete time).
	Email     *openapi_types.Email `json:"email"`
	HasAvatar bool                 `json:"has_avatar"`
	Id        openapi_types.UUID   `json:"id"`
	Role      AdminUserRole        `json:"role"`
	WeekStart AdminUserWeekStart   `json:"week_start"`
}

// AdminUserRole defines model for AdminUser.Role.
type AdminUserRole string

// AdminUserWeekStart defines model for AdminUser.WeekStart.
type AdminUserWeekStart int

// AdminUserCreateRequest defines model for AdminUserCreateRequest.
type AdminUserCreateRequest struct {
	DisplayName string                      `json:"display_name"`
	Email       openapi_types.Email         `json:"email"`
	Role        *AdminUserCreateRequestRole `json:"role,omitempty"`
}

// AdminUserCreateRequestRole defines model for AdminUserCreateRequest.Role.
type AdminUserCreateRequestRole string

// AdminUserListResponse defines model for AdminUserListResponse.
type AdminUserListResponse struct {
	Items  []AdminUser `json:"items"`
	Limit  int         `json:"limit"`
	Offset int         `json:"offset"`
	Total  int         `json:"total"`
}

// Balance defines model for Balance.
type Balance struct {
	DisplayName string `json:"display_name"`

	// NetCents positive = owed to user; negative = user owes
	NetCents int64              `json:"net_cents"`
	UserId   openapi_types.UUID `json:"user_id"`
}

// BalancesResponse defines model for BalancesResponse.
type BalancesResponse struct {
	Net        []Balance        `json:"net"`
	Simplified []SimplifiedDebt `json:"simplified"`
}

// Cadence defines model for Cadence.
type Cadence string

// Category defines model for Category.
type Category struct {
	// GroupLabel Section header for the picker (e.g. `Entertainment`, `No category`).
	GroupLabel string             `json:"group_label"`
	Id         openapi_types.UUID `json:"id"`

	// Label Human-readable name.
	Label string `json:"label"`

	// Slug Stable machine identifier (e.g. `groceries`). The frontend maps this to an icon.
	Slug string `json:"slug"`
}

// ChangeEmailRequest defines model for ChangeEmailRequest.
type ChangeEmailRequest struct {
	NewEmail openapi_types.Email `json:"new_email"`

	// Password The caller's current password (step-up).
	Password string `json:"password"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	NewPassword string `json:"new_password"`
	OldPassword string `json:"old_password"`
}

// ConfirmEmailChangeRequest defines model for ConfirmEmailChangeRequest.
type ConfirmEmailChangeRequest struct {
	// Code 6-digit code received at the new address.
	Code string `json:"code"`
}

// CreateExpenseRequest defines model for CreateExpenseRequest.
type CreateExpenseRequest struct {
	AmountCents int64 `json:"amount_cents"`

	// CategoryId Defaults to the `other` category when omitted.
	CategoryId *openapi_types.UUID `json:"category_id,omitempty"`

	// Currency Defaults to group.default_currency if omitted
	Currency    *string    `json:"currency,omitempty"`
	Description string     `json:"description"`
	IncurredAt  *time.Time `json:"incurred_at,omitempty"`
	Mode        SplitMode  `json:"mode"`

	// Notes Optional free-form notes about the expense.
	Notes   *string            `json:"notes,omitempty"`
	PayerId openapi_types.UUID `json:"payer_id"`
	Splits  []SplitInput       `json:"splits"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	DefaultCurrency *string `json:"default_currency,omitempty"`
	Name            string  `json:"name"`
}

// CreateRecurringExpenseRequest defines model for CreateRecurringExpenseRequest.
type CreateRecurringExpenseRequest struct {
	AmountCents int64   `json:"amount_cents"`
	Cadence     Cadence `json:"cadence"`

	// CategoryId Defaults to the `other` category when omitted.
	CategoryId *openapi_types.UUID `json:"category_id,omitempty"`

	// Currency Defaults to group.default_currency if omitted
	Currency    *string            `json:"currency,omitempty"`
	Description string             `json:"description"`
	Mode        SplitMode          `json:"mode"`
	NextRunAt   time.Time          `json:"next_run_at"`
	PayerId     openapi_types.UUID `json:"payer_id"`
	Splits      []SplitInput       `json:"splits"`
}

// CreateSettlementRequest defines model for CreateSettlementRequest.
type CreateSettlementRequest struct {
	AmountCents int64              `json:"amount_cents"`
	Note        *string            `json:"note,omitempty"`
	SettledAt   *time.Time         `json:"settled_at,omitempty"`
	ToUserId    openapi_types.UUID `json:"to_user_id"`
}

// DefaultSplitEntry defines model for DefaultSplitEntry.
type DefaultSplitEntry struct {
	// BasisPoints 0..10000; the two entries must sum to exactly 10000.
	BasisPoints int                `json:"basis_points"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Expense defines model for Expense.
type Expense struct {
	AmountCents int64              `json:"amount_cents"`
	CategoryId  openapi_types.UUID `json:"category_id"`
	CreatedAt   time.Time          `json:"created_at"`

	// CreatedBy User who recorded the expense. Distinct from `payer_id` (who fronted
	// the money) - any group member may create an expense on behalf of any
	// other member, and the history attributes the action to this user.
	CreatedBy   openapi_types.UUID `json:"created_by"`
	Currency    string             `json:"currency"`
	Description string             `json:"description"`
	GroupId     openapi_types.UUID `json:"group_id"`
	Id          openapi_types.UUID `json:"id"`
	IncurredAt  time.Time          `json:"incurred_at"`
	Notes       string             `json:"notes"`
	PayerId     openapi_types.UUID `json:"payer_id"`
	Splits      []Split            `json:"splits"`
}

// ExpenseRevision defines model for ExpenseRevision.
type ExpenseRevision struct {
	EditedAt  time.Time          `json:"edited_at"`
	EditedBy  openapi_types.UUID `json:"edited_by"`
	ExpenseId openapi_types.UUID `json:"expense_id"`

	// Field Which field was changed.
	Field ExpenseRevisionField `json:"field"`
	Id    openapi_types.UUID   `json:"id"`

	// NewValue New value, stringified.
	NewValue string `json:"new_value"`

	// OldValue Previous value, stringified.
	OldValue string `json:"old_value"`
}

// ExpenseRevisionField Which field was changed.
type ExpenseRevisionField string

// Group defines model for Group.
type Group struct {
	CreatedAt time.Time          `json:"created_at"`
	CreatedBy openapi_types.UUID `json:"created_by"`

	// DefaultCurrency ISO-4217 code used when expenses omit currency
	DefaultCurrency string `json:"default_currency"`

	// DefaultSplit Optional 2-member percentage split that prefills the create-expense form.
	// Automatically cleared by the server when the group grows past 2 members.
	DefaultSplit *[]DefaultSplitEntry `json:"default_split,omitempty"`
	Id           openapi_types.UUID   `json:"id"`
	Members      []GroupMember        `json:"members"`
	Name         string               `json:"name"`
}

// GroupMember defines model for GroupMember.
type GroupMember struct {
	AvatarUpdatedAt *time.Time `json:"avatar_updated_at,omitempty"`

	// DeletedAt Set when the user has soft-deleted their account; `display_name` is a tombstone.
	DeletedAt   *time.Time         `json:"deleted_at,omitempty"`
	DisplayName string             `json:"display_name"`
	HasAvatar   bool               `json:"has_avatar"`
	JoinedAt    time.Time          `json:"joined_at"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// ImportSplitwiseBalance defines model for ImportSplitwiseBalance.
type ImportSplitwiseBalance struct {
	// CsvName Member name as it appears in the CSV header.
	CsvName string `json:"csv_name"`

	// NetCents Net cents; positive = member is owed, negative = member owes.
	NetCents int64 `json:"net_cents"`
}

// ImportSplitwiseMember defines model for ImportSplitwiseMember.
type ImportSplitwiseMember struct {
	// CsvName Name as it appears in the CSV column header.
	CsvName string              `json:"csv_name"`
	Email   openapi_types.Email `json:"email"`
}

// ImportSplitwisePreviewRow defines model for ImportSplitwisePreviewRow.
type ImportSplitwisePreviewRow struct {
	AmountCents  int64     `json:"amount_cents"`
	CategorySlug string    `json:"category_slug"`
	Currency     string    `json:"currency"`
	Description  string    `json:"description"`
	IncurredAt   time.Time `json:"incurred_at"`
	PayerCsvName string    `json:"payer_csv_name"`
}

// ImportSplitwiseRequest defines model for ImportSplitwiseRequest.
type ImportSplitwiseRequest struct {
	// Csv Raw CSV text exactly as exported by Splitwise. Hard cap 256 KiB.
	Csv             string `json:"csv"`
	DefaultCurrency string `json:"default_currency"`

	// DryRun When true, parses the CSV and returns the preview without writing anything.
	DryRun    *bool  `json:"dry_run,omitempty"`
	GroupName string `json:"group_name"`

	// Members One entry per CSV user column, in column order. Must match the header exactly.
	Members []ImportSplitwiseMember `json:"members"`
}

// ImportSplitwiseResponse defines model for ImportSplitwiseResponse.
type ImportSplitwiseResponse struct {
	// Balances Projected net balance per member after the import, derived from the expenses AND settlements that will actually be created (sign convention matches /v1/groups/{id}/balances).
	Balances []ImportSplitwiseBalance `json:"balances"`

	// CsvCurrencies Distinct ISO currency codes seen in the CSV, in first-seen order.
	// DoTheSplit groups are single-currency, so a length > 1 means the
	// CSV mixes currencies and the imported values will be stored under
	// the chosen `default_currency` regardless of their original code.
	// UI clients should warn the user in that case.
	CsvCurrencies   []string `json:"csv_currencies"`
	DefaultCurrency string   `json:"default_currency"`

	// ExpenseCount Number of valid expenses parsed from the CSV.
	ExpenseCount int `json:"expense_count"`

	// GroupId Set only when the import was committed (`dry_run: false`).
	GroupId   *openapi_types.UUID         `json:"group_id,omitempty"`
	GroupName string                      `json:"group_name"`
	Members   []ImportSplitwiseMember     `json:"members"`
	Preview   []ImportSplitwisePreviewRow `json:"preview"`

	// SettlementCount Number of valid settlements parsed from the CSV (rows whose Splitwise category is "Payment").
	SettlementCount   int                                `json:"settlement_count"`
	SettlementPreview []ImportSplitwiseSettlementPreview `json:"settlement_preview"`

	// Skipped Raw CSV records (rejoined with commas) for rows that were skipped, capped at 50 entries. Useful for surfacing why an import didn't include certain rows.
	Skipped []string `json:"skipped"`

	// SkippedCount Number of rows skipped (malformed, structurally invalid, or the trailing "Total balance" row).
	SkippedCount int `json:"skipped_count"`
}

// ImportSplitwiseSettlementPreview defines model for ImportSplitwiseSettlementPreview.
type ImportSplitwiseSettlementPreview struct {
	AmountCents int64  `json:"amount_cents"`
	Currency    string `json:"currency"`

	// FromCsvName Member who paid (CSV column header).
	FromCsvName string    `json:"from_csv_name"`
	Note        string    `json:"note"`
	SettledAt   time.Time `json:"settled_at"`

	// ToCsvName Member who received the payment (CSV column header).
	ToCsvName string `json:"to_csv_name"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// NotificationPrefs Per-user, per-event email opt-in flags. All default to false (off).
// The server only emails when the corresponding flag is true AND SMTP is
// configured.
type NotificationPrefs struct {
	// NotifyGroupAdded Email me when I am added to a new group.
	NotifyGroupAdded *bool `json:"notify_group_added,omitempty"`

	// NotifyRecurringRun Email me when a recurring expense is materialized in one of my groups.
	NotifyRecurringRun *bool `json:"notify_recurring_run,omitempty"`

	// NotifySettlement Email me when a settlement is recorded in one of my groups.
	NotifySettlement *bool `json:"notify_settlement,omitempty"`
}

// PasswordResetConfirm defines model for PasswordResetConfirm.
type PasswordResetConfirm struct {
	// Code 6-digit numeric code received by email.
	Code        string              `json:"code"`
	Email       openapi_types.Email `json:"email"`
	NewPassword string              `json:"new_password"`
}

// PasswordResetRequest defines model for PasswordResetRequest.
type PasswordResetRequest struct {
	Email openapi_types.Email `json:"email"`
}

// RecurringExpense defines model for RecurringExpense.
type RecurringExpense struct {
	AmountCents int64              `json:"amount_cents"`
	Cadence     Cadence            `json:"cadence"`
	CategoryId  openapi_types.UUID `json:"category_id"`
	CreatedAt   time.Time          `json:"created_at"`
	Currency    string             `json:"currency"`
	Description string             `json:"description"`
	GroupId     openapi_types.UUID `json:"group_id"`
	Id          openapi_types.UUID `json:"id"`
	Mode        SplitMode          `json:"mode"`
	NextRunAt   time.Time          `json:"next_run_at"`
	PayerId     openapi_types.UUID `json:"payer_id"`
	Splits      []SplitInput       `json:"splits"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	User User `json:"user"`

	// VerificationRequired True when the user must POST a 6-digit code to `/v1/auth/verify` before logging in. False when SMTP is unconfigured and the account was auto-verified.
	VerificationRequired bool `json:"verification_required"`
}

// ResendVerificationRequest defines model for ResendVerificationRequest.
type ResendVerificationRequest struct {
	Email openapi_types.Email `json:"email"`
}

// SearchGroupRef Group descriptor returned alongside search results so the client can
// render the "GroupA" section heading, payer/recipient avatars, and the
// per-group filter without a follow-up `/v1/groups` round-trip.
type SearchGroupRef struct {
	DefaultCurrency string             `json:"default_currency"`
	Id              openapi_types.UUID `json:"id"`
	Members         []GroupMember      `json:"members"`
	Name            string             `json:"name"`
}

// SearchResponse Flat list of matching expenses and settlements, newest first across
// all groups. The client groups them by `group_id` for display. The
// `groups` field is the set of groups the caller is a member of (or the
// subset they filtered to) and is what the per-group filter chip row
// is built from - it is *not* limited to groups that produced a hit.
// `available_category_ids` lists every distinct category present among
// the expenses that match `q` + `group_id` (independent of the active
// `category_id` filter), so the client can hide categories that have
// no hits in the current search from the category picker.
type SearchResponse struct {
	// AvailableCategoryIds Distinct expense categories matching `q` + `group_id`, ignoring
	// the active `category_id` filter. Empty when no expenses match.
	AvailableCategoryIds []openapi_types.UUID `json:"available_category_ids"`
	Groups               []SearchGroupRef     `json:"groups"`
	Items                []ActivityItem       `json:"items"`
	Query                string               `json:"query"`
}

// SetAvatarRequest defines model for SetAvatarRequest.
type SetAvatarRequest struct {
	// PngBase64 Base64-encoded PNG. Decoded size must be <= 1024 bytes and the image exactly 8x8 pixels.
	PngBase64 string `json:"png_base64"`
}

// Settlement defines model for Settlement.
type Settlement struct {
	AmountCents int64              `json:"amount_cents"`
	CreatedAt   time.Time          `json:"created_at"`
	FromUserId  openapi_types.UUID `json:"from_user_id"`
	GroupId     openapi_types.UUID `json:"group_id"`
	Id          openapi_types.UUID `json:"id"`
	Note        *string            `json:"note,omitempty"`
	SettledAt   time.Time          `json:"settled_at"`
	ToUserId    openapi_types.UUID `json:"to_user_id"`
}

// SetupCompleteRequest defines model for SetupCompleteRequest.
type SetupCompleteRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
	Token       string              `json:"token"`
}

// SetupStatus defines model for SetupStatus.
type SetupStatus struct {
	// Locked True after the install ceremony has been completed; false while it is still pending.
	Locked bool `json:"locked"`
}

// SimplifiedDebt defines model for SimplifiedDebt.
type SimplifiedDebt struct {
	AmountCents int64              `json:"amount_cents"`
	FromUserId  openapi_types.UUID `json:"from_user_id"`
	ToUserId    openapi_types.UUID `json:"to_user_id"`
}

// SmtpConfig defines model for SmtpConfig.
type SmtpConfig struct {
	FromAddress openapi_types.Email `json:"from_address"`
	Host        string              `json:"host"`

	// PasswordSet True when an encrypted password is stored. The cleartext is never returned.
	PasswordSet bool                `json:"password_set"`
	Port        int                 `json:"port"`
	TlsMode     SmtpTlsMode         `json:"tls_mode"`
	UpdatedAt   *time.Time          `json:"updated_at,omitempty"`
	UpdatedBy   *openapi_types.UUID `json:"updated_by,omitempty"`
	Username    *string             `json:"username,omitempty"`
}

// SmtpConfigUpdateRequest defines model for SmtpConfigUpdateRequest.
type SmtpConfigUpdateRequest struct {
	// AllowPlaintextCredentials Required when tls_mode='none' and a username/password is provided.
	AllowPlaintextCredentials *bool               `json:"allow_plaintext_credentials,omitempty"`
	FromAddress               openapi_types.Email `json:"from_address"`
	Host                      string              `json:"host"`
	Port                      int                 `json:"port"`

	// SmtpPassword SMTP password. Pass null to leave the existing one untouched; pass empty string to clear it; pass a non-empty value to set a new one.
	SmtpPassword *string     `json:"smtp_password,omitempty"`
	TlsMode      SmtpTlsMode `json:"tls_mode"`
	Username     *string     `json:"username,omitempty"`
}

// SmtpPasswordResponse defines model for SmtpPasswordResponse.
type SmtpPasswordResponse struct {
	// Password Cleartext SMTP password. Empty string when no password is stored.
	Password string `json:"password"`
}

// SmtpTestResponse defines model for SmtpTestResponse.
type SmtpTestResponse struct {
	// Error Short, non-sensitive error code on failure (e.g. "dial_timeout", "auth_failed", "tls_handshake_failed").
	Error   *string `json:"error,omitempty"`
	Success bool    `json:"success"`
}

// SmtpTlsMode defines model for SmtpTlsMode.
type SmtpTlsMode string

// Split defines model for Split.
type Split struct {
	ShareCents int64              `json:"share_cents"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// SplitInput defines model for SplitInput.
type SplitInput struct {
	UserId openapi_types.UUID `json:"user_id"`
	Value  *int64             `json:"value,omitempty"`
}

// SplitMode defines model for SplitMode.
type SplitMode string

// StepUpRequest defines model for StepUpRequest.
type StepUpRequest struct {
	// Password The admin's own password, re-entered for the destructive action.
	Password string `json:"password"`
}

// UpdateExpenseRequest defines model for UpdateExpenseRequest.
type UpdateExpenseRequest struct {
	AmountCents *int64              `json:"amount_cents,omitempty"`
	CategoryId  *openapi_types.UUID `json:"category_id,omitempty"`
	Description *string             `json:"description,omitempty"`

	// IncurredAt When the expense was incurred (independent of when it was recorded).
	// Defaults to the creation time if omitted on create, then immutable
	// unless explicitly set here.
	IncurredAt *time.Time `json:"incurred_at,omitempty"`

	// Mode Must be supplied together with `splits`. When both are present, the server
	// re-resolves per-user shares. When neither is present, existing splits are
	// rescaled proportionally if `amount_cents` changes.
	Mode *SplitMode `json:"mode,omitempty"`

	// Notes Optional free-form notes about the expense.
	Notes *string `json:"notes,omitempty"`

	// PayerId New payer; must be a current group member.
	PayerId *openapi_types.UUID `json:"payer_id,omitempty"`

	// Splits Must be supplied together with `mode`.
	Splits *[]SplitInput `json:"splits,omitempty"`
}

// UpdateGroupRequest defines model for UpdateGroupRequest.
type UpdateGroupRequest struct {
	// CreatedBy Transfer group ownership to another member. Only the current owner
	// may set this; the target must already be a member of the group.
	CreatedBy       *openapi_types.UUID `json:"created_by,omitempty"`
	DefaultCurrency *string             `json:"default_currency,omitempty"`

	// DefaultSplit Set the default 2-member split. Pass an empty array (or null) to clear it.
	// Only valid when the group has exactly 2 members.
	DefaultSplit *[]DefaultSplitEntry `json:"default_split,omitempty"`
	Name         *string              `json:"name,omitempty"`
}

// UpdateMeRequest defines model for UpdateMeRequest.
type UpdateMeRequest struct {
	DisplayName *string `json:"display_name,omitempty"`

	// Timezone IANA timezone (e.g. "Europe/Madrid"). Send an empty string to revert to device detection.
	Timezone *string `json:"timezone,omitempty"`

	// WeekStart First day of the week. 0 = Sunday, 1 = Monday.
	WeekStart *UpdateMeRequestWeekStart `json:"week_start,omitempty"`
}

// UpdateMeRequestWeekStart First day of the week. 0 = Sunday, 1 = Monday.
type UpdateMeRequestWeekStart int

// User defines model for User.
type User struct {
	// AvatarUpdatedAt Cache-buster for the avatar URL. Changes on every upload/delete.
	AvatarUpdatedAt *time.Time `json:"avatar_updated_at,omitempty"`
	CreatedAt       time.Time  `json:"created_at"`

	// DeletedAt Set when the account has been soft-deleted; `display_name` is then a tombstone.
	DeletedAt   *time.Time          `json:"deleted_at,omitempty"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`

	// EmailVerifiedAt When the email address was confirmed. Null until the user verifies, or set automatically at registration when SMTP is unconfigured.
	EmailVerifiedAt *time.Time `json:"email_verified_at,omitempty"`

	// HasAvatar True when the user has uploaded a pixel avatar. Fetch it at `/v1/users/{id}/avatar`.
	HasAvatar bool               `json:"has_avatar"`
	Id        openapi_types.UUID `json:"id"`

	// IsAdmin True when the user has the admin role. Read-only; promotion only happens via the bootstrap path or an admin endpoint.
	IsAdmin *bool `json:"is_admin,omitempty"`

	// Timezone IANA timezone (e.g. "Europe/Madrid"). Null means the client should use the device-detected zone.
	Timezone *string `json:"timezone,omitempty"`

	// WeekStart First day of the week in calendar UIs. 0 = Sunday, 1 = Monday.
	WeekStart UserWeekStart `json:"week_start"`
}

// UserWeekStart First day of the week in calendar UIs. 0 = Sunday, 1 = Monday.
type UserWeekStart int

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	// Code 6-digit numeric code received by email.
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
}

// ExpenseId defines model for ExpenseId.
type ExpenseId = openapi_types.UUID

// GroupId defines model for GroupId.
type GroupId = openapi_types.UUID

// RecurringId defines model for RecurringId.
type RecurringId = openapi_types.UUID

// SettlementId defines model for SettlementId.
type SettlementId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// SetupRequired defines model for SetupRequired.
type SetupRequired = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// cookieAuthContextKey is the context key for cookieAuth security scheme
type cookieAuthContextKey string

// AdminListAuditLogParams defines parameters for AdminListAuditLog.
type AdminListAuditLogParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
	Action *string `form:"action,omitempty" json:"action,omitempty"`
}

// AdminListGroupsParams defines parameters for AdminListGroups.
type AdminListGroupsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminListUsersParams defines parameters for AdminListUsers.
type AdminListUsersParams struct {
	Limit          *int  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset         *int  `form:"offset,omitempty" json:"offset,omitempty"`
	IncludeDeleted *bool `form:"include_deleted,omitempty" json:"include_deleted,omitempty"`
}

// ListActivityParams defines parameters for ListActivity.
type ListActivityParams struct {
	// Limit Max items to return. Defaults to 50.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned by a previous response; omit for the first page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// SearchParams defines parameters for Search.
type SearchParams struct {
	// Q Substring to match. Whitespace is trimmed.
	Q string `form:"q" json:"q"`

	// GroupId Repeat to filter to one or more groups. Omit to search all groups the caller belongs to.
	GroupId *[]openapi_types.UUID `form:"group_id,omitempty" json:"group_id,omitempty"`

	// CategoryId Narrow results to a single category. When set, settlements are
	// excluded from the response. Unknown id silently yields zero matches.
	CategoryId *openapi_types.UUID `form:"category_id,omitempty" json:"category_id,omitempty"`

	// Limit Max items returned. Defaults to 100.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// AdminDeleteGroupJSONRequestBody defines body for AdminDeleteGroup for application/json ContentType.
type AdminDeleteGroupJSONRequestBody = StepUpRequest

// AdminUpdateSmtpConfigJSONRequestBody defines body for AdminUpdateSmtpConfig for application/json ContentType.
type AdminUpdateSmtpConfigJSONRequestBody = SmtpConfigUpdateRequest

// AdminCreateUserJSONRequestBody defines body for AdminCreateUser for application/json ContentType.
type AdminCreateUserJSONRequestBody = AdminUserCreateRequest

// AdminDeleteUserJSONRequestBody defines body for AdminDeleteUser for application/json ContentType.
type AdminDeleteUserJSONRequestBody = StepUpRequest

// AdminResetUserPasswordJSONRequestBody defines body for AdminResetUserPassword for application/json ContentType.
type AdminResetUserPasswordJSONRequestBody = StepUpRequest

// AdminSetUserRoleJSONRequestBody defines body for AdminSetUserRole for application/json ContentType.
type AdminSetUserRoleJSONRequestBody = AdminSetUserRoleRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = PasswordResetConfirm

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = PasswordResetRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody = ResendVerificationRequest

// UpdateExpenseJSONRequestBody defines body for UpdateExpense for application/json ContentType.
type UpdateExpenseJSONRequestBody = UpdateExpenseRequest

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = UpdateGroupRequest

// CreateExpenseJSONRequestBody defines body for CreateExpense for application/json ContentType.
type CreateExpenseJSONRequestBody = CreateExpenseRequest

// AddGroupMemberJSONRequestBody defines body for AddGroupMember for application/json ContentType.
type AddGroupMemberJSONRequestBody = AddMemberRequest

// CreateRecurringExpenseJSONRequestBody defines body for CreateRecurringExpense for application/json ContentType.
type CreateRecurringExpenseJSONRequestBody = CreateRecurringExpenseRequest

// CreateSettlementJSONRequestBody defines body for CreateSettlement for application/json ContentType.
type CreateSettlementJSONRequestBody = CreateSettlementRequest

// ImportSplitwiseJSONRequestBody defines body for ImportSplitwise for application/json ContentType.
type ImportSplitwiseJSONRequestBody = ImportSplitwiseRequest

// DeleteMeJSONRequestBody defines body for DeleteMe for application/json ContentType.
type DeleteMeJSONRequestBody = StepUpRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateMeRequest

// SetAvatarJSONRequestBody defines body for SetAvatar for application/json ContentType.
type SetAvatarJSONRequestBody = SetAvatarRequest

// ChangeEmailConfirmJSONRequestBody defines body for ChangeEmailConfirm for application/json ContentType.
type ChangeEmailConfirmJSONRequestBody = ConfirmEmailChangeRequest

// ChangeEmailRequestJSONRequestBody defines body for ChangeEmailRequest for application/json ContentType.
type ChangeEmailRequestJSONRequestBody = ChangeEmailRequest

// UpdateMyNotificationsJSONRequestBody defines body for UpdateMyNotifications for application/json ContentType.
type UpdateMyNotificationsJSONRequestBody = NotificationPrefs

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// CompleteSetupJSONRequestBody defines body for CompleteSetup for application/json ContentType.
type CompleteSetupJSONRequestBody = SetupCompleteRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L3pchtH0ij6Khm4X4TI72uAi5axqXDcK1GyR3ckWUFKnnvD8CEK3Qmght1V7apqQrBDf88DnEc8T3Ki",
	"sqp6Q2MjCS3+JiZiLKK7a8nKzMo9/+zFMsulQGF07+zPXs4Uy9Cgor9efsxRaHyV2D+46J31cmZmvagn",
	"WIa9sx5PelFP4e8FV5j0zowqMOrpeIYZs19MpMqY6Z31ioLeNIvcfqWN4mLa+/Qp6v2kZJHvb/gLjAtl",
	"/9rfFJdoTIoZCrOvOT7Zj3UuhUY6lOcsucDfC9TG/hVLYVDQP1mepzxmhktx9C8thf2tmuY/FE56Z73/",
	"66g68CP3VB+9VEoqN1WCOlY8t4P0znqvxA1LeQJc5IWBg4yldrWYwP97+fPbCCaMp5gAvUPzRiAVFOJa",
	"yLmACcc0ORz0PkW9cykmKY8/w4o9aCD2M2qYczMD/Mi14WIK2jCDcICD6QCSwk2PgBnjqVvqj1KNeZKg",
	"2P9anxVmhsLQEhIYFwaENJCjyrixv0ykAjPjGhRqWagYaYFvpflRFiL5HLB000IiUdPaCIxwIBVwDTMC",
	"E4wXoOXE9BNM0aAD4iWqGx7jB8FuGE/ZOMX9r9bOibQwu1KFLFn4c37xHAqhkMUzu5KwQlPkFyVR7p+Q",
	"tGEiRrs8bklDadNXhQBt1wGZTPAp3HDNDRzRT7TI91K+YWLhcVp/hhO3xJDyjBtMBnCBRi2ATQxaPEQY",
	"0Q/9Z/aHEcyQJagGvajn/kXLq71h/2yfUCxFoqEQhqc0YpxyFAYytgBlv7SjVVvIuOBZkfXOTkquyIXB",
	"KdLaP0W9D4IVZiYV/+NznOEbrrVlIRb7PV/UqDWXAmIpr7klz09h/QSNZ7HhN9wsXhnM6HZVMkdluGPk",
	"MUtQxEQZLE1/nvTOfl2/snP/waff2kv75wwFXHOR/IDuygYmEoJw+DtjJp6hBgYqXIpgMMtTe+LjBXjQ",
	"RfRRePBAg1/kAH72TEmaGao5144Z+eG334MXKTr28E6htsjAJ5PGVmge+4OdBIXFh1/LeaOeLi/g3m9L",
	"l2fUk7HdLSZXzDQu24QZ7BueYa/jo9qYW2+sEgS22Vs1g0OaSjz41e21ufJqZ3L8L4yNXWRArndsisvI",
	"xQ1mzX+sW3wDUT+VkzGl2ML+LfCjuYoLpWUHWb9jWoORhDn2RVD+DmYaRu6j0QCejQkCc4upFoUQmEIQ",
	"EjKpEGiVg04Jqw4at5lOaCTJG8zGqGqyEUsSbtfI0nc12ExYqjFqgYsEgAaCuF82Lci91b2gjItnRcLN",
	"S2HUYvmEWOzg9+cy/rHYSHVVaFRXPNlCRox6sUIrROyE5VsOzXP7mihSf487+XXptQwNS5hhqwHvPlwx",
	"UAU4XcQxal0DzFjKFJkgxGRqiuZqavWGFbDZuFI/xhrwbhyCvmVTzyA2vN7GYTtD84SjgAzV7htHuh6/",
	"XnNtLryGcGdG0MLaDl5A4sGm6znqyclEY/O94673jDQs3fRaJxsI34YllXOuBBepmx0X8S2IJ3wzXmxF",
	"RAlOWJESD1UoYvooYx9fo5iaWe/sYWS3X/traQB/4V3FshBbQHVL2s6IZW47qNNn/9wGv+nVjm03ANfA",
	"8dZi2jtef6b3TgIOU/5a2H+J5oNGdSFTvN0lmTOt51IlyyLA+xkCs3M80GBV//AmHGiDeb/ID+3dXkPx",
	"kw5kVNKpiUHGs9zRskY7bods14IKfR1Va1wJBguD++EBTuMN37R1nUrWARYTElvlr6YqJxYmW87EdZ6y",
	"xdUKCowq+aW5ihcYq0VuxXZ6YQBvizQlu0J9HWAhreHAzJArQNH4hhYdK5aNU0yAGXAfgV3qYWMHQWLa",
	"eHvOmL5iN8ww1X3Jb8m8dsSXqDdHvL7ShilT++w4OvltM8nZBYT9NQ4jCojXYGW1HTamXYuU5zTCtqSJ",
	"H1mWOwA0saP3LOUxlus96zH79//j3x9INQ2LPnMg+9Sm8za21S6q7443kvHWonR1gv6aCAuKbskCOg9o",
	"Lcjv/d744AH617g2nrOUeQvFegxZOlmB5ioOToUmT8ql5obfIPwAco6J1RztMT8FgVPmH9gf7FNd5y9c",
	"mCePel3g2F5TasGkEsBbRF2tfw1c9GrUEe4Ut0KcAOUOtNE8y1M+4c68tdVol+UnL3BslgdtQcAutDFP",
	"137PK0tVoMyE8XThmRv9Y8zLf2ZSmBn9a4FMpYtOZnzODE5ll2LslLuUjTHttCHaf3nrozeRI+Q8vkbl",
	"7b2jl8KgMoyLDIUZRTB6KyH2840OB3dQhles6u9FxkRfIUvsxQcWiTpn0Wkx7diToa8yFs+4QOAJCmMP",
	"o9zPVMkYFUc9OhyAlbUmisx1CWQs185HYCQwATyWYgszit0brSXsKGpAvRMHZkxM8aVlsbe4ogTOrxr3",
	"0UDgvLyTYpnVRbezXiyVwtj0Z1Jp7I+ZMagWfW2YHW7pvqoN3nHr1G6v08ePOg5lvVgbszRF9UCD02HM",
	"bWTbJZoL690grzqYv/Ov3E5ot5PVd9gAx5Pmwo+7DKhpsvX3mzbeGCtqLq1z/1JMuMoI6RwsboF6sUzs",
	"qN+f/O3xo0fLyOMet0/+ST/hU27APgWFMfIbJ/06I+ccWJIo1GSyrEGkCY8n9ngt6toR/8evx/3vf/vz",
	"yaf/2EietKROeJCE6E3otwAFy6waEi7m0+Pj4+O2pfrv0hA7yBzU8PeCOTRd+Cu29zd2kjwef4/94/iY",
	"9R+xk9P+9+zx4/5x/PhxPDkdP5mMTyx7yVNuZ/n1z+p63u7bT1H9k+/jY3zIHp70n4xPJ/1HJ8nf+uPJ",
	"d8f9v7GHk5Pxk+Rhcvqo9+m3pXNt7vXPZTFivSQWrgsvVrTVKpJXS6v3iJwio/KOcZqfdB6Tho600n5b",
	"swutnot49KBtVAE+CXM1sXGzVakxVZO2jzdL+lzcwreSeXpbK8NY3HljX7SipDTYIUb+nDuMh4lC7Nu5",
	"gd4ENpaFqfu+WjR6SljfcQsstje3B+TeViazr78SeUFUnHHxyn11skE4q+84amJ0bcEepuWqVnMOsmrd",
	"RsFcsl72Xn64qCJc3iueW/x8zfVYig6FssP6Wel8bqid8PY2mmn7El6lHAY13HtJd+S298yESrl7K7/w",
	"v9nWNmxrdw6EH82VKsROfO6vw08qPGyCYjXxVL7wL0I29h7owosVfv7d7i8jr25tbqh92wJ/Fyw9CdFh",
	"lz7kHaA4Zprrq1zyTjPM8WBwYgXApy7iYy4BhbE6JmSFNqCLzJIufmSxSRdAr/qL1EPeSY/r7VT3YJhp",
	"7KILTC5eZ9mg76m8w+eltQ+Z2EIMr97vnLsKf9kRgzdKnHtx+Te9lk2E+KBRwXwmrbojVYKN+KEBvKAA",
	"ytjARMkMRoFbjODAfuMMEslQ2G8yKXBxCH1gYuGYPzjfHgV6uTUAE2VskhQwxhlLJyAn9puhoIvJfxSV",
	"sUwzro29ppgxio8LK+w57wpZhOhS45psh4Oh2PX62nTJLD1fF4Nw61iL20jUpYD8+e+gjeZFmqqEVLT+",
	"Bqp5iWuXUcNhXAdQy+dSu60qQgrQWUO8F3jDtT/kVlBQwnclMP/JllEBwcW95QlRQPUy4f5zxuOZi7aG",
	"OdMQk6WEBLjSWrsW7A141SBfQrQJ9TZEd8ZygfOrG5YWHXaXtzgHehSBe5+M0p22VJkmq0Z5p/CGy0Jv",
	"N1Snr686mfqhRjWcCOdRX0l9b10o93UFoLRClC9/7j86Pfmbs3kVGhOnD3hQaBLWoUajO4rsbn7CqTXa",
	"/GnfXxU5KougbIpA34CZMQO5wglPU8f4HQj64RqxMBgMxbPCyIwZHrM0XUCcIlOYwHhBn2gXJF565t3t",
	"NFVyriFn2sCpv3W0u0K2YoXLgtongo6Xyk/rIvrpspNnp1id7Rk04ZqLiewM6fwcwTx6NRX4lS1LTuQ2",
	"vyryZH/xGORenLFmNAa48Acfq/EURnWX4Ai4BgZGZmNtpMB7DN3YFA3xL8nFjoC4f39otYjGgrtO91WW",
	"S+WIYc41rvQhx/qmBEor0N5xAPsQmAZugOU5MkWpE/b8zi9/qaUf7OJ8fosG6NFTqPmhPcvhmjzSUd0T",
	"7R/JOerBNs7otg4RNrnJpdyCWkUdOyh8qyH6di0oY5kWmahBdE8BH6thszqMugUXutlxfiHn96tzBcfs",
	"WhXhLjaq+xH1nXBWP+f1IG7KfU0xbrXw3YTK0qxbHNNt3HT6pnfWe8EMRi+qVUchTCA6l9pE536REcU4",
	"Rc/leChOj08f9Y9P+scn0bmcTBCjF1xQnk5hokeD4+Po5YeL6NT+o2//n+71lRbtRC2uVCFC7JpTXbyZ",
	"+52Sun63nf1ap7kNcVexzMizVfvguRzXXh/LcfPlZZ8WwejPpZytOVGxwY+mtNcwbeU2qYwTfcqDGcDf",
	"mUogZjmcPn4C/+DP296RJ6cnjx7tI4K5hGzN9u/RoCOZicAPOVPaa/l2i0wkoNAUSrjfcscNKMVTFgbm",
	"ilOSJxMLM+NiWrsdahdq/Ux3DW6rCWEtAVYgGdAWVnClxZKQ4VhrZLmt57JSWSYLbwptXFKWM224cBZ/",
	"fINtJc/uW6MhfT5cL34u8+ReA0KdYt864W6JE6wKkRr7IKou9U3a0TABgQb8ewRXfxtXKYmcZosgQUUe",
	"ejJO1exWGp69fQFVtpV2asScpymw2BSkI4yDKpHAgeZTe1TiBgVZlULe3NHNyRGBRR/9yZNPR2H1h7c9",
	"q1rU19aHFRH38AfBu0BXWuleXf5c6mqk0WnQiKJ27UdVIio9cYg5FC/k+xnSMp12pClRS3MxTbEfhoxA",
	"S2CQEqnAsDg+fohwAhkyR5pDYUkg4x8xBM7Y9ZaWPHdsLnW8QO3OY4ygjbTKWiESVM6WGM+kRgGjNhaO",
	"QOGUqSRFrUFOvPAuFZ9yq0baHQ+G4sMrn2KqQc9kQQYSVdMBCBrMQMw0thS+nXhb+5juP92jJc8VTiqd",
	"uNz7CtuJYdbI4Pzyl0Gn5FO3Xi5rSlKki0pdcqflbEsy83mgByPP0M+AuPjocCuPYZP53lnJvTsDtHcs",
	"3SK3nbMmkjbmfdIRzlnyoW0Pts65Os4WDshyMbdEUl3ylUOXaxj23rGFHWDYO+xGhdqq7giKyu/ngbIZ",
	"Itc8zzFZLdU4Z4SGA4VOB3X1HCweMn1I8Z8EAsfW0XIqN2RkhZzcBW09Pg7OrQF80DgpfA5EoSYstgLD",
	"fLag6EmH6AlPxAMDXMRpkSDELpaU5mlw+2XsLbf6+HjlXjcfPW3Iv10rukF2zCI2haJby+egU8kNcuEp",
	"xlO7mWHvvTQsDRfnsGcH7Dz71uW/7bXfZk8diN3ebXXSUXXxV6TXiYRLt90W4sYyBt6LmnhbNm5p9Wqj",
	"oWM+k5AznsDBkjbeHawcHNz35dDeaoVlFCRJ3o6nbLniduiNXX5jseu00SYMm+vtwojXcsrFnrPAm0HD",
	"22WlrI10fSsNn/h6Fe8UTvTGlbdEZlR9K9FEVkzuo5VeffqWzE3fCnopm+oBPEtT8JQNRrqbGw7kZHI4",
	"GIr3lYGcBAAaQFdyAEVlW3E+sWzGjmgvGKupkZR9+eb9O+B6KGIpJnxaKEycTNUKSLZbXfgUbpYkXdyf",
	"In4hQzf3K2AZ0JsU5U7xty6mqFO/8xOUdS4qrXP1FPWyGMGfwLWV/lFxlvI/MLHCohRoGXTm3dp67QKa",
	"VSTWz169C1Tvx3vgt5zyUwdGVVHjGo0PpL5F2PSj705Pvn+41qrRCuTeNXp/fQC2KDJUPG4FYo89ct5P",
	"+PU6E+bG7IG7xdev4BU+9GRjgHzjkG9hdFtnqtqaN24A0dYVM9ohl/dk4b1jCOV+4nC+tsCTv1pM5N6D",
	"UhoxE9vFS24s6XGBU67N9iVsbpsCfMd0q32lB++UqHUvbLaWi7QxZ7g6nFUGzcIXFliHpSE/+AZVKe9d",
	"qVoZulYCmpWtmm5ris589/Ple2DQyFIyEkZHNydHrDCzIxp/MYIxTqRCSOV0akUbLgbwI8l8NKiX2KCo",
	"iWyljS4ULZgzDawwsu/W3AihqUsgbT9yb9Uuu6GrUSS/1N7/1m+zS2QqnvmMi8ny0dITCL9J5R0b9gBS",
	"KaaaJ1YYt2OAQk2h9FrWi+bFTAyFQpF4U/jQDfls2ANdS5LlYhoBca4jhTHP6VvnvtdlaOVQWLXBBcNM",
	"eGqsyud9KgwmMk3lvF/kDr+cGDoCJQuR9I3ieZeUf2cL6DccFbPOPeLQos5EmmjxY8oMpFwbEvqZiWc1",
	"lcQZ0Gs2wcjqQqiNs+MDi5XUeihYmgZtgdKFPcZ4c76ZYWYl6FG4AkdkDfMckL4YilE4ZhdXyLUPn6J1",
	"VQP59FgXHRNiJSZUIZTQShdj+42Z4cIjFilxh7QRbnVLn1O5hH/xjOeg5HwouIZxwVMfedwHTjrSfwpp",
	"/jPUqiyzTHQIE5NJEVtaghk3g6EYlYVIr2pXtx4RqDXgDaqFhYBznpT209zX7WOZFFPnkCiPgiZyHrzR",
	"7yP4rzo8D7hIMLe0KYz3TlCY8o2FbG0BI7/bw2iZuGFmWYB/mYcJZ8yOIaTdVxnEEVKTPb8oLcTVPig9",
	"votOu+GyxrEUtOPawko0bcMhAj4V0pKQg50DAXRBYAAvs9x4p4OQFZhp8JZvZiNXaJO1w43tZckm7+4Y",
	"8H7LK/5eoFpsZjvutais5OF3Fa06xG7+Y54R879lCSgxvRozjU8eLaPIc/q9j8KKIwm8e/vTAF6g+0Pz",
	"P9CJLmN07sL4Bzg5Pn0E44VpOAbZFMsohu8+fgc5/4hpO8/65PHxjul+tYWvAEvNVnN3rfMWOiHZOXep",
	"+bgPPfC+Lcu3jkRs62gN6ERrMqladuUNKheVgT6XVlA0t8zx/AbVIQu/axR3LefgBolupU4R4C8NM4Xe",
	"Ed6pjK9X6kq1yBChjZWDYlSYSbGgeN8xooDYH3fy1Nu/5zOeohcrtOFpCvbqXhE/1IKBX03nFpuVeHbn",
	"K+uzHHfmF3chx63JrxMQmcnJAj1dBgIN7ItpbOd5mUlHoivp4cqX0FqlSjNRq3FXVnOhs5cKkyAyI1MU",
	"Usc1CCsflgpat9E/l66sXJkg+eTx44ePNx2iSfXVVra3zOTvUx2sb7eJjg/fdCeMbFXyNrC43QrezlzU",
	"JAEoah54DQCt81uPRx9oL7dMLrba7FWeMnsMH81VrJAKLrFUb45NDB0DvFHGL/6HB0IKfEBSDIMAqaM6",
	"buVK3vBkFfLcngo2XC+3w0qdmfxqdVkkMhuFxwOg+t8WJawWliK7QR+B51tuSIFQCCOLeGZ5rv0QkIR9",
	"t077GZEbcOMfMxBS9N1LFCJm37GKpHP++QSMzZWeb0lde0b1Vbhd8+asMDGuPpPzkl+1TudlHdJBu+rg",
	"ehuvgLWOKIIgriumiCFNu4VLM4rftMetUfiMDHrXWTWloC4zhQpNW4a9hLP0ynI5WZhhL4JhjxVmduWa",
	"0bgfLKhnTCR6xq6xfNIdTLGm3ngLAuHNlQDwKFQrk2f5ghVJDVPGpB4LOnMnL0NiXBNsesYUbiMj7Cv/",
	"vr6Azo1Xfpfd+PAuokuZ57nT/lfsaeUu2ocXil+ROmrJ2qUkBqCsOEeD+Yf8cxVYjkBhH4Wzq4ViiAm6",
	"QDFLSi45ftcKdWtp3V2+O9bFybio/3qy33JdW6TD3mPhq670hVrrlTnTEL5YsgwSR+bOyxLCPg4HQ9Gu",
	"1UN6LJU54BnWSudYBul0XGrdIoBnWUH1JIeiEBQdjR/zlMfcpAu6QmeosFUfYauCXVu2QamcxEtdUN54",
	"+48u8jzlZLWdIlV6oJjOkfOfjgZAIBxLM6PQc2+EjWoJvEOhsK9Qy/QGNdmOyTfmyNJ/L5DT2CR8+RGq",
	"NmA0lR3eDqVjllpdQEl7cxMKp1SfaFRHy5HPrKfU4C9TmGw5WZ6ePi1Na6y0BdfrbmwVmV3523c7NYsf",
	"o62zIHYpXbSC8+xUxWwT31lXEeW9YkJPUHlYyrlApWeu1Blr1CgZwM8iXTRs8fT2UGTMUZ2Zce1L7VD7",
	"EXdiLHV9yujkKvdJmZm+ZR2Tu+dmrc/Ov3QunDJysEzSp/e9BmDVapI16QDJBWSF58O6eD8YCgKUC25v",
	"ZeHPKGnNWX73k4a/Qphf8v7tWFZuBZ6+ubfL8W4mRsvY/7By6HLJh2dvn0F4XMrXLws7+dEblihOUjNc",
	"olVsxZLWpvAGFQWSJnjDY4sgBiuBoxaY92hjOf6WG5T8mQlbBHKwLw/gGH6Ay0IkbBHBCfwAb6T9d63S",
	"ycpq/stnpLeuPtDStFg8w/640KZWf9p9Bx8uXg/AVarV9mZ2fsUiTyVLjlydge0rB3yWlhSlVbReCqGr",
	"+IFxgar7qICwQ9g1PbgKkSgb5C+KsfX6t89eojBYTHwjjKoRIYkPflhNKRVkbWiUEmEGFAUBKSeJrQyh",
	"WQmaHTtjbIwFsofnkItc3eQq86g4gB/RxDPK+DcucIO6fLjsRffOqNsYta1HSV+5vgzbrtQEHQaUTHEA",
	"F8iSvhTp4qmVvDJJQKXA8xnLrYAEN5zRV2MpjQV7DjkzM3s6TPihUCRUG25APXZZYq+XFnjr7cPuzAoJ",
	"b8o0x+Cu98mFhUZ/T1pu2HfcEBP4Y1uD1c4skRKLWYoisdznlb4Li9y24cmtO51QeNfitiXktw9I/2uF",
	"mK8LEV+GMrlq40Jxs7i0clEAgLzm+KywcyxfC40epkC1QriGUWL0lW9wOrKXGZnM4e/v37+DBPNULlxa",
	"IhPJUIyurv4utek3viEWMDr/+ed/vHp5dfny/MPFyx8s4o+8UCco9NTOWpUSrg1QQZHl/B+4cD1Z8aMF",
	"N0tfyLg7dTwpYgM6lrlrgspUPOOWDgtlpymUxZmZMbk+OzqacjMrxhZpjv5VpJyJPkuZiqU4Sqx4T+Lt",
	"0TiV46OMcXH0/PWHl+8uXr19P8gSZweYyNB3lrnu1n4bVRL1rebsLXc3poTsKg4sk2La0PGspGz/5+0y",
	"fasLWzHt2btXpZRSS+1meU4fnJep7vpsKAD+k1KEqIJjSM62OrjnE652DhwICZNUMqMPB9VHr164dz98",
	"ePVCh9+rFtcWxzipCTJnvxfYap4LB2sQLrKjAXRimXSvXB7SlT1e1KJgUznlYuSX4rKbGlNaLL9kGV5y",
	"gz+8Zh9HT6mEBJa3igaF6cJOQcFXFo7nlxc/+hFDr/GxTDjaVy0JNtufazgYdTG4KmnaL45nHtIXP57D",
	"w4cPv4cP78/phH5BZdfMxdQf0PNCc0GGnXKVKb9BlzVPux8N4LlCdm3P39ss4H//z/9ln50GcIyOZshS",
	"M/tjRGQyOiJN1P5Fxz1RLGSb1sHhKArh7c/vrbhkFxayvCwb9pZ/TwRvXr1fwn5psdM1M5dqeuQ/0kf2",
	"XbqgTdqkH4vALpRYh8K1p4NjKgCYo2A57531Hg6OBw/Jg2hmxBTC3qidjPMGW8gTEr5Keme9v/vnrd76",
	"p8fHHQadfzTYau/s19+ini6yjKlF76z3mt+g8B4eNtXkBqLRe7/ZzzxcV67kwj3ediFR7/Hxw1WacDnE",
	"UUcD9nV7uKBAYYtTBzkXUw0vnh+u2o8lLit6HbEiccaCzn1RO6zXXBvXo1S6QkKKZWhC7Ry6AEJQm8eZ",
	"0JWq6tVdOmQfH9fKD582ig93NQiPuifw7a46Zzje5E/oHrJq3loO2b7Df+s+33tpWL6iE2xHB3OHQI+O",
	"TzYjUKO1On20Bdb9KNWYJwk611mdRLTx8johTVlq+oB+rKOab/XWxLQqfHM9qv0UAiK/dUTbO7osd039",
	"6tCljGH3Ye1VVJeIcTfMIaXXHUCKLsCxA4Ne0ENXorUbhez9Uh0w6UiVaO5UuuoMNjlcf3MfozbPZbK4",
	"t+Nt+h8/NdUHu8ZPS7j1qKt9AxmC3FEebz7K56xsT/W5UMZ+8WjzF2+l+VEWwk1x+vDe4OzKzndQzaXr",
	"CgaKGez7/IRBC8MvK2NbrUi6w+kIQl+xTcitM5OvZ4o/oakF3+2RqdRm+bKMZGesaJzLT+jjZ4Ixz6kt",
	"q5lN1POBDx3Ad16AFvz3QPArouK2Iv3PhQFuaV81P2kgglvvbriwRJtH9XiOaVdQqu/PrJcqGzaCuIDp",
	"Kh51AIRcZDh1thcSqfqpnE6RXh3RCq5uOM6vGpF8o1WhrUNRJh9a/fmnl++huZMR9J385ruDOEMn15Bg",
	"YtEFk6EISmIEcypIn7HrZoOGEIfgN2vXZxUTpz120M8F3iBL64Fx++ZgSwF4Xwkv2/OF5V0YQhqonBjk",
	"BFkRKtikFXdOLjrD1e9rYu8uFKNRJH3jLcO5j3Ft2ytFooE561Cf8Nh+4N09ZqZkMZ35ejVlUjOtyNe2",
	"MdKXFmQp1csKcVXBq9R0HA3gciHimZJCFvqsJE4KGylSX65lkjpDf8IVkv/aJ+aFYyWLmSzMWH6s5c0e",
	"RkOhZYhv1L4eGQLPMkw4M1gN5JSnD69WEouFSgjCfOlNxHullUa0ZwdWXTjweF+FJg+yMZjlZvCNCAPO",
	"6w2KkLuGYbI6ER+NF3yMu2B6G8k7ztSC+POJb7sdaCyF8FnmdiffypnaTTbCdG5/w5M7dbNN4oN2JfP+",
	"orYvXyTxykcOdI/tnXlL4dV7N3Ms9fj/Gq0chEjrdYzVPMI13Pvg6m3sQ70o4Rj6Yu6gXZzc/yq6TtCt",
	"7Ks3Vny/+QvL6VMe/Lglqpz7lmkulqJql7YLp9rFBubR6d8msL+gCWw3NPyCNrOnViFWi1pKbyxlmsi5",
	"WGtNczSyhSktWm83+6w0sO878Js3yjFfgL5+ujvwvYYlZoVaGSuWjVNvsvBB2naEB7pSZWdMzyJQeCOv",
	"MVSNCXVdQmyBD7bIXHElX0OVau60Cna5ii8LqvVC0YZDISii309WV2W1YSJhKgELLjQwSeXcWXOcZugy",
	"lC1u6aFgYPUsqZhaVImAq60s2iF7zcjy35vxB0CAA7XT+n4vsLA8ySHGAx1CSbTHhmTwb1/Jnnwl6GvD",
	"EOmzEqP79ePZ1XVSYw1KuvjCnJl4tuI+uHQkcmFf/XbJo72VL+QpWHsrfQOOgr+01NWmvncUmY0gFSRI",
	"/9pewgoUV4birbZ3UdH2PWmwjYLwnxnXV6H5a+et4eJpOybRGWhcLX1aziWa/rmLkm1M22Yan+6I//vF",
	"tWc+34QyMDWMQyZkI0djxpwXghJSSnP8Ar158XQLInov5RsmFv649frIPTkFwroScYtGlJvHW1mYtYhr",
	"n28jV/gzt6+3LEGSmtXBAXnmStHicP3KmvfgUVyVeO9eqa8B3ygZvieK66w9/5VQXiXdScNIzVwmwMFd",
	"KHD3S+vkeP/0Vy+t69QP/JhTJRupyjTUQgc59r5JLZRYq8lvXrwuNCUTzrChHO2E+qpKJunW7Z6lc7bQ",
	"3huXaDg9fkQ5vDeSJ2UmHFIeCAHIufk0yyoP3lDoGcvRufu8r3w+c3nQFSOjp65OtIOskMano1M5VPdW",
	"6CnHRKiI6UVbOheuAUVQNyjJmHo6CUktDYfCJ0cN4KJ2bVN3vFfvurQ8fz6fne7vqoY9i2PMrUQCzxxg",
	"Mrag8qfueiBQ3kHtum8Mf45TLpbR+0B7d3VD9Q/JRRtYfMCl1Zj9z3oOYs3fbVFS4LxEbkrK0lCIcKue",
	"NfzTQzGWyeKBhlFnyW5KAB1R6k4EQnakUWg0kY9GKXd6s8RyLGq7Y6u8qN7J/r5e33woqMA5N2uLmpfG",
	"k1S6yuYNYAhp6p1oGkmvvFXRvOFxD6VIa5SPRlOPlsau/1VoAym/purqXHSTnj+//ZBbu1/AZ/bJLFXE",
	"X+2aGcBlF8rU+gyuQTzyHn7mK3m7HAvj6lAQuG+n5d0zEwpH4uuk+TL8aziMI6nVQmMtZXNPSNyRFPqV",
	"SIq/eO7wbwnxc0iIDg/sBepqr7Zy7bmZ7SgkOtQme7lItpANXfClFQ2bnWWXpbxSfgtrHYr6YqO1suUO",
	"clu7JcberpFVvTfuQ3SzfKhDfNMozFcjuzkI+Fu/hnVLEsxKjKuq4a+MCHrNtTmvXrsjQ9uqIk5ont/R",
	"Een+3IEdQS0h57CrWcCBRkwwqUu+NeCVAA2ZzhvDFpybPrQMWzLOd+2keuXIf/cq6XU4YjcFBXz9EYyN",
	"NJPyNA6qlBOXO14/jAD41R7yn9DsBdz3eMf55X3LXm9XvqX0e5dn57P9SXReeW6lL6vVdTLhVBrQ56af",
	"waj2fBS1yt1FzUYdEYxCKbrRYCguywp6sKqAnhPsO0voRa4mn7qh2xNZPPOo+IBS7hlZRaicn71DlJyT",
	"zpZT4URSHkehBbHCG06O2NFQTKTyTnk3Tde12qheeWcEvv/buLO65meWiNfQz1/RP9eV+VPbdQQOhaOy",
	"nw7lRhAxwIH7jwxFAqk4jlTryLPrhjsq0Xit/FCiRXj5CzLgrSSQ1oL3Koh8dg5dpClgwg3MuDZSUWGm",
	"+jUr06TszbUeFzYkuDdy2/d/aC4F+vPKjPWWYj40n8yBY6RueGBkDYAeXKtDo53ZKaRy74NN12b4QuY3",
	"f0pfQTh0d6zy1EN/6dAaOL+lfL8iK38Dt6Ov/qKy/YsQ7+pzx+sXz1OImY5ZgvpwBdV0xzrV6uveEdb7",
	"kot2J7jj/RPcv2OWTLcQVSKnQsEyCiJygnlZSThULD7cjlEcMd9Jb+1VGdrt3R6Ho6Ui2Owj0N3pyt6a",
	"QokB1Gu0Pz4ehJJ2t8zqOtkmq6tdapwKqcWF0vUGsmMyo1qJUha69GM9pZLxZS041zE0Z1NctXA37Jcr",
	"a+RP8R2brtXkv4FqAiThWKBnqChJ328NJujbNpSUUu/nGtnj4cLyloajOKB3J4WMWcpEvMYO+ROa5+Gd",
	"e7xQ7+/gw+q+xqS9n9CAQAMByvBfoMs2b5Az7oI1EhwbXT/Y2vGVB9R5fKVusIUa+AXPbxfl7ytT+lbo",
	"HlVtzQYNrjaxrVE8bmtd2rcM1VjdF1Jb1tiWvoE8zk5Vp1T5t9DxHZXXupavyu1N6p3KvzZEepYkbmVf",
	"UvcNXdw7go2T5K9sonyWJFW7ECMr4YGLG26warRcxSJuK197xDz6s9CoXrU18+WeVE2jZ8wEKMzkjatq",
	"JqToh0ehT8ozsQgrz9hiKPzrZoaZRurmc0AtBA99raJqZCGN7y4olduc/TKB/lDUOrOEli1SwaQIJQSB",
	"tuALEAcsdfx9MBTvy3y/B7p+uZeisneVeaCGFiV/oJJw4JoNQ5EPhbsvqJM7rc3HtWY+OU/zFIX9kEoM",
	"a5CTCckJA3hV6/hCdZQ0FLkLeZjgnEIPmKhaokQE3JwLK+uPGq1bRsD1UFAYuRUz6+0LukMMLAjvhdFE",
	"nXlQDovuOT+2w3TjVh9Q4q9L+ReeuAIJlVYft3NtMUMKfBpQhYIuypacnsK25QUKrXbOxbS/lVB6EV7/",
	"RqTT9nq3FVOX5ccSUKXp32CWp8xSebcOUH6xUZRcWuXXKVO2l/nFQlLbZ3r/UuY9CIxrMGYFknSQp7t5",
	"stAwcSVdXtbe+7opslrp7WmxBhWgePw26dXBton4agv6OsmuWuAXIrj6kX37Ct0FNeCkUP+wLTiQAsN1",
	"m7OFDp3/DlfilKdVnuVSWVBZwWzOfU/kzhjUd0xRUw+4DO/C+eUvljdI5cpl+l6WuSubqUOCQpGaoTgY",
	"JWpxpQpxBpSicUh2dpll3NKAgdpz33QCxgvfUFRMXaj4UBCdROCaatrf/Z5dAQtXzKL8xsLECvVSYWU3",
	"yVENhevsp+SceldU+4nLPiNnQOE+Ss4f1Fp3xjItMuEbjYW6G5pPBSZDURfKvQMhyOZKzuFgRJFC0Iec",
	"8WR0OIC3OGVlYpVv8xkrTLiRSsOBfc0tniRrSiSRczyMIJe+BXX5IcnoUukBPBuKOaYptfRE2iPownkE",
	"nC5gJXbqblW4CGYjU1R20YcEvRnTwMxQpMi0cV3RfTknAojmCQ7gQtLpMgM3XNoLwZc9v2GKM4uOLE2H",
	"ws4XuQQ1C6PILgSMlDBhCiZKZuDeGKdMXFO0ChU1UYynFHA17L2XhqUBqMOe3c0hbVdf8zzHpFJX6OBl",
	"IQzlKw/FyL9xRT/6mrJWXI8NuJD4oRi9YAajF7UYmhCKGp1LbaJz7/aJhsXx8cPYagsn9E+s/XLqfxkM",
	"Bk6vQTGRKqZ+I0Pxo5V6LbDmM1RW5U0Nz9NwcHTCB/RjPxw8vX4YEbQrdIAxxpKar4BGy8BNidJPQzfl",
	"sAuYukyg0a/XR//4bTQUuphM+EdfyQUcxWPiFUYqmMrTFMZ2Yip1S7AyBPrw8lC46CIS1ccIFHYe0NJT",
	"iZAZFyyFWGrjKoJyDTHTCAfNzVBdknTSd/TANSRK0mmOMWaFRqhaDLncG13kxKWGwuKji2XKLdU7CBAp",
	"1azdZTteZTVvrwnTcbypcwt6z+rrxA3sFQBsyrjwXhBC+4QZNrZbCMHyRBjXrks9j2chNQxDjGEwZQzg",
	"g++w4yeb+to5UvQpE4siHPOUxTiTaYKqSoKTlm0gnwq4xoU9HeZbkT71DJWl3phApow4ZTxrJo5ZiWJS",
	"UFMcKsFjt/53phIgL58+g9PHT+Af/DkoNrc8/Ck8Pj4+Jsx7Cg9LFf6pi8CElPp+DYX9Kp4xy2WqEHHa",
	"d8bo/Oxh97koW+RbuqwgOhQuqBpSNsYUUq5NZHk9lbcds/iaIibp2hp12QFeES6WzHpPITOtWb6QF39p",
	"FaudTO/cbQsHLpC1dctaaeM+RakdFublqqWF+ev9C0X+uA2U1ki6hlaINAeng0FFDXVRyktNlRiV4ebo",
	"oDf7Qtn7KSgVal+U3VXLfDJnqPus8vG3Vc5vKR7woGxAq6HelzICHati7BOMI/ClNFialpW6OpKtV2Q4",
	"eHz6zPmG57V93gc9/oRmCX5dIFgbDLY30mr3yP5Kkj4/eyxXSwGlOKnNp1Yyx6N6u+B1PPJZaNK6Bb9y",
	"zawb3Omu+wpensa+HujQOPvASiu6lFW44IazlHpoeyrvpN7O5iuXaGqb3cOlEMa/873g9q7ZzRdDuA/U",
	"PRqYgO8+fhcO493bn+DAyuZPHvVRxDLBJAKnl/0AJ8enj2C8MKgP16ElseEjp6z3O2oTtWx5AnQRx6gb",
	"6n9ZU8W3Y48a7Lw0AbjiKVbF96UYnbGCwUShnnUUq+BaF1bDlQ2EJC3NKq9WLdCQhgpdXQKza/FOSeuh",
	"vNGezHxudDcTTfqV8UtaWTigp5Tt+8Wz5W9nN9y1dsNfKSe/VqeJ8K2Whu+I0FvddkvDb7OBjXWavNzo",
	"atPELE2JDQQCLSvrBE+8LizEMXFmFYt6NN1QcA0zq16Tut5I4jbyGgWxBzJ/5Kg018anFJLpaEBjjIai",
	"2cD+3c+X7x1zoux/C5lGRR8jh2K0hveF3kt+L6Hi3TVirmEuFRk+CmHs8v0njiViojdwoID6e+JAyxNt",
	"xXpOl4/3nKoek1GdTzqqFh0+BTZnnCzMHgauZELvq2YEX0upzlCByiOeI9xJKudVESqPqlV5KIeGa29y",
	"IU1JP2ujit8s3jZe3eNtVJ/oncKJ3l92WpcWRSbZagWQK5ygQh9SvaOC1QG1+6fiFQD7fPLDVif2ZZUv",
	"n7Ryp8OuyKar4nwXC2/0ttsX+64K891TaXTHY75YjqGTRjpOqmo653enQaZJ+fNqRrcc7LRlZuKdA3TK",
	"AW6XqPhFcg6r+JXt4lY0MuVYYGcbzPOWdwN0MXZagJO2QN6EAkw+XKZRuOJoJKRBKgBBdS3KEn41Nz69",
	"MnJulwG4XmbOwxIqMRnpk5Cr7oCoqOxEcIXLSQT4kfpdga6MlOQK9h5y56pyeVjUzgG16btUK9/FutbX",
	"+mC8gJGMCYWTK2ZGkV21gFHs7Pv2p0MfoCpzV1YDFObO+D+iUa54MoISm0AwpaSPD3BAd9e91Ohd/Ppp",
	"cE8mGpobFdLUN+vcwcENzKeCmj+2ltMoEdKxEOUhTWHKrpbJUIRvCGSUPoMahmXMPMnmwx70G9E8jGIN",
	"CPpUelUMBTdl7UnNRexLQlKRKSHLag2Vw9BueUGON3LY+zpeXeL1pUPYJVpuSWUlmho/2gD+OeMGdU59",
	"HDUYRaUlV6XY/b42NDZjH1+Tg7Bq+Vb+vRwou5QdeEGYYpc24alxoeL1wA2HDgP4OXOFNj2+1BC0hh5V",
	"Hr7dC37MU6v5+SV3bS1gZyN/sAwD2xD1247+inraLFL7g/2wIz/zLaFbF7bV0IDqgzpsaeLVUJSIRV6r",
	"evnPOvZU1LBwjGYZjToTKSsS6e0S+rwmCzXwmGYS6snxbbJQXeLp9s0F95n75+hum8y/zy50uKVV4U6W",
	"dzXwyPH3huliGop2VJFixFdqF2M5wJbyxh1iEqtP/zvUO2sE8a2reNaOCF2l3+4R8sefKSDz2+z5VTvI",
	"8QIosIsOsd8ustQZh6nRFLlr+7Pa8viLD1QKkpMpcm8rPPCOACPh2btXoE0iC0NBe1RobCylgfmMW7HG",
	"ReppY2/QGBVmUiysEOBNqYdVDKWfh0Zw0mFBrgeyryqZ4g+03gG8SjDLpUWLMxKKLTsThhiM9q704Dhx",
	"V8JQPDo5hp/sPd8sY0q76bQk+tL8VM54fy6zIg8TfaFQ5VUeDGpH5I/la6j1e5+5tqvMia98nG4N0Qdf",
	"rxeEsKd0d8QejXzQXhfBxancfycLotu+KoSHYj2mumrZ7iMHB00uVeRt/qQNM8Va8ypB4dK9tt8LpJxm",
	"TdbFykq6roxyKJrcBtKMaVf/tzzFNZCpNWmrohw6DQhhWtcqUVLyY+XLrjuKfbiyLJRT0Lzne8xNxvKh",
	"KMgf7mqokCSXchTmqb8V1A0qKHKqdkmh9cSvBTJl1XyBfDoby0INhWZWqRXT0KrArolNqeUjN6BQWGYC",
	"seI6B2Yon/P88hI0/wMHcE7Sox4K8nO5UF5Gua8+bNwJMqUvrtarcgDPnRdbg57JIk2srh1bfV3A6P++",
	"+eFPB5Ur76+9YubTqKpWbQkJy9WV/i8KiLWgoQuy6wrx7VLLqIuvoGkqz9gUj3IxbWJ+OfCYC0b60RLb",
	"XooCffuTi3f4VoRgi6a+S9sDDTn/iKkLwa5FdxAK9b2ph5EA0WUbbVK6BbC9957Zp2e//maPwRFFl3Hk",
	"tYxZCgnewMELGV+jAss6pUY7UaHS3llvZkx+dnSU2jdnUpuz746/Oyb52C9kmc7rZdYp2pv+IwsTBVOw",
	"yydJpbwu8kGFcbSlZZXalVUkycxHo8543sw9D91CWJLYS4dVGewxE8CSxHXp0YOW8UN3TBdyYx31MjXm",
	"htq0upD8TCao4QB/L1gaufD6CHJUMQoTOU6gDwdQU3OSAbxMuNX+FYuvKV6lqzRubWllLu/y4i5dEHlX",
	"0W7M5L84/BfotJgeDuACWULSt53v5mSwZOvgnRNYBCgsKjZK6JAivaqIzgDeuux54uq1icoyOsvTjP4/",
	"l//x/49AUUaXz6iRk4muTVwbrK44LI/3vszmzZhBxVlqKRu4oFpgLK1sAv7WGLP4ekppQOTaR1WbqrKO",
	"d9h3qDxUreyTKxAlJ6utDrX84gjqhWvqqB8KRnWciJJa933AdpGmfYMfTbAEktU9YEPtO31E9vbWWsD9",
	"WNfNXMZNA85k/lhex/Mive672G9yWfsTmy0S5TJmx4qJpC9w3oguF4AfDSrBUrqdeYwPtI8xH4CPp00X",
	"zRh03Y4+r60vRJ8vL/A1v0FhVSm7aSuIcvorV3JsN02NlSytYVIfb4Ys7WQ7r6zUKmLsz3niRcWSsVny",
	"8r6rShV8ag/AqML1C7tBNS4rWVhF2YcHlO4v7tOHnEQLY5ks6ghByvDyqn4spbW2VD2AZ25m37GHp2Ri",
	"dzKu6+nYJKci73367dP/CQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
